/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "EUTRA-RRC-Definitions"
 * 	found in "../asn1_defs/EUTRA-RRC-Definitions.asn"
 * 	`asn1c -gen-PER -fcompound-names -fnative-types`
 */

#include "CSI-IM-ConfigExt-r12.h"

static int
memb_resourceConfig_r12_constraint_1(asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	long long value;
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	value = *(const long long *)sptr;
	
	if((value >= 0LL && value <= 31LL)) {
		/* Constraint check succeeded */
		return 0;
	} else {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

static int
memb_subframeConfig_r12_constraint_1(asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	long long value;
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	value = *(const long long *)sptr;
	
	if((value >= 0LL && value <= 154LL)) {
		/* Constraint check succeeded */
		return 0;
	} else {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

static asn_per_constraints_t asn_PER_memb_resourceConfig_r12_constr_3 GCC_NOTUSED = {
	{ APC_CONSTRAINED,	 5,  5,  0,  31 }	/* (0..31) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_per_constraints_t asn_PER_memb_subframeConfig_r12_constr_4 GCC_NOTUSED = {
	{ APC_CONSTRAINED,	 8,  8,  0,  154 }	/* (0..154) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_TYPE_member_t asn_MBR_CSI_IM_ConfigExt_r12_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct CSI_IM_ConfigExt_r12, csi_IM_ConfigId_v1250),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_CSI_IM_ConfigId_v1250,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"csi-IM-ConfigId-v1250"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct CSI_IM_ConfigExt_r12, resourceConfig_r12),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NativeInteger,
		memb_resourceConfig_r12_constraint_1,
		&asn_PER_memb_resourceConfig_r12_constr_3,
		0,
		"resourceConfig-r12"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct CSI_IM_ConfigExt_r12, subframeConfig_r12),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NativeInteger,
		memb_subframeConfig_r12_constraint_1,
		&asn_PER_memb_subframeConfig_r12_constr_4,
		0,
		"subframeConfig-r12"
		},
	{ ATF_POINTER, 2, offsetof(struct CSI_IM_ConfigExt_r12, interferenceMeasRestriction_r13),
		(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_BOOLEAN,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"interferenceMeasRestriction-r13"
		},
	{ ATF_POINTER, 1, offsetof(struct CSI_IM_ConfigExt_r12, csi_IM_ConfigId_v1310),
		(ASN_TAG_CLASS_CONTEXT | (4 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_CSI_IM_ConfigId_v1310,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"csi-IM-ConfigId-v1310"
		},
};
static const int asn_MAP_CSI_IM_ConfigExt_r12_oms_1[] = { 3, 4 };
static const ber_tlv_tag_t asn_DEF_CSI_IM_ConfigExt_r12_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_CSI_IM_ConfigExt_r12_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* csi-IM-ConfigId-v1250 */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* resourceConfig-r12 */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 }, /* subframeConfig-r12 */
    { (ASN_TAG_CLASS_CONTEXT | (3 << 2)), 3, 0, 0 }, /* interferenceMeasRestriction-r13 */
    { (ASN_TAG_CLASS_CONTEXT | (4 << 2)), 4, 0, 0 } /* csi-IM-ConfigId-v1310 */
};
static asn_SEQUENCE_specifics_t asn_SPC_CSI_IM_ConfigExt_r12_specs_1 = {
	sizeof(struct CSI_IM_ConfigExt_r12),
	offsetof(struct CSI_IM_ConfigExt_r12, _asn_ctx),
	asn_MAP_CSI_IM_ConfigExt_r12_tag2el_1,
	5,	/* Count of tags in the map */
	asn_MAP_CSI_IM_ConfigExt_r12_oms_1,	/* Optional members */
	0, 2,	/* Root/Additions */
	2,	/* Start extensions */
	6	/* Stop extensions */
};
asn_TYPE_descriptor_t asn_DEF_CSI_IM_ConfigExt_r12 = {
	"CSI-IM-ConfigExt-r12",
	"CSI-IM-ConfigExt-r12",
	SEQUENCE_free,
	SEQUENCE_print,
	SEQUENCE_constraint,
	SEQUENCE_decode_ber,
	SEQUENCE_encode_der,
	SEQUENCE_decode_xer,
	SEQUENCE_encode_xer,
	SEQUENCE_decode_uper,
	SEQUENCE_encode_uper,
	SEQUENCE_decode_aper,
	SEQUENCE_encode_aper,
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_CSI_IM_ConfigExt_r12_tags_1,
	sizeof(asn_DEF_CSI_IM_ConfigExt_r12_tags_1)
		/sizeof(asn_DEF_CSI_IM_ConfigExt_r12_tags_1[0]), /* 1 */
	asn_DEF_CSI_IM_ConfigExt_r12_tags_1,	/* Same as above */
	sizeof(asn_DEF_CSI_IM_ConfigExt_r12_tags_1)
		/sizeof(asn_DEF_CSI_IM_ConfigExt_r12_tags_1[0]), /* 1 */
	0,	/* No PER visible constraints */
	asn_MBR_CSI_IM_ConfigExt_r12_1,
	5,	/* Elements count */
	&asn_SPC_CSI_IM_ConfigExt_r12_specs_1	/* Additional specs */
};

