/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "EUTRA-RRC-Definitions"
 * 	found in "../asn1_defs/EUTRA-RRC-Definitions.asn"
 * 	`asn1c -gen-PER -fcompound-names -fnative-types`
 */

#include "DRB-ToAddModSCG-r12.h"

static int
memb_eps_BearerIdentity_r12_constraint_5(asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	long long value;
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	value = *(const long long *)sptr;
	
	if((value >= 0LL && value <= 15LL)) {
		/* Constraint check succeeded */
		return 0;
	} else {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

static int
memb_logicalChannelIdentitySCG_r12_constraint_1(asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	long long value;
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	value = *(const long long *)sptr;
	
	if((value >= 3LL && value <= 10LL)) {
		/* Constraint check succeeded */
		return 0;
	} else {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

static asn_per_constraints_t asn_PER_memb_eps_BearerIdentity_r12_constr_6 GCC_NOTUSED = {
	{ APC_CONSTRAINED,	 4,  4,  0,  15 }	/* (0..15) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_per_constraints_t asn_PER_type_drb_Type_r12_constr_3 GCC_NOTUSED = {
	{ APC_CONSTRAINED,	 1,  1,  0,  1 }	/* (0..1) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_per_constraints_t asn_PER_memb_logicalChannelIdentitySCG_r12_constr_10 GCC_NOTUSED = {
	{ APC_CONSTRAINED,	 3,  3,  3,  10 }	/* (3..10) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_TYPE_member_t asn_MBR_scg_r12_5[] = {
	{ ATF_POINTER, 2, offsetof(struct DRB_ToAddModSCG_r12__drb_Type_r12__scg_r12, eps_BearerIdentity_r12),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NativeInteger,
		memb_eps_BearerIdentity_r12_constraint_5,
		&asn_PER_memb_eps_BearerIdentity_r12_constr_6,
		0,
		"eps-BearerIdentity-r12"
		},
	{ ATF_POINTER, 1, offsetof(struct DRB_ToAddModSCG_r12__drb_Type_r12__scg_r12, pdcp_Config_r12),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_PDCP_Config,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"pdcp-Config-r12"
		},
};
static const int asn_MAP_scg_r12_oms_5[] = { 0, 1 };
static const ber_tlv_tag_t asn_DEF_scg_r12_tags_5[] = {
	(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_scg_r12_tag2el_5[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* eps-BearerIdentity-r12 */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 } /* pdcp-Config-r12 */
};
static asn_SEQUENCE_specifics_t asn_SPC_scg_r12_specs_5 = {
	sizeof(struct DRB_ToAddModSCG_r12__drb_Type_r12__scg_r12),
	offsetof(struct DRB_ToAddModSCG_r12__drb_Type_r12__scg_r12, _asn_ctx),
	asn_MAP_scg_r12_tag2el_5,
	2,	/* Count of tags in the map */
	asn_MAP_scg_r12_oms_5,	/* Optional members */
	2, 0,	/* Root/Additions */
	-1,	/* Start extensions */
	-1	/* Stop extensions */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_scg_r12_5 = {
	"scg-r12",
	"scg-r12",
	SEQUENCE_free,
	SEQUENCE_print,
	SEQUENCE_constraint,
	SEQUENCE_decode_ber,
	SEQUENCE_encode_der,
	SEQUENCE_decode_xer,
	SEQUENCE_encode_xer,
	SEQUENCE_decode_uper,
	SEQUENCE_encode_uper,
	SEQUENCE_decode_aper,
	SEQUENCE_encode_aper,
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_scg_r12_tags_5,
	sizeof(asn_DEF_scg_r12_tags_5)
		/sizeof(asn_DEF_scg_r12_tags_5[0]) - 1, /* 1 */
	asn_DEF_scg_r12_tags_5,	/* Same as above */
	sizeof(asn_DEF_scg_r12_tags_5)
		/sizeof(asn_DEF_scg_r12_tags_5[0]), /* 2 */
	0,	/* No PER visible constraints */
	asn_MBR_scg_r12_5,
	2,	/* Elements count */
	&asn_SPC_scg_r12_specs_5	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_drb_Type_r12_3[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct DRB_ToAddModSCG_r12__drb_Type_r12, choice.split_r12),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NULL,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"split-r12"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct DRB_ToAddModSCG_r12__drb_Type_r12, choice.scg_r12),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		0,
		&asn_DEF_scg_r12_5,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"scg-r12"
		},
};
static const asn_TYPE_tag2member_t asn_MAP_drb_Type_r12_tag2el_3[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* split-r12 */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 } /* scg-r12 */
};
static asn_CHOICE_specifics_t asn_SPC_drb_Type_r12_specs_3 = {
	sizeof(struct DRB_ToAddModSCG_r12__drb_Type_r12),
	offsetof(struct DRB_ToAddModSCG_r12__drb_Type_r12, _asn_ctx),
	offsetof(struct DRB_ToAddModSCG_r12__drb_Type_r12, present),
	sizeof(((struct DRB_ToAddModSCG_r12__drb_Type_r12 *)0)->present),
	asn_MAP_drb_Type_r12_tag2el_3,
	2,	/* Count of tags in the map */
	0,
	-1	/* Extensions start */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_drb_Type_r12_3 = {
	"drb-Type-r12",
	"drb-Type-r12",
	CHOICE_free,
	CHOICE_print,
	CHOICE_constraint,
	CHOICE_decode_ber,
	CHOICE_encode_der,
	CHOICE_decode_xer,
	CHOICE_encode_xer,
	CHOICE_decode_uper,
	CHOICE_encode_uper,
	CHOICE_decode_aper,
	CHOICE_encode_aper,
	CHOICE_outmost_tag,
	0,	/* No effective tags (pointer) */
	0,	/* No effective tags (count) */
	0,	/* No tags (pointer) */
	0,	/* No tags (count) */
	&asn_PER_type_drb_Type_r12_constr_3,
	asn_MBR_drb_Type_r12_3,
	2,	/* Elements count */
	&asn_SPC_drb_Type_r12_specs_3	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_DRB_ToAddModSCG_r12_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct DRB_ToAddModSCG_r12, drb_Identity_r12),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_DRB_Identity,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"drb-Identity-r12"
		},
	{ ATF_POINTER, 5, offsetof(struct DRB_ToAddModSCG_r12, drb_Type_r12),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_drb_Type_r12_3,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"drb-Type-r12"
		},
	{ ATF_POINTER, 4, offsetof(struct DRB_ToAddModSCG_r12, rlc_ConfigSCG_r12),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_RLC_Config,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"rlc-ConfigSCG-r12"
		},
	{ ATF_POINTER, 3, offsetof(struct DRB_ToAddModSCG_r12, rlc_Config_v1250),
		(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_RLC_Config_v1250,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"rlc-Config-v1250"
		},
	{ ATF_POINTER, 2, offsetof(struct DRB_ToAddModSCG_r12, logicalChannelIdentitySCG_r12),
		(ASN_TAG_CLASS_CONTEXT | (4 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NativeInteger,
		memb_logicalChannelIdentitySCG_r12_constraint_1,
		&asn_PER_memb_logicalChannelIdentitySCG_r12_constr_10,
		0,
		"logicalChannelIdentitySCG-r12"
		},
	{ ATF_POINTER, 1, offsetof(struct DRB_ToAddModSCG_r12, logicalChannelConfigSCG_r12),
		(ASN_TAG_CLASS_CONTEXT | (5 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_LogicalChannelConfig,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"logicalChannelConfigSCG-r12"
		},
};
static const int asn_MAP_DRB_ToAddModSCG_r12_oms_1[] = { 1, 2, 3, 4, 5 };
static const ber_tlv_tag_t asn_DEF_DRB_ToAddModSCG_r12_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_DRB_ToAddModSCG_r12_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* drb-Identity-r12 */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* drb-Type-r12 */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 }, /* rlc-ConfigSCG-r12 */
    { (ASN_TAG_CLASS_CONTEXT | (3 << 2)), 3, 0, 0 }, /* rlc-Config-v1250 */
    { (ASN_TAG_CLASS_CONTEXT | (4 << 2)), 4, 0, 0 }, /* logicalChannelIdentitySCG-r12 */
    { (ASN_TAG_CLASS_CONTEXT | (5 << 2)), 5, 0, 0 } /* logicalChannelConfigSCG-r12 */
};
static asn_SEQUENCE_specifics_t asn_SPC_DRB_ToAddModSCG_r12_specs_1 = {
	sizeof(struct DRB_ToAddModSCG_r12),
	offsetof(struct DRB_ToAddModSCG_r12, _asn_ctx),
	asn_MAP_DRB_ToAddModSCG_r12_tag2el_1,
	6,	/* Count of tags in the map */
	asn_MAP_DRB_ToAddModSCG_r12_oms_1,	/* Optional members */
	5, 0,	/* Root/Additions */
	5,	/* Start extensions */
	7	/* Stop extensions */
};
asn_TYPE_descriptor_t asn_DEF_DRB_ToAddModSCG_r12 = {
	"DRB-ToAddModSCG-r12",
	"DRB-ToAddModSCG-r12",
	SEQUENCE_free,
	SEQUENCE_print,
	SEQUENCE_constraint,
	SEQUENCE_decode_ber,
	SEQUENCE_encode_der,
	SEQUENCE_decode_xer,
	SEQUENCE_encode_xer,
	SEQUENCE_decode_uper,
	SEQUENCE_encode_uper,
	SEQUENCE_decode_aper,
	SEQUENCE_encode_aper,
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_DRB_ToAddModSCG_r12_tags_1,
	sizeof(asn_DEF_DRB_ToAddModSCG_r12_tags_1)
		/sizeof(asn_DEF_DRB_ToAddModSCG_r12_tags_1[0]), /* 1 */
	asn_DEF_DRB_ToAddModSCG_r12_tags_1,	/* Same as above */
	sizeof(asn_DEF_DRB_ToAddModSCG_r12_tags_1)
		/sizeof(asn_DEF_DRB_ToAddModSCG_r12_tags_1[0]), /* 1 */
	0,	/* No PER visible constraints */
	asn_MBR_DRB_ToAddModSCG_r12_1,
	6,	/* Elements count */
	&asn_SPC_DRB_ToAddModSCG_r12_specs_1	/* Additional specs */
};

