/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "EUTRA-RRC-Definitions"
 * 	found in "../asn1_defs/EUTRA-RRC-Definitions.asn"
 * 	`asn1c -gen-PER -fcompound-names -fnative-types`
 */

#include "EPDCCH-SetConfig-r11.h"

static int
transmissionType_r11_3_constraint(asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	/* Replace with underlying type checker */
	td->check_constraints = asn_DEF_NativeEnumerated.check_constraints;
	return td->check_constraints(td, sptr, ctfailcb, app_key);
}

/*
 * This type is implemented using NativeEnumerated,
 * so here we adjust the DEF accordingly.
 */
static void
transmissionType_r11_3_inherit_TYPE_descriptor(asn_TYPE_descriptor_t *td) {
	td->free_struct    = asn_DEF_NativeEnumerated.free_struct;
	td->print_struct   = asn_DEF_NativeEnumerated.print_struct;
	td->check_constraints = asn_DEF_NativeEnumerated.check_constraints;
	td->ber_decoder    = asn_DEF_NativeEnumerated.ber_decoder;
	td->der_encoder    = asn_DEF_NativeEnumerated.der_encoder;
	td->xer_decoder    = asn_DEF_NativeEnumerated.xer_decoder;
	td->xer_encoder    = asn_DEF_NativeEnumerated.xer_encoder;
	td->uper_decoder   = asn_DEF_NativeEnumerated.uper_decoder;
	td->uper_encoder   = asn_DEF_NativeEnumerated.uper_encoder;
	td->aper_decoder   = asn_DEF_NativeEnumerated.aper_decoder;
	td->aper_encoder   = asn_DEF_NativeEnumerated.aper_encoder;
	if(!td->per_constraints)
		td->per_constraints = asn_DEF_NativeEnumerated.per_constraints;
	td->elements       = asn_DEF_NativeEnumerated.elements;
	td->elements_count = asn_DEF_NativeEnumerated.elements_count;
     /* td->specifics      = asn_DEF_NativeEnumerated.specifics;	// Defined explicitly */
}

static void
transmissionType_r11_3_free(asn_TYPE_descriptor_t *td,
		void *struct_ptr, int contents_only) {
	transmissionType_r11_3_inherit_TYPE_descriptor(td);
	td->free_struct(td, struct_ptr, contents_only);
}

static int
transmissionType_r11_3_print(asn_TYPE_descriptor_t *td, const void *struct_ptr,
		int ilevel, asn_app_consume_bytes_f *cb, void *app_key) {
	transmissionType_r11_3_inherit_TYPE_descriptor(td);
	return td->print_struct(td, struct_ptr, ilevel, cb, app_key);
}

static asn_dec_rval_t
transmissionType_r11_3_decode_ber(asn_codec_ctx_t *opt_codec_ctx, asn_TYPE_descriptor_t *td,
		void **structure, const void *bufptr, size_t size, int tag_mode) {
	transmissionType_r11_3_inherit_TYPE_descriptor(td);
	return td->ber_decoder(opt_codec_ctx, td, structure, bufptr, size, tag_mode);
}

static asn_enc_rval_t
transmissionType_r11_3_encode_der(asn_TYPE_descriptor_t *td,
		void *structure, int tag_mode, ber_tlv_tag_t tag,
		asn_app_consume_bytes_f *cb, void *app_key) {
	transmissionType_r11_3_inherit_TYPE_descriptor(td);
	return td->der_encoder(td, structure, tag_mode, tag, cb, app_key);
}

static asn_dec_rval_t
transmissionType_r11_3_decode_xer(asn_codec_ctx_t *opt_codec_ctx, asn_TYPE_descriptor_t *td,
		void **structure, const char *opt_mname, const void *bufptr, size_t size) {
	transmissionType_r11_3_inherit_TYPE_descriptor(td);
	return td->xer_decoder(opt_codec_ctx, td, structure, opt_mname, bufptr, size);
}

static asn_enc_rval_t
transmissionType_r11_3_encode_xer(asn_TYPE_descriptor_t *td, void *structure,
		int ilevel, enum xer_encoder_flags_e flags,
		asn_app_consume_bytes_f *cb, void *app_key) {
	transmissionType_r11_3_inherit_TYPE_descriptor(td);
	return td->xer_encoder(td, structure, ilevel, flags, cb, app_key);
}

static asn_dec_rval_t
transmissionType_r11_3_decode_uper(asn_codec_ctx_t *opt_codec_ctx, asn_TYPE_descriptor_t *td,
		asn_per_constraints_t *constraints, void **structure, asn_per_data_t *per_data) {
	transmissionType_r11_3_inherit_TYPE_descriptor(td);
	return td->uper_decoder(opt_codec_ctx, td, constraints, structure, per_data);
}

static asn_enc_rval_t
transmissionType_r11_3_encode_uper(asn_TYPE_descriptor_t *td,
		asn_per_constraints_t *constraints,
		void *structure, asn_per_outp_t *per_out) {
	transmissionType_r11_3_inherit_TYPE_descriptor(td);
	return td->uper_encoder(td, constraints, structure, per_out);
}

static asn_dec_rval_t
transmissionType_r11_3_decode_aper(asn_codec_ctx_t *opt_codec_ctx, asn_TYPE_descriptor_t *td,
		asn_per_constraints_t *constraints, void **structure, asn_per_data_t *per_data) {
	transmissionType_r11_3_inherit_TYPE_descriptor(td);
	return td->aper_decoder(opt_codec_ctx, td, constraints, structure, per_data);
}

static asn_enc_rval_t
transmissionType_r11_3_encode_aper(asn_TYPE_descriptor_t *td,
		asn_per_constraints_t *constraints,
		void *structure, asn_per_outp_t *per_out) {
	transmissionType_r11_3_inherit_TYPE_descriptor(td);
	return td->aper_encoder(td, constraints, structure, per_out);
}

static int
numberPRB_Pairs_r11_7_constraint(asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	/* Replace with underlying type checker */
	td->check_constraints = asn_DEF_NativeEnumerated.check_constraints;
	return td->check_constraints(td, sptr, ctfailcb, app_key);
}

/*
 * This type is implemented using NativeEnumerated,
 * so here we adjust the DEF accordingly.
 */
static void
numberPRB_Pairs_r11_7_inherit_TYPE_descriptor(asn_TYPE_descriptor_t *td) {
	td->free_struct    = asn_DEF_NativeEnumerated.free_struct;
	td->print_struct   = asn_DEF_NativeEnumerated.print_struct;
	td->check_constraints = asn_DEF_NativeEnumerated.check_constraints;
	td->ber_decoder    = asn_DEF_NativeEnumerated.ber_decoder;
	td->der_encoder    = asn_DEF_NativeEnumerated.der_encoder;
	td->xer_decoder    = asn_DEF_NativeEnumerated.xer_decoder;
	td->xer_encoder    = asn_DEF_NativeEnumerated.xer_encoder;
	td->uper_decoder   = asn_DEF_NativeEnumerated.uper_decoder;
	td->uper_encoder   = asn_DEF_NativeEnumerated.uper_encoder;
	td->aper_decoder   = asn_DEF_NativeEnumerated.aper_decoder;
	td->aper_encoder   = asn_DEF_NativeEnumerated.aper_encoder;
	if(!td->per_constraints)
		td->per_constraints = asn_DEF_NativeEnumerated.per_constraints;
	td->elements       = asn_DEF_NativeEnumerated.elements;
	td->elements_count = asn_DEF_NativeEnumerated.elements_count;
     /* td->specifics      = asn_DEF_NativeEnumerated.specifics;	// Defined explicitly */
}

static void
numberPRB_Pairs_r11_7_free(asn_TYPE_descriptor_t *td,
		void *struct_ptr, int contents_only) {
	numberPRB_Pairs_r11_7_inherit_TYPE_descriptor(td);
	td->free_struct(td, struct_ptr, contents_only);
}

static int
numberPRB_Pairs_r11_7_print(asn_TYPE_descriptor_t *td, const void *struct_ptr,
		int ilevel, asn_app_consume_bytes_f *cb, void *app_key) {
	numberPRB_Pairs_r11_7_inherit_TYPE_descriptor(td);
	return td->print_struct(td, struct_ptr, ilevel, cb, app_key);
}

static asn_dec_rval_t
numberPRB_Pairs_r11_7_decode_ber(asn_codec_ctx_t *opt_codec_ctx, asn_TYPE_descriptor_t *td,
		void **structure, const void *bufptr, size_t size, int tag_mode) {
	numberPRB_Pairs_r11_7_inherit_TYPE_descriptor(td);
	return td->ber_decoder(opt_codec_ctx, td, structure, bufptr, size, tag_mode);
}

static asn_enc_rval_t
numberPRB_Pairs_r11_7_encode_der(asn_TYPE_descriptor_t *td,
		void *structure, int tag_mode, ber_tlv_tag_t tag,
		asn_app_consume_bytes_f *cb, void *app_key) {
	numberPRB_Pairs_r11_7_inherit_TYPE_descriptor(td);
	return td->der_encoder(td, structure, tag_mode, tag, cb, app_key);
}

static asn_dec_rval_t
numberPRB_Pairs_r11_7_decode_xer(asn_codec_ctx_t *opt_codec_ctx, asn_TYPE_descriptor_t *td,
		void **structure, const char *opt_mname, const void *bufptr, size_t size) {
	numberPRB_Pairs_r11_7_inherit_TYPE_descriptor(td);
	return td->xer_decoder(opt_codec_ctx, td, structure, opt_mname, bufptr, size);
}

static asn_enc_rval_t
numberPRB_Pairs_r11_7_encode_xer(asn_TYPE_descriptor_t *td, void *structure,
		int ilevel, enum xer_encoder_flags_e flags,
		asn_app_consume_bytes_f *cb, void *app_key) {
	numberPRB_Pairs_r11_7_inherit_TYPE_descriptor(td);
	return td->xer_encoder(td, structure, ilevel, flags, cb, app_key);
}

static asn_dec_rval_t
numberPRB_Pairs_r11_7_decode_uper(asn_codec_ctx_t *opt_codec_ctx, asn_TYPE_descriptor_t *td,
		asn_per_constraints_t *constraints, void **structure, asn_per_data_t *per_data) {
	numberPRB_Pairs_r11_7_inherit_TYPE_descriptor(td);
	return td->uper_decoder(opt_codec_ctx, td, constraints, structure, per_data);
}

static asn_enc_rval_t
numberPRB_Pairs_r11_7_encode_uper(asn_TYPE_descriptor_t *td,
		asn_per_constraints_t *constraints,
		void *structure, asn_per_outp_t *per_out) {
	numberPRB_Pairs_r11_7_inherit_TYPE_descriptor(td);
	return td->uper_encoder(td, constraints, structure, per_out);
}

static asn_dec_rval_t
numberPRB_Pairs_r11_7_decode_aper(asn_codec_ctx_t *opt_codec_ctx, asn_TYPE_descriptor_t *td,
		asn_per_constraints_t *constraints, void **structure, asn_per_data_t *per_data) {
	numberPRB_Pairs_r11_7_inherit_TYPE_descriptor(td);
	return td->aper_decoder(opt_codec_ctx, td, constraints, structure, per_data);
}

static asn_enc_rval_t
numberPRB_Pairs_r11_7_encode_aper(asn_TYPE_descriptor_t *td,
		asn_per_constraints_t *constraints,
		void *structure, asn_per_outp_t *per_out) {
	numberPRB_Pairs_r11_7_inherit_TYPE_descriptor(td);
	return td->aper_encoder(td, constraints, structure, per_out);
}

static int
memb_resourceBlockAssignment_r11_constraint_6(asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	const BIT_STRING_t *st = (const BIT_STRING_t *)sptr;
	size_t size;
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	if(st->size > 0) {
		/* Size in bits */
		size = 8 * st->size - (st->bits_unused & 0x07);
	} else {
		size = 0;
	}
	
	if((size >= 4LL && size <= 38LL)) {
		/* Constraint check succeeded */
		return 0;
	} else {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

static int
setup_21_constraint(asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	/* Replace with underlying type checker */
	td->check_constraints = asn_DEF_NativeEnumerated.check_constraints;
	return td->check_constraints(td, sptr, ctfailcb, app_key);
}

/*
 * This type is implemented using NativeEnumerated,
 * so here we adjust the DEF accordingly.
 */
static void
setup_21_inherit_TYPE_descriptor(asn_TYPE_descriptor_t *td) {
	td->free_struct    = asn_DEF_NativeEnumerated.free_struct;
	td->print_struct   = asn_DEF_NativeEnumerated.print_struct;
	td->check_constraints = asn_DEF_NativeEnumerated.check_constraints;
	td->ber_decoder    = asn_DEF_NativeEnumerated.ber_decoder;
	td->der_encoder    = asn_DEF_NativeEnumerated.der_encoder;
	td->xer_decoder    = asn_DEF_NativeEnumerated.xer_decoder;
	td->xer_encoder    = asn_DEF_NativeEnumerated.xer_encoder;
	td->uper_decoder   = asn_DEF_NativeEnumerated.uper_decoder;
	td->uper_encoder   = asn_DEF_NativeEnumerated.uper_encoder;
	td->aper_decoder   = asn_DEF_NativeEnumerated.aper_decoder;
	td->aper_encoder   = asn_DEF_NativeEnumerated.aper_encoder;
	if(!td->per_constraints)
		td->per_constraints = asn_DEF_NativeEnumerated.per_constraints;
	td->elements       = asn_DEF_NativeEnumerated.elements;
	td->elements_count = asn_DEF_NativeEnumerated.elements_count;
     /* td->specifics      = asn_DEF_NativeEnumerated.specifics;	// Defined explicitly */
}

static void
setup_21_free(asn_TYPE_descriptor_t *td,
		void *struct_ptr, int contents_only) {
	setup_21_inherit_TYPE_descriptor(td);
	td->free_struct(td, struct_ptr, contents_only);
}

static int
setup_21_print(asn_TYPE_descriptor_t *td, const void *struct_ptr,
		int ilevel, asn_app_consume_bytes_f *cb, void *app_key) {
	setup_21_inherit_TYPE_descriptor(td);
	return td->print_struct(td, struct_ptr, ilevel, cb, app_key);
}

static asn_dec_rval_t
setup_21_decode_ber(asn_codec_ctx_t *opt_codec_ctx, asn_TYPE_descriptor_t *td,
		void **structure, const void *bufptr, size_t size, int tag_mode) {
	setup_21_inherit_TYPE_descriptor(td);
	return td->ber_decoder(opt_codec_ctx, td, structure, bufptr, size, tag_mode);
}

static asn_enc_rval_t
setup_21_encode_der(asn_TYPE_descriptor_t *td,
		void *structure, int tag_mode, ber_tlv_tag_t tag,
		asn_app_consume_bytes_f *cb, void *app_key) {
	setup_21_inherit_TYPE_descriptor(td);
	return td->der_encoder(td, structure, tag_mode, tag, cb, app_key);
}

static asn_dec_rval_t
setup_21_decode_xer(asn_codec_ctx_t *opt_codec_ctx, asn_TYPE_descriptor_t *td,
		void **structure, const char *opt_mname, const void *bufptr, size_t size) {
	setup_21_inherit_TYPE_descriptor(td);
	return td->xer_decoder(opt_codec_ctx, td, structure, opt_mname, bufptr, size);
}

static asn_enc_rval_t
setup_21_encode_xer(asn_TYPE_descriptor_t *td, void *structure,
		int ilevel, enum xer_encoder_flags_e flags,
		asn_app_consume_bytes_f *cb, void *app_key) {
	setup_21_inherit_TYPE_descriptor(td);
	return td->xer_encoder(td, structure, ilevel, flags, cb, app_key);
}

static asn_dec_rval_t
setup_21_decode_uper(asn_codec_ctx_t *opt_codec_ctx, asn_TYPE_descriptor_t *td,
		asn_per_constraints_t *constraints, void **structure, asn_per_data_t *per_data) {
	setup_21_inherit_TYPE_descriptor(td);
	return td->uper_decoder(opt_codec_ctx, td, constraints, structure, per_data);
}

static asn_enc_rval_t
setup_21_encode_uper(asn_TYPE_descriptor_t *td,
		asn_per_constraints_t *constraints,
		void *structure, asn_per_outp_t *per_out) {
	setup_21_inherit_TYPE_descriptor(td);
	return td->uper_encoder(td, constraints, structure, per_out);
}

static asn_dec_rval_t
setup_21_decode_aper(asn_codec_ctx_t *opt_codec_ctx, asn_TYPE_descriptor_t *td,
		asn_per_constraints_t *constraints, void **structure, asn_per_data_t *per_data) {
	setup_21_inherit_TYPE_descriptor(td);
	return td->aper_decoder(opt_codec_ctx, td, constraints, structure, per_data);
}

static asn_enc_rval_t
setup_21_encode_aper(asn_TYPE_descriptor_t *td,
		asn_per_constraints_t *constraints,
		void *structure, asn_per_outp_t *per_out) {
	setup_21_inherit_TYPE_descriptor(td);
	return td->aper_encoder(td, constraints, structure, per_out);
}

static int
csi_NumRepetitionCE_r13_26_constraint(asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	/* Replace with underlying type checker */
	td->check_constraints = asn_DEF_NativeEnumerated.check_constraints;
	return td->check_constraints(td, sptr, ctfailcb, app_key);
}

/*
 * This type is implemented using NativeEnumerated,
 * so here we adjust the DEF accordingly.
 */
static void
csi_NumRepetitionCE_r13_26_inherit_TYPE_descriptor(asn_TYPE_descriptor_t *td) {
	td->free_struct    = asn_DEF_NativeEnumerated.free_struct;
	td->print_struct   = asn_DEF_NativeEnumerated.print_struct;
	td->check_constraints = asn_DEF_NativeEnumerated.check_constraints;
	td->ber_decoder    = asn_DEF_NativeEnumerated.ber_decoder;
	td->der_encoder    = asn_DEF_NativeEnumerated.der_encoder;
	td->xer_decoder    = asn_DEF_NativeEnumerated.xer_decoder;
	td->xer_encoder    = asn_DEF_NativeEnumerated.xer_encoder;
	td->uper_decoder   = asn_DEF_NativeEnumerated.uper_decoder;
	td->uper_encoder   = asn_DEF_NativeEnumerated.uper_encoder;
	td->aper_decoder   = asn_DEF_NativeEnumerated.aper_decoder;
	td->aper_encoder   = asn_DEF_NativeEnumerated.aper_encoder;
	if(!td->per_constraints)
		td->per_constraints = asn_DEF_NativeEnumerated.per_constraints;
	td->elements       = asn_DEF_NativeEnumerated.elements;
	td->elements_count = asn_DEF_NativeEnumerated.elements_count;
     /* td->specifics      = asn_DEF_NativeEnumerated.specifics;	// Defined explicitly */
}

static void
csi_NumRepetitionCE_r13_26_free(asn_TYPE_descriptor_t *td,
		void *struct_ptr, int contents_only) {
	csi_NumRepetitionCE_r13_26_inherit_TYPE_descriptor(td);
	td->free_struct(td, struct_ptr, contents_only);
}

static int
csi_NumRepetitionCE_r13_26_print(asn_TYPE_descriptor_t *td, const void *struct_ptr,
		int ilevel, asn_app_consume_bytes_f *cb, void *app_key) {
	csi_NumRepetitionCE_r13_26_inherit_TYPE_descriptor(td);
	return td->print_struct(td, struct_ptr, ilevel, cb, app_key);
}

static asn_dec_rval_t
csi_NumRepetitionCE_r13_26_decode_ber(asn_codec_ctx_t *opt_codec_ctx, asn_TYPE_descriptor_t *td,
		void **structure, const void *bufptr, size_t size, int tag_mode) {
	csi_NumRepetitionCE_r13_26_inherit_TYPE_descriptor(td);
	return td->ber_decoder(opt_codec_ctx, td, structure, bufptr, size, tag_mode);
}

static asn_enc_rval_t
csi_NumRepetitionCE_r13_26_encode_der(asn_TYPE_descriptor_t *td,
		void *structure, int tag_mode, ber_tlv_tag_t tag,
		asn_app_consume_bytes_f *cb, void *app_key) {
	csi_NumRepetitionCE_r13_26_inherit_TYPE_descriptor(td);
	return td->der_encoder(td, structure, tag_mode, tag, cb, app_key);
}

static asn_dec_rval_t
csi_NumRepetitionCE_r13_26_decode_xer(asn_codec_ctx_t *opt_codec_ctx, asn_TYPE_descriptor_t *td,
		void **structure, const char *opt_mname, const void *bufptr, size_t size) {
	csi_NumRepetitionCE_r13_26_inherit_TYPE_descriptor(td);
	return td->xer_decoder(opt_codec_ctx, td, structure, opt_mname, bufptr, size);
}

static asn_enc_rval_t
csi_NumRepetitionCE_r13_26_encode_xer(asn_TYPE_descriptor_t *td, void *structure,
		int ilevel, enum xer_encoder_flags_e flags,
		asn_app_consume_bytes_f *cb, void *app_key) {
	csi_NumRepetitionCE_r13_26_inherit_TYPE_descriptor(td);
	return td->xer_encoder(td, structure, ilevel, flags, cb, app_key);
}

static asn_dec_rval_t
csi_NumRepetitionCE_r13_26_decode_uper(asn_codec_ctx_t *opt_codec_ctx, asn_TYPE_descriptor_t *td,
		asn_per_constraints_t *constraints, void **structure, asn_per_data_t *per_data) {
	csi_NumRepetitionCE_r13_26_inherit_TYPE_descriptor(td);
	return td->uper_decoder(opt_codec_ctx, td, constraints, structure, per_data);
}

static asn_enc_rval_t
csi_NumRepetitionCE_r13_26_encode_uper(asn_TYPE_descriptor_t *td,
		asn_per_constraints_t *constraints,
		void *structure, asn_per_outp_t *per_out) {
	csi_NumRepetitionCE_r13_26_inherit_TYPE_descriptor(td);
	return td->uper_encoder(td, constraints, structure, per_out);
}

static asn_dec_rval_t
csi_NumRepetitionCE_r13_26_decode_aper(asn_codec_ctx_t *opt_codec_ctx, asn_TYPE_descriptor_t *td,
		asn_per_constraints_t *constraints, void **structure, asn_per_data_t *per_data) {
	csi_NumRepetitionCE_r13_26_inherit_TYPE_descriptor(td);
	return td->aper_decoder(opt_codec_ctx, td, constraints, structure, per_data);
}

static asn_enc_rval_t
csi_NumRepetitionCE_r13_26_encode_aper(asn_TYPE_descriptor_t *td,
		asn_per_constraints_t *constraints,
		void *structure, asn_per_outp_t *per_out) {
	csi_NumRepetitionCE_r13_26_inherit_TYPE_descriptor(td);
	return td->aper_encoder(td, constraints, structure, per_out);
}

static int
mpdcch_pdsch_HoppingConfig_r13_33_constraint(asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	/* Replace with underlying type checker */
	td->check_constraints = asn_DEF_NativeEnumerated.check_constraints;
	return td->check_constraints(td, sptr, ctfailcb, app_key);
}

/*
 * This type is implemented using NativeEnumerated,
 * so here we adjust the DEF accordingly.
 */
static void
mpdcch_pdsch_HoppingConfig_r13_33_inherit_TYPE_descriptor(asn_TYPE_descriptor_t *td) {
	td->free_struct    = asn_DEF_NativeEnumerated.free_struct;
	td->print_struct   = asn_DEF_NativeEnumerated.print_struct;
	td->check_constraints = asn_DEF_NativeEnumerated.check_constraints;
	td->ber_decoder    = asn_DEF_NativeEnumerated.ber_decoder;
	td->der_encoder    = asn_DEF_NativeEnumerated.der_encoder;
	td->xer_decoder    = asn_DEF_NativeEnumerated.xer_decoder;
	td->xer_encoder    = asn_DEF_NativeEnumerated.xer_encoder;
	td->uper_decoder   = asn_DEF_NativeEnumerated.uper_decoder;
	td->uper_encoder   = asn_DEF_NativeEnumerated.uper_encoder;
	td->aper_decoder   = asn_DEF_NativeEnumerated.aper_decoder;
	td->aper_encoder   = asn_DEF_NativeEnumerated.aper_encoder;
	if(!td->per_constraints)
		td->per_constraints = asn_DEF_NativeEnumerated.per_constraints;
	td->elements       = asn_DEF_NativeEnumerated.elements;
	td->elements_count = asn_DEF_NativeEnumerated.elements_count;
     /* td->specifics      = asn_DEF_NativeEnumerated.specifics;	// Defined explicitly */
}

static void
mpdcch_pdsch_HoppingConfig_r13_33_free(asn_TYPE_descriptor_t *td,
		void *struct_ptr, int contents_only) {
	mpdcch_pdsch_HoppingConfig_r13_33_inherit_TYPE_descriptor(td);
	td->free_struct(td, struct_ptr, contents_only);
}

static int
mpdcch_pdsch_HoppingConfig_r13_33_print(asn_TYPE_descriptor_t *td, const void *struct_ptr,
		int ilevel, asn_app_consume_bytes_f *cb, void *app_key) {
	mpdcch_pdsch_HoppingConfig_r13_33_inherit_TYPE_descriptor(td);
	return td->print_struct(td, struct_ptr, ilevel, cb, app_key);
}

static asn_dec_rval_t
mpdcch_pdsch_HoppingConfig_r13_33_decode_ber(asn_codec_ctx_t *opt_codec_ctx, asn_TYPE_descriptor_t *td,
		void **structure, const void *bufptr, size_t size, int tag_mode) {
	mpdcch_pdsch_HoppingConfig_r13_33_inherit_TYPE_descriptor(td);
	return td->ber_decoder(opt_codec_ctx, td, structure, bufptr, size, tag_mode);
}

static asn_enc_rval_t
mpdcch_pdsch_HoppingConfig_r13_33_encode_der(asn_TYPE_descriptor_t *td,
		void *structure, int tag_mode, ber_tlv_tag_t tag,
		asn_app_consume_bytes_f *cb, void *app_key) {
	mpdcch_pdsch_HoppingConfig_r13_33_inherit_TYPE_descriptor(td);
	return td->der_encoder(td, structure, tag_mode, tag, cb, app_key);
}

static asn_dec_rval_t
mpdcch_pdsch_HoppingConfig_r13_33_decode_xer(asn_codec_ctx_t *opt_codec_ctx, asn_TYPE_descriptor_t *td,
		void **structure, const char *opt_mname, const void *bufptr, size_t size) {
	mpdcch_pdsch_HoppingConfig_r13_33_inherit_TYPE_descriptor(td);
	return td->xer_decoder(opt_codec_ctx, td, structure, opt_mname, bufptr, size);
}

static asn_enc_rval_t
mpdcch_pdsch_HoppingConfig_r13_33_encode_xer(asn_TYPE_descriptor_t *td, void *structure,
		int ilevel, enum xer_encoder_flags_e flags,
		asn_app_consume_bytes_f *cb, void *app_key) {
	mpdcch_pdsch_HoppingConfig_r13_33_inherit_TYPE_descriptor(td);
	return td->xer_encoder(td, structure, ilevel, flags, cb, app_key);
}

static asn_dec_rval_t
mpdcch_pdsch_HoppingConfig_r13_33_decode_uper(asn_codec_ctx_t *opt_codec_ctx, asn_TYPE_descriptor_t *td,
		asn_per_constraints_t *constraints, void **structure, asn_per_data_t *per_data) {
	mpdcch_pdsch_HoppingConfig_r13_33_inherit_TYPE_descriptor(td);
	return td->uper_decoder(opt_codec_ctx, td, constraints, structure, per_data);
}

static asn_enc_rval_t
mpdcch_pdsch_HoppingConfig_r13_33_encode_uper(asn_TYPE_descriptor_t *td,
		asn_per_constraints_t *constraints,
		void *structure, asn_per_outp_t *per_out) {
	mpdcch_pdsch_HoppingConfig_r13_33_inherit_TYPE_descriptor(td);
	return td->uper_encoder(td, constraints, structure, per_out);
}

static asn_dec_rval_t
mpdcch_pdsch_HoppingConfig_r13_33_decode_aper(asn_codec_ctx_t *opt_codec_ctx, asn_TYPE_descriptor_t *td,
		asn_per_constraints_t *constraints, void **structure, asn_per_data_t *per_data) {
	mpdcch_pdsch_HoppingConfig_r13_33_inherit_TYPE_descriptor(td);
	return td->aper_decoder(opt_codec_ctx, td, constraints, structure, per_data);
}

static asn_enc_rval_t
mpdcch_pdsch_HoppingConfig_r13_33_encode_aper(asn_TYPE_descriptor_t *td,
		asn_per_constraints_t *constraints,
		void *structure, asn_per_outp_t *per_out) {
	mpdcch_pdsch_HoppingConfig_r13_33_inherit_TYPE_descriptor(td);
	return td->aper_encoder(td, constraints, structure, per_out);
}

static int
fdd_r13_37_constraint(asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	/* Replace with underlying type checker */
	td->check_constraints = asn_DEF_NativeEnumerated.check_constraints;
	return td->check_constraints(td, sptr, ctfailcb, app_key);
}

/*
 * This type is implemented using NativeEnumerated,
 * so here we adjust the DEF accordingly.
 */
static void
fdd_r13_37_inherit_TYPE_descriptor(asn_TYPE_descriptor_t *td) {
	td->free_struct    = asn_DEF_NativeEnumerated.free_struct;
	td->print_struct   = asn_DEF_NativeEnumerated.print_struct;
	td->check_constraints = asn_DEF_NativeEnumerated.check_constraints;
	td->ber_decoder    = asn_DEF_NativeEnumerated.ber_decoder;
	td->der_encoder    = asn_DEF_NativeEnumerated.der_encoder;
	td->xer_decoder    = asn_DEF_NativeEnumerated.xer_decoder;
	td->xer_encoder    = asn_DEF_NativeEnumerated.xer_encoder;
	td->uper_decoder   = asn_DEF_NativeEnumerated.uper_decoder;
	td->uper_encoder   = asn_DEF_NativeEnumerated.uper_encoder;
	td->aper_decoder   = asn_DEF_NativeEnumerated.aper_decoder;
	td->aper_encoder   = asn_DEF_NativeEnumerated.aper_encoder;
	if(!td->per_constraints)
		td->per_constraints = asn_DEF_NativeEnumerated.per_constraints;
	td->elements       = asn_DEF_NativeEnumerated.elements;
	td->elements_count = asn_DEF_NativeEnumerated.elements_count;
     /* td->specifics      = asn_DEF_NativeEnumerated.specifics;	// Defined explicitly */
}

static void
fdd_r13_37_free(asn_TYPE_descriptor_t *td,
		void *struct_ptr, int contents_only) {
	fdd_r13_37_inherit_TYPE_descriptor(td);
	td->free_struct(td, struct_ptr, contents_only);
}

static int
fdd_r13_37_print(asn_TYPE_descriptor_t *td, const void *struct_ptr,
		int ilevel, asn_app_consume_bytes_f *cb, void *app_key) {
	fdd_r13_37_inherit_TYPE_descriptor(td);
	return td->print_struct(td, struct_ptr, ilevel, cb, app_key);
}

static asn_dec_rval_t
fdd_r13_37_decode_ber(asn_codec_ctx_t *opt_codec_ctx, asn_TYPE_descriptor_t *td,
		void **structure, const void *bufptr, size_t size, int tag_mode) {
	fdd_r13_37_inherit_TYPE_descriptor(td);
	return td->ber_decoder(opt_codec_ctx, td, structure, bufptr, size, tag_mode);
}

static asn_enc_rval_t
fdd_r13_37_encode_der(asn_TYPE_descriptor_t *td,
		void *structure, int tag_mode, ber_tlv_tag_t tag,
		asn_app_consume_bytes_f *cb, void *app_key) {
	fdd_r13_37_inherit_TYPE_descriptor(td);
	return td->der_encoder(td, structure, tag_mode, tag, cb, app_key);
}

static asn_dec_rval_t
fdd_r13_37_decode_xer(asn_codec_ctx_t *opt_codec_ctx, asn_TYPE_descriptor_t *td,
		void **structure, const char *opt_mname, const void *bufptr, size_t size) {
	fdd_r13_37_inherit_TYPE_descriptor(td);
	return td->xer_decoder(opt_codec_ctx, td, structure, opt_mname, bufptr, size);
}

static asn_enc_rval_t
fdd_r13_37_encode_xer(asn_TYPE_descriptor_t *td, void *structure,
		int ilevel, enum xer_encoder_flags_e flags,
		asn_app_consume_bytes_f *cb, void *app_key) {
	fdd_r13_37_inherit_TYPE_descriptor(td);
	return td->xer_encoder(td, structure, ilevel, flags, cb, app_key);
}

static asn_dec_rval_t
fdd_r13_37_decode_uper(asn_codec_ctx_t *opt_codec_ctx, asn_TYPE_descriptor_t *td,
		asn_per_constraints_t *constraints, void **structure, asn_per_data_t *per_data) {
	fdd_r13_37_inherit_TYPE_descriptor(td);
	return td->uper_decoder(opt_codec_ctx, td, constraints, structure, per_data);
}

static asn_enc_rval_t
fdd_r13_37_encode_uper(asn_TYPE_descriptor_t *td,
		asn_per_constraints_t *constraints,
		void *structure, asn_per_outp_t *per_out) {
	fdd_r13_37_inherit_TYPE_descriptor(td);
	return td->uper_encoder(td, constraints, structure, per_out);
}

static asn_dec_rval_t
fdd_r13_37_decode_aper(asn_codec_ctx_t *opt_codec_ctx, asn_TYPE_descriptor_t *td,
		asn_per_constraints_t *constraints, void **structure, asn_per_data_t *per_data) {
	fdd_r13_37_inherit_TYPE_descriptor(td);
	return td->aper_decoder(opt_codec_ctx, td, constraints, structure, per_data);
}

static asn_enc_rval_t
fdd_r13_37_encode_aper(asn_TYPE_descriptor_t *td,
		asn_per_constraints_t *constraints,
		void *structure, asn_per_outp_t *per_out) {
	fdd_r13_37_inherit_TYPE_descriptor(td);
	return td->aper_encoder(td, constraints, structure, per_out);
}

static int
tdd_r13_46_constraint(asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	/* Replace with underlying type checker */
	td->check_constraints = asn_DEF_NativeEnumerated.check_constraints;
	return td->check_constraints(td, sptr, ctfailcb, app_key);
}

/*
 * This type is implemented using NativeEnumerated,
 * so here we adjust the DEF accordingly.
 */
static void
tdd_r13_46_inherit_TYPE_descriptor(asn_TYPE_descriptor_t *td) {
	td->free_struct    = asn_DEF_NativeEnumerated.free_struct;
	td->print_struct   = asn_DEF_NativeEnumerated.print_struct;
	td->check_constraints = asn_DEF_NativeEnumerated.check_constraints;
	td->ber_decoder    = asn_DEF_NativeEnumerated.ber_decoder;
	td->der_encoder    = asn_DEF_NativeEnumerated.der_encoder;
	td->xer_decoder    = asn_DEF_NativeEnumerated.xer_decoder;
	td->xer_encoder    = asn_DEF_NativeEnumerated.xer_encoder;
	td->uper_decoder   = asn_DEF_NativeEnumerated.uper_decoder;
	td->uper_encoder   = asn_DEF_NativeEnumerated.uper_encoder;
	td->aper_decoder   = asn_DEF_NativeEnumerated.aper_decoder;
	td->aper_encoder   = asn_DEF_NativeEnumerated.aper_encoder;
	if(!td->per_constraints)
		td->per_constraints = asn_DEF_NativeEnumerated.per_constraints;
	td->elements       = asn_DEF_NativeEnumerated.elements;
	td->elements_count = asn_DEF_NativeEnumerated.elements_count;
     /* td->specifics      = asn_DEF_NativeEnumerated.specifics;	// Defined explicitly */
}

static void
tdd_r13_46_free(asn_TYPE_descriptor_t *td,
		void *struct_ptr, int contents_only) {
	tdd_r13_46_inherit_TYPE_descriptor(td);
	td->free_struct(td, struct_ptr, contents_only);
}

static int
tdd_r13_46_print(asn_TYPE_descriptor_t *td, const void *struct_ptr,
		int ilevel, asn_app_consume_bytes_f *cb, void *app_key) {
	tdd_r13_46_inherit_TYPE_descriptor(td);
	return td->print_struct(td, struct_ptr, ilevel, cb, app_key);
}

static asn_dec_rval_t
tdd_r13_46_decode_ber(asn_codec_ctx_t *opt_codec_ctx, asn_TYPE_descriptor_t *td,
		void **structure, const void *bufptr, size_t size, int tag_mode) {
	tdd_r13_46_inherit_TYPE_descriptor(td);
	return td->ber_decoder(opt_codec_ctx, td, structure, bufptr, size, tag_mode);
}

static asn_enc_rval_t
tdd_r13_46_encode_der(asn_TYPE_descriptor_t *td,
		void *structure, int tag_mode, ber_tlv_tag_t tag,
		asn_app_consume_bytes_f *cb, void *app_key) {
	tdd_r13_46_inherit_TYPE_descriptor(td);
	return td->der_encoder(td, structure, tag_mode, tag, cb, app_key);
}

static asn_dec_rval_t
tdd_r13_46_decode_xer(asn_codec_ctx_t *opt_codec_ctx, asn_TYPE_descriptor_t *td,
		void **structure, const char *opt_mname, const void *bufptr, size_t size) {
	tdd_r13_46_inherit_TYPE_descriptor(td);
	return td->xer_decoder(opt_codec_ctx, td, structure, opt_mname, bufptr, size);
}

static asn_enc_rval_t
tdd_r13_46_encode_xer(asn_TYPE_descriptor_t *td, void *structure,
		int ilevel, enum xer_encoder_flags_e flags,
		asn_app_consume_bytes_f *cb, void *app_key) {
	tdd_r13_46_inherit_TYPE_descriptor(td);
	return td->xer_encoder(td, structure, ilevel, flags, cb, app_key);
}

static asn_dec_rval_t
tdd_r13_46_decode_uper(asn_codec_ctx_t *opt_codec_ctx, asn_TYPE_descriptor_t *td,
		asn_per_constraints_t *constraints, void **structure, asn_per_data_t *per_data) {
	tdd_r13_46_inherit_TYPE_descriptor(td);
	return td->uper_decoder(opt_codec_ctx, td, constraints, structure, per_data);
}

static asn_enc_rval_t
tdd_r13_46_encode_uper(asn_TYPE_descriptor_t *td,
		asn_per_constraints_t *constraints,
		void *structure, asn_per_outp_t *per_out) {
	tdd_r13_46_inherit_TYPE_descriptor(td);
	return td->uper_encoder(td, constraints, structure, per_out);
}

static asn_dec_rval_t
tdd_r13_46_decode_aper(asn_codec_ctx_t *opt_codec_ctx, asn_TYPE_descriptor_t *td,
		asn_per_constraints_t *constraints, void **structure, asn_per_data_t *per_data) {
	tdd_r13_46_inherit_TYPE_descriptor(td);
	return td->aper_decoder(opt_codec_ctx, td, constraints, structure, per_data);
}

static asn_enc_rval_t
tdd_r13_46_encode_aper(asn_TYPE_descriptor_t *td,
		asn_per_constraints_t *constraints,
		void *structure, asn_per_outp_t *per_out) {
	tdd_r13_46_inherit_TYPE_descriptor(td);
	return td->aper_encoder(td, constraints, structure, per_out);
}

static int
mpdcch_NumRepetition_r13_55_constraint(asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	/* Replace with underlying type checker */
	td->check_constraints = asn_DEF_NativeEnumerated.check_constraints;
	return td->check_constraints(td, sptr, ctfailcb, app_key);
}

/*
 * This type is implemented using NativeEnumerated,
 * so here we adjust the DEF accordingly.
 */
static void
mpdcch_NumRepetition_r13_55_inherit_TYPE_descriptor(asn_TYPE_descriptor_t *td) {
	td->free_struct    = asn_DEF_NativeEnumerated.free_struct;
	td->print_struct   = asn_DEF_NativeEnumerated.print_struct;
	td->check_constraints = asn_DEF_NativeEnumerated.check_constraints;
	td->ber_decoder    = asn_DEF_NativeEnumerated.ber_decoder;
	td->der_encoder    = asn_DEF_NativeEnumerated.der_encoder;
	td->xer_decoder    = asn_DEF_NativeEnumerated.xer_decoder;
	td->xer_encoder    = asn_DEF_NativeEnumerated.xer_encoder;
	td->uper_decoder   = asn_DEF_NativeEnumerated.uper_decoder;
	td->uper_encoder   = asn_DEF_NativeEnumerated.uper_encoder;
	td->aper_decoder   = asn_DEF_NativeEnumerated.aper_decoder;
	td->aper_encoder   = asn_DEF_NativeEnumerated.aper_encoder;
	if(!td->per_constraints)
		td->per_constraints = asn_DEF_NativeEnumerated.per_constraints;
	td->elements       = asn_DEF_NativeEnumerated.elements;
	td->elements_count = asn_DEF_NativeEnumerated.elements_count;
     /* td->specifics      = asn_DEF_NativeEnumerated.specifics;	// Defined explicitly */
}

static void
mpdcch_NumRepetition_r13_55_free(asn_TYPE_descriptor_t *td,
		void *struct_ptr, int contents_only) {
	mpdcch_NumRepetition_r13_55_inherit_TYPE_descriptor(td);
	td->free_struct(td, struct_ptr, contents_only);
}

static int
mpdcch_NumRepetition_r13_55_print(asn_TYPE_descriptor_t *td, const void *struct_ptr,
		int ilevel, asn_app_consume_bytes_f *cb, void *app_key) {
	mpdcch_NumRepetition_r13_55_inherit_TYPE_descriptor(td);
	return td->print_struct(td, struct_ptr, ilevel, cb, app_key);
}

static asn_dec_rval_t
mpdcch_NumRepetition_r13_55_decode_ber(asn_codec_ctx_t *opt_codec_ctx, asn_TYPE_descriptor_t *td,
		void **structure, const void *bufptr, size_t size, int tag_mode) {
	mpdcch_NumRepetition_r13_55_inherit_TYPE_descriptor(td);
	return td->ber_decoder(opt_codec_ctx, td, structure, bufptr, size, tag_mode);
}

static asn_enc_rval_t
mpdcch_NumRepetition_r13_55_encode_der(asn_TYPE_descriptor_t *td,
		void *structure, int tag_mode, ber_tlv_tag_t tag,
		asn_app_consume_bytes_f *cb, void *app_key) {
	mpdcch_NumRepetition_r13_55_inherit_TYPE_descriptor(td);
	return td->der_encoder(td, structure, tag_mode, tag, cb, app_key);
}

static asn_dec_rval_t
mpdcch_NumRepetition_r13_55_decode_xer(asn_codec_ctx_t *opt_codec_ctx, asn_TYPE_descriptor_t *td,
		void **structure, const char *opt_mname, const void *bufptr, size_t size) {
	mpdcch_NumRepetition_r13_55_inherit_TYPE_descriptor(td);
	return td->xer_decoder(opt_codec_ctx, td, structure, opt_mname, bufptr, size);
}

static asn_enc_rval_t
mpdcch_NumRepetition_r13_55_encode_xer(asn_TYPE_descriptor_t *td, void *structure,
		int ilevel, enum xer_encoder_flags_e flags,
		asn_app_consume_bytes_f *cb, void *app_key) {
	mpdcch_NumRepetition_r13_55_inherit_TYPE_descriptor(td);
	return td->xer_encoder(td, structure, ilevel, flags, cb, app_key);
}

static asn_dec_rval_t
mpdcch_NumRepetition_r13_55_decode_uper(asn_codec_ctx_t *opt_codec_ctx, asn_TYPE_descriptor_t *td,
		asn_per_constraints_t *constraints, void **structure, asn_per_data_t *per_data) {
	mpdcch_NumRepetition_r13_55_inherit_TYPE_descriptor(td);
	return td->uper_decoder(opt_codec_ctx, td, constraints, structure, per_data);
}

static asn_enc_rval_t
mpdcch_NumRepetition_r13_55_encode_uper(asn_TYPE_descriptor_t *td,
		asn_per_constraints_t *constraints,
		void *structure, asn_per_outp_t *per_out) {
	mpdcch_NumRepetition_r13_55_inherit_TYPE_descriptor(td);
	return td->uper_encoder(td, constraints, structure, per_out);
}

static asn_dec_rval_t
mpdcch_NumRepetition_r13_55_decode_aper(asn_codec_ctx_t *opt_codec_ctx, asn_TYPE_descriptor_t *td,
		asn_per_constraints_t *constraints, void **structure, asn_per_data_t *per_data) {
	mpdcch_NumRepetition_r13_55_inherit_TYPE_descriptor(td);
	return td->aper_decoder(opt_codec_ctx, td, constraints, structure, per_data);
}

static asn_enc_rval_t
mpdcch_NumRepetition_r13_55_encode_aper(asn_TYPE_descriptor_t *td,
		asn_per_constraints_t *constraints,
		void *structure, asn_per_outp_t *per_out) {
	mpdcch_NumRepetition_r13_55_inherit_TYPE_descriptor(td);
	return td->aper_encoder(td, constraints, structure, per_out);
}

static int
memb_mpdcch_Narrowband_r13_constraint_25(asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	long long value;
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	value = *(const long long *)sptr;
	
	if((value >= 1LL && value <= 16LL)) {
		/* Constraint check succeeded */
		return 0;
	} else {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

static int
memb_dmrs_ScramblingSequenceInt_r11_constraint_1(asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	long long value;
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	value = *(const long long *)sptr;
	
	if((value >= 0LL && value <= 503LL)) {
		/* Constraint check succeeded */
		return 0;
	} else {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

static int
memb_pucch_ResourceStartOffset_r11_constraint_1(asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	long long value;
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	value = *(const long long *)sptr;
	
	if((value >= 0LL && value <= 2047LL)) {
		/* Constraint check succeeded */
		return 0;
	} else {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

static asn_per_constraints_t asn_PER_type_transmissionType_r11_constr_3 GCC_NOTUSED = {
	{ APC_CONSTRAINED,	 1,  1,  0,  1 }	/* (0..1) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_per_constraints_t asn_PER_type_numberPRB_Pairs_r11_constr_7 GCC_NOTUSED = {
	{ APC_CONSTRAINED,	 2,  2,  0,  2 }	/* (0..2) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_per_constraints_t asn_PER_memb_resourceBlockAssignment_r11_constr_11 GCC_NOTUSED = {
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	{ APC_CONSTRAINED,	 6,  6,  4,  38 }	/* (SIZE(4..38)) */,
	0, 0	/* No PER value map */
};
static asn_per_constraints_t asn_PER_type_csi_RS_ConfigZPId2_r12_constr_16 GCC_NOTUSED = {
	{ APC_CONSTRAINED,	 1,  1,  0,  1 }	/* (0..1) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_per_constraints_t asn_PER_type_setup_constr_21 GCC_NOTUSED = {
	{ APC_CONSTRAINED,	 0,  0,  0,  0 }	/* (0..0) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_per_constraints_t asn_PER_type_numberPRB_Pairs_v1310_constr_19 GCC_NOTUSED = {
	{ APC_CONSTRAINED,	 1,  1,  0,  1 }	/* (0..1) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_per_constraints_t asn_PER_type_csi_NumRepetitionCE_r13_constr_26 GCC_NOTUSED = {
	{ APC_CONSTRAINED,	 3,  3,  0,  5 }	/* (0..5) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_per_constraints_t asn_PER_type_mpdcch_pdsch_HoppingConfig_r13_constr_33 GCC_NOTUSED = {
	{ APC_CONSTRAINED,	 1,  1,  0,  1 }	/* (0..1) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_per_constraints_t asn_PER_type_fdd_r13_constr_37 GCC_NOTUSED = {
	{ APC_CONSTRAINED,	 3,  3,  0,  7 }	/* (0..7) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_per_constraints_t asn_PER_type_tdd_r13_constr_46 GCC_NOTUSED = {
	{ APC_CONSTRAINED,	 3,  3,  0,  7 }	/* (0..7) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_per_constraints_t asn_PER_type_mpdcch_StartSF_UESS_r13_constr_36 GCC_NOTUSED = {
	{ APC_CONSTRAINED,	 1,  1,  0,  1 }	/* (0..1) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_per_constraints_t asn_PER_type_mpdcch_NumRepetition_r13_constr_55 GCC_NOTUSED = {
	{ APC_CONSTRAINED,	 4,  4,  0,  8 }	/* (0..8) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_per_constraints_t asn_PER_memb_mpdcch_Narrowband_r13_constr_65 GCC_NOTUSED = {
	{ APC_CONSTRAINED,	 4,  4,  1,  16 }	/* (1..16) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_per_constraints_t asn_PER_type_mpdcch_config_r13_constr_23 GCC_NOTUSED = {
	{ APC_CONSTRAINED,	 1,  1,  0,  1 }	/* (0..1) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_per_constraints_t asn_PER_memb_dmrs_ScramblingSequenceInt_r11_constr_12 GCC_NOTUSED = {
	{ APC_CONSTRAINED,	 9,  9,  0,  503 }	/* (0..503) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_per_constraints_t asn_PER_memb_pucch_ResourceStartOffset_r11_constr_13 GCC_NOTUSED = {
	{ APC_CONSTRAINED,	 11,  11,  0,  2047 }	/* (0..2047) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static const asn_INTEGER_enum_map_t asn_MAP_transmissionType_r11_value2enum_3[] = {
	{ 0,	9,	"localised" },
	{ 1,	11,	"distributed" }
};
static const unsigned int asn_MAP_transmissionType_r11_enum2value_3[] = {
	1,	/* distributed(1) */
	0	/* localised(0) */
};
static const asn_INTEGER_specifics_t asn_SPC_transmissionType_r11_specs_3 = {
	asn_MAP_transmissionType_r11_value2enum_3,	/* "tag" => N; sorted by tag */
	asn_MAP_transmissionType_r11_enum2value_3,	/* N => "tag"; sorted by N */
	2,	/* Number of elements in the maps */
	0,	/* Enumeration is not extensible */
	1,	/* Strict enumeration */
	0,	/* Native long size */
	0
};
static const ber_tlv_tag_t asn_DEF_transmissionType_r11_tags_3[] = {
	(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (10 << 2))
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_transmissionType_r11_3 = {
	"transmissionType-r11",
	"transmissionType-r11",
	transmissionType_r11_3_free,
	transmissionType_r11_3_print,
	transmissionType_r11_3_constraint,
	transmissionType_r11_3_decode_ber,
	transmissionType_r11_3_encode_der,
	transmissionType_r11_3_decode_xer,
	transmissionType_r11_3_encode_xer,
	transmissionType_r11_3_decode_uper,
	transmissionType_r11_3_encode_uper,
	transmissionType_r11_3_decode_aper,
	transmissionType_r11_3_encode_aper,
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_transmissionType_r11_tags_3,
	sizeof(asn_DEF_transmissionType_r11_tags_3)
		/sizeof(asn_DEF_transmissionType_r11_tags_3[0]) - 1, /* 1 */
	asn_DEF_transmissionType_r11_tags_3,	/* Same as above */
	sizeof(asn_DEF_transmissionType_r11_tags_3)
		/sizeof(asn_DEF_transmissionType_r11_tags_3[0]), /* 2 */
	&asn_PER_type_transmissionType_r11_constr_3,
	0, 0,	/* Defined elsewhere */
	&asn_SPC_transmissionType_r11_specs_3	/* Additional specs */
};

static const asn_INTEGER_enum_map_t asn_MAP_numberPRB_Pairs_r11_value2enum_7[] = {
	{ 0,	2,	"n2" },
	{ 1,	2,	"n4" },
	{ 2,	2,	"n8" }
};
static const unsigned int asn_MAP_numberPRB_Pairs_r11_enum2value_7[] = {
	0,	/* n2(0) */
	1,	/* n4(1) */
	2	/* n8(2) */
};
static const asn_INTEGER_specifics_t asn_SPC_numberPRB_Pairs_r11_specs_7 = {
	asn_MAP_numberPRB_Pairs_r11_value2enum_7,	/* "tag" => N; sorted by tag */
	asn_MAP_numberPRB_Pairs_r11_enum2value_7,	/* N => "tag"; sorted by N */
	3,	/* Number of elements in the maps */
	0,	/* Enumeration is not extensible */
	1,	/* Strict enumeration */
	0,	/* Native long size */
	0
};
static const ber_tlv_tag_t asn_DEF_numberPRB_Pairs_r11_tags_7[] = {
	(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (10 << 2))
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_numberPRB_Pairs_r11_7 = {
	"numberPRB-Pairs-r11",
	"numberPRB-Pairs-r11",
	numberPRB_Pairs_r11_7_free,
	numberPRB_Pairs_r11_7_print,
	numberPRB_Pairs_r11_7_constraint,
	numberPRB_Pairs_r11_7_decode_ber,
	numberPRB_Pairs_r11_7_encode_der,
	numberPRB_Pairs_r11_7_decode_xer,
	numberPRB_Pairs_r11_7_encode_xer,
	numberPRB_Pairs_r11_7_decode_uper,
	numberPRB_Pairs_r11_7_encode_uper,
	numberPRB_Pairs_r11_7_decode_aper,
	numberPRB_Pairs_r11_7_encode_aper,
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_numberPRB_Pairs_r11_tags_7,
	sizeof(asn_DEF_numberPRB_Pairs_r11_tags_7)
		/sizeof(asn_DEF_numberPRB_Pairs_r11_tags_7[0]) - 1, /* 1 */
	asn_DEF_numberPRB_Pairs_r11_tags_7,	/* Same as above */
	sizeof(asn_DEF_numberPRB_Pairs_r11_tags_7)
		/sizeof(asn_DEF_numberPRB_Pairs_r11_tags_7[0]), /* 2 */
	&asn_PER_type_numberPRB_Pairs_r11_constr_7,
	0, 0,	/* Defined elsewhere */
	&asn_SPC_numberPRB_Pairs_r11_specs_7	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_resourceBlockAssignment_r11_6[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct EPDCCH_SetConfig_r11__resourceBlockAssignment_r11, numberPRB_Pairs_r11),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_numberPRB_Pairs_r11_7,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"numberPRB-Pairs-r11"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct EPDCCH_SetConfig_r11__resourceBlockAssignment_r11, resourceBlockAssignment_r11),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_BIT_STRING,
		memb_resourceBlockAssignment_r11_constraint_6,
		&asn_PER_memb_resourceBlockAssignment_r11_constr_11,
		0,
		"resourceBlockAssignment-r11"
		},
};
static const ber_tlv_tag_t asn_DEF_resourceBlockAssignment_r11_tags_6[] = {
	(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_resourceBlockAssignment_r11_tag2el_6[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* numberPRB-Pairs-r11 */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 } /* resourceBlockAssignment-r11 */
};
static asn_SEQUENCE_specifics_t asn_SPC_resourceBlockAssignment_r11_specs_6 = {
	sizeof(struct EPDCCH_SetConfig_r11__resourceBlockAssignment_r11),
	offsetof(struct EPDCCH_SetConfig_r11__resourceBlockAssignment_r11, _asn_ctx),
	asn_MAP_resourceBlockAssignment_r11_tag2el_6,
	2,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* Start extensions */
	-1	/* Stop extensions */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_resourceBlockAssignment_r11_6 = {
	"resourceBlockAssignment-r11",
	"resourceBlockAssignment-r11",
	SEQUENCE_free,
	SEQUENCE_print,
	SEQUENCE_constraint,
	SEQUENCE_decode_ber,
	SEQUENCE_encode_der,
	SEQUENCE_decode_xer,
	SEQUENCE_encode_xer,
	SEQUENCE_decode_uper,
	SEQUENCE_encode_uper,
	SEQUENCE_decode_aper,
	SEQUENCE_encode_aper,
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_resourceBlockAssignment_r11_tags_6,
	sizeof(asn_DEF_resourceBlockAssignment_r11_tags_6)
		/sizeof(asn_DEF_resourceBlockAssignment_r11_tags_6[0]) - 1, /* 1 */
	asn_DEF_resourceBlockAssignment_r11_tags_6,	/* Same as above */
	sizeof(asn_DEF_resourceBlockAssignment_r11_tags_6)
		/sizeof(asn_DEF_resourceBlockAssignment_r11_tags_6[0]), /* 2 */
	0,	/* No PER visible constraints */
	asn_MBR_resourceBlockAssignment_r11_6,
	2,	/* Elements count */
	&asn_SPC_resourceBlockAssignment_r11_specs_6	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_csi_RS_ConfigZPId2_r12_16[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct EPDCCH_SetConfig_r11__csi_RS_ConfigZPId2_r12, choice.release),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NULL,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"release"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct EPDCCH_SetConfig_r11__csi_RS_ConfigZPId2_r12, choice.setup),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_CSI_RS_ConfigZPId_r11,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"setup"
		},
};
static const asn_TYPE_tag2member_t asn_MAP_csi_RS_ConfigZPId2_r12_tag2el_16[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* release */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 } /* setup */
};
static asn_CHOICE_specifics_t asn_SPC_csi_RS_ConfigZPId2_r12_specs_16 = {
	sizeof(struct EPDCCH_SetConfig_r11__csi_RS_ConfigZPId2_r12),
	offsetof(struct EPDCCH_SetConfig_r11__csi_RS_ConfigZPId2_r12, _asn_ctx),
	offsetof(struct EPDCCH_SetConfig_r11__csi_RS_ConfigZPId2_r12, present),
	sizeof(((struct EPDCCH_SetConfig_r11__csi_RS_ConfigZPId2_r12 *)0)->present),
	asn_MAP_csi_RS_ConfigZPId2_r12_tag2el_16,
	2,	/* Count of tags in the map */
	0,
	-1	/* Extensions start */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_csi_RS_ConfigZPId2_r12_16 = {
	"csi-RS-ConfigZPId2-r12",
	"csi-RS-ConfigZPId2-r12",
	CHOICE_free,
	CHOICE_print,
	CHOICE_constraint,
	CHOICE_decode_ber,
	CHOICE_encode_der,
	CHOICE_decode_xer,
	CHOICE_encode_xer,
	CHOICE_decode_uper,
	CHOICE_encode_uper,
	CHOICE_decode_aper,
	CHOICE_encode_aper,
	CHOICE_outmost_tag,
	0,	/* No effective tags (pointer) */
	0,	/* No effective tags (count) */
	0,	/* No tags (pointer) */
	0,	/* No tags (count) */
	&asn_PER_type_csi_RS_ConfigZPId2_r12_constr_16,
	asn_MBR_csi_RS_ConfigZPId2_r12_16,
	2,	/* Elements count */
	&asn_SPC_csi_RS_ConfigZPId2_r12_specs_16	/* Additional specs */
};

static const asn_INTEGER_enum_map_t asn_MAP_setup_value2enum_21[] = {
	{ 0,	2,	"n6" }
};
static const unsigned int asn_MAP_setup_enum2value_21[] = {
	0	/* n6(0) */
};
static const asn_INTEGER_specifics_t asn_SPC_setup_specs_21 = {
	asn_MAP_setup_value2enum_21,	/* "tag" => N; sorted by tag */
	asn_MAP_setup_enum2value_21,	/* N => "tag"; sorted by N */
	1,	/* Number of elements in the maps */
	0,	/* Enumeration is not extensible */
	1,	/* Strict enumeration */
	0,	/* Native long size */
	0
};
static const ber_tlv_tag_t asn_DEF_setup_tags_21[] = {
	(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (10 << 2))
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_setup_21 = {
	"setup",
	"setup",
	setup_21_free,
	setup_21_print,
	setup_21_constraint,
	setup_21_decode_ber,
	setup_21_encode_der,
	setup_21_decode_xer,
	setup_21_encode_xer,
	setup_21_decode_uper,
	setup_21_encode_uper,
	setup_21_decode_aper,
	setup_21_encode_aper,
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_setup_tags_21,
	sizeof(asn_DEF_setup_tags_21)
		/sizeof(asn_DEF_setup_tags_21[0]) - 1, /* 1 */
	asn_DEF_setup_tags_21,	/* Same as above */
	sizeof(asn_DEF_setup_tags_21)
		/sizeof(asn_DEF_setup_tags_21[0]), /* 2 */
	&asn_PER_type_setup_constr_21,
	0, 0,	/* Defined elsewhere */
	&asn_SPC_setup_specs_21	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_numberPRB_Pairs_v1310_19[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct EPDCCH_SetConfig_r11__numberPRB_Pairs_v1310, choice.release),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NULL,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"release"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct EPDCCH_SetConfig_r11__numberPRB_Pairs_v1310, choice.setup),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_setup_21,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"setup"
		},
};
static const asn_TYPE_tag2member_t asn_MAP_numberPRB_Pairs_v1310_tag2el_19[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* release */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 } /* setup */
};
static asn_CHOICE_specifics_t asn_SPC_numberPRB_Pairs_v1310_specs_19 = {
	sizeof(struct EPDCCH_SetConfig_r11__numberPRB_Pairs_v1310),
	offsetof(struct EPDCCH_SetConfig_r11__numberPRB_Pairs_v1310, _asn_ctx),
	offsetof(struct EPDCCH_SetConfig_r11__numberPRB_Pairs_v1310, present),
	sizeof(((struct EPDCCH_SetConfig_r11__numberPRB_Pairs_v1310 *)0)->present),
	asn_MAP_numberPRB_Pairs_v1310_tag2el_19,
	2,	/* Count of tags in the map */
	0,
	-1	/* Extensions start */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_numberPRB_Pairs_v1310_19 = {
	"numberPRB-Pairs-v1310",
	"numberPRB-Pairs-v1310",
	CHOICE_free,
	CHOICE_print,
	CHOICE_constraint,
	CHOICE_decode_ber,
	CHOICE_encode_der,
	CHOICE_decode_xer,
	CHOICE_encode_xer,
	CHOICE_decode_uper,
	CHOICE_encode_uper,
	CHOICE_decode_aper,
	CHOICE_encode_aper,
	CHOICE_outmost_tag,
	0,	/* No effective tags (pointer) */
	0,	/* No effective tags (count) */
	0,	/* No tags (pointer) */
	0,	/* No tags (count) */
	&asn_PER_type_numberPRB_Pairs_v1310_constr_19,
	asn_MBR_numberPRB_Pairs_v1310_19,
	2,	/* Elements count */
	&asn_SPC_numberPRB_Pairs_v1310_specs_19	/* Additional specs */
};

static const asn_INTEGER_enum_map_t asn_MAP_csi_NumRepetitionCE_r13_value2enum_26[] = {
	{ 0,	3,	"sf1" },
	{ 1,	3,	"sf2" },
	{ 2,	3,	"sf4" },
	{ 3,	3,	"sf8" },
	{ 4,	4,	"sf16" },
	{ 5,	4,	"sf32" }
};
static const unsigned int asn_MAP_csi_NumRepetitionCE_r13_enum2value_26[] = {
	0,	/* sf1(0) */
	4,	/* sf16(4) */
	1,	/* sf2(1) */
	5,	/* sf32(5) */
	2,	/* sf4(2) */
	3	/* sf8(3) */
};
static const asn_INTEGER_specifics_t asn_SPC_csi_NumRepetitionCE_r13_specs_26 = {
	asn_MAP_csi_NumRepetitionCE_r13_value2enum_26,	/* "tag" => N; sorted by tag */
	asn_MAP_csi_NumRepetitionCE_r13_enum2value_26,	/* N => "tag"; sorted by N */
	6,	/* Number of elements in the maps */
	0,	/* Enumeration is not extensible */
	1,	/* Strict enumeration */
	0,	/* Native long size */
	0
};
static const ber_tlv_tag_t asn_DEF_csi_NumRepetitionCE_r13_tags_26[] = {
	(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (10 << 2))
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_csi_NumRepetitionCE_r13_26 = {
	"csi-NumRepetitionCE-r13",
	"csi-NumRepetitionCE-r13",
	csi_NumRepetitionCE_r13_26_free,
	csi_NumRepetitionCE_r13_26_print,
	csi_NumRepetitionCE_r13_26_constraint,
	csi_NumRepetitionCE_r13_26_decode_ber,
	csi_NumRepetitionCE_r13_26_encode_der,
	csi_NumRepetitionCE_r13_26_decode_xer,
	csi_NumRepetitionCE_r13_26_encode_xer,
	csi_NumRepetitionCE_r13_26_decode_uper,
	csi_NumRepetitionCE_r13_26_encode_uper,
	csi_NumRepetitionCE_r13_26_decode_aper,
	csi_NumRepetitionCE_r13_26_encode_aper,
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_csi_NumRepetitionCE_r13_tags_26,
	sizeof(asn_DEF_csi_NumRepetitionCE_r13_tags_26)
		/sizeof(asn_DEF_csi_NumRepetitionCE_r13_tags_26[0]) - 1, /* 1 */
	asn_DEF_csi_NumRepetitionCE_r13_tags_26,	/* Same as above */
	sizeof(asn_DEF_csi_NumRepetitionCE_r13_tags_26)
		/sizeof(asn_DEF_csi_NumRepetitionCE_r13_tags_26[0]), /* 2 */
	&asn_PER_type_csi_NumRepetitionCE_r13_constr_26,
	0, 0,	/* Defined elsewhere */
	&asn_SPC_csi_NumRepetitionCE_r13_specs_26	/* Additional specs */
};

static const asn_INTEGER_enum_map_t asn_MAP_mpdcch_pdsch_HoppingConfig_r13_value2enum_33[] = {
	{ 0,	2,	"on" },
	{ 1,	3,	"off" }
};
static const unsigned int asn_MAP_mpdcch_pdsch_HoppingConfig_r13_enum2value_33[] = {
	1,	/* off(1) */
	0	/* on(0) */
};
static const asn_INTEGER_specifics_t asn_SPC_mpdcch_pdsch_HoppingConfig_r13_specs_33 = {
	asn_MAP_mpdcch_pdsch_HoppingConfig_r13_value2enum_33,	/* "tag" => N; sorted by tag */
	asn_MAP_mpdcch_pdsch_HoppingConfig_r13_enum2value_33,	/* N => "tag"; sorted by N */
	2,	/* Number of elements in the maps */
	0,	/* Enumeration is not extensible */
	1,	/* Strict enumeration */
	0,	/* Native long size */
	0
};
static const ber_tlv_tag_t asn_DEF_mpdcch_pdsch_HoppingConfig_r13_tags_33[] = {
	(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (10 << 2))
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_mpdcch_pdsch_HoppingConfig_r13_33 = {
	"mpdcch-pdsch-HoppingConfig-r13",
	"mpdcch-pdsch-HoppingConfig-r13",
	mpdcch_pdsch_HoppingConfig_r13_33_free,
	mpdcch_pdsch_HoppingConfig_r13_33_print,
	mpdcch_pdsch_HoppingConfig_r13_33_constraint,
	mpdcch_pdsch_HoppingConfig_r13_33_decode_ber,
	mpdcch_pdsch_HoppingConfig_r13_33_encode_der,
	mpdcch_pdsch_HoppingConfig_r13_33_decode_xer,
	mpdcch_pdsch_HoppingConfig_r13_33_encode_xer,
	mpdcch_pdsch_HoppingConfig_r13_33_decode_uper,
	mpdcch_pdsch_HoppingConfig_r13_33_encode_uper,
	mpdcch_pdsch_HoppingConfig_r13_33_decode_aper,
	mpdcch_pdsch_HoppingConfig_r13_33_encode_aper,
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_mpdcch_pdsch_HoppingConfig_r13_tags_33,
	sizeof(asn_DEF_mpdcch_pdsch_HoppingConfig_r13_tags_33)
		/sizeof(asn_DEF_mpdcch_pdsch_HoppingConfig_r13_tags_33[0]) - 1, /* 1 */
	asn_DEF_mpdcch_pdsch_HoppingConfig_r13_tags_33,	/* Same as above */
	sizeof(asn_DEF_mpdcch_pdsch_HoppingConfig_r13_tags_33)
		/sizeof(asn_DEF_mpdcch_pdsch_HoppingConfig_r13_tags_33[0]), /* 2 */
	&asn_PER_type_mpdcch_pdsch_HoppingConfig_r13_constr_33,
	0, 0,	/* Defined elsewhere */
	&asn_SPC_mpdcch_pdsch_HoppingConfig_r13_specs_33	/* Additional specs */
};

static const asn_INTEGER_enum_map_t asn_MAP_fdd_r13_value2enum_37[] = {
	{ 0,	2,	"v1" },
	{ 1,	6,	"v1dot5" },
	{ 2,	2,	"v2" },
	{ 3,	6,	"v2dot5" },
	{ 4,	2,	"v4" },
	{ 5,	2,	"v5" },
	{ 6,	2,	"v8" },
	{ 7,	3,	"v10" }
};
static const unsigned int asn_MAP_fdd_r13_enum2value_37[] = {
	0,	/* v1(0) */
	7,	/* v10(7) */
	1,	/* v1dot5(1) */
	2,	/* v2(2) */
	3,	/* v2dot5(3) */
	4,	/* v4(4) */
	5,	/* v5(5) */
	6	/* v8(6) */
};
static const asn_INTEGER_specifics_t asn_SPC_fdd_r13_specs_37 = {
	asn_MAP_fdd_r13_value2enum_37,	/* "tag" => N; sorted by tag */
	asn_MAP_fdd_r13_enum2value_37,	/* N => "tag"; sorted by N */
	8,	/* Number of elements in the maps */
	0,	/* Enumeration is not extensible */
	1,	/* Strict enumeration */
	0,	/* Native long size */
	0
};
static const ber_tlv_tag_t asn_DEF_fdd_r13_tags_37[] = {
	(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (10 << 2))
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_fdd_r13_37 = {
	"fdd-r13",
	"fdd-r13",
	fdd_r13_37_free,
	fdd_r13_37_print,
	fdd_r13_37_constraint,
	fdd_r13_37_decode_ber,
	fdd_r13_37_encode_der,
	fdd_r13_37_decode_xer,
	fdd_r13_37_encode_xer,
	fdd_r13_37_decode_uper,
	fdd_r13_37_encode_uper,
	fdd_r13_37_decode_aper,
	fdd_r13_37_encode_aper,
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_fdd_r13_tags_37,
	sizeof(asn_DEF_fdd_r13_tags_37)
		/sizeof(asn_DEF_fdd_r13_tags_37[0]) - 1, /* 1 */
	asn_DEF_fdd_r13_tags_37,	/* Same as above */
	sizeof(asn_DEF_fdd_r13_tags_37)
		/sizeof(asn_DEF_fdd_r13_tags_37[0]), /* 2 */
	&asn_PER_type_fdd_r13_constr_37,
	0, 0,	/* Defined elsewhere */
	&asn_SPC_fdd_r13_specs_37	/* Additional specs */
};

static const asn_INTEGER_enum_map_t asn_MAP_tdd_r13_value2enum_46[] = {
	{ 0,	2,	"v1" },
	{ 1,	2,	"v2" },
	{ 2,	2,	"v4" },
	{ 3,	2,	"v5" },
	{ 4,	2,	"v8" },
	{ 5,	3,	"v10" },
	{ 6,	3,	"v20" },
	{ 7,	6,	"spare1" }
};
static const unsigned int asn_MAP_tdd_r13_enum2value_46[] = {
	7,	/* spare1(7) */
	0,	/* v1(0) */
	5,	/* v10(5) */
	1,	/* v2(1) */
	6,	/* v20(6) */
	2,	/* v4(2) */
	3,	/* v5(3) */
	4	/* v8(4) */
};
static const asn_INTEGER_specifics_t asn_SPC_tdd_r13_specs_46 = {
	asn_MAP_tdd_r13_value2enum_46,	/* "tag" => N; sorted by tag */
	asn_MAP_tdd_r13_enum2value_46,	/* N => "tag"; sorted by N */
	8,	/* Number of elements in the maps */
	0,	/* Enumeration is not extensible */
	1,	/* Strict enumeration */
	0,	/* Native long size */
	0
};
static const ber_tlv_tag_t asn_DEF_tdd_r13_tags_46[] = {
	(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (10 << 2))
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_tdd_r13_46 = {
	"tdd-r13",
	"tdd-r13",
	tdd_r13_46_free,
	tdd_r13_46_print,
	tdd_r13_46_constraint,
	tdd_r13_46_decode_ber,
	tdd_r13_46_encode_der,
	tdd_r13_46_decode_xer,
	tdd_r13_46_encode_xer,
	tdd_r13_46_decode_uper,
	tdd_r13_46_encode_uper,
	tdd_r13_46_decode_aper,
	tdd_r13_46_encode_aper,
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_tdd_r13_tags_46,
	sizeof(asn_DEF_tdd_r13_tags_46)
		/sizeof(asn_DEF_tdd_r13_tags_46[0]) - 1, /* 1 */
	asn_DEF_tdd_r13_tags_46,	/* Same as above */
	sizeof(asn_DEF_tdd_r13_tags_46)
		/sizeof(asn_DEF_tdd_r13_tags_46[0]), /* 2 */
	&asn_PER_type_tdd_r13_constr_46,
	0, 0,	/* Defined elsewhere */
	&asn_SPC_tdd_r13_specs_46	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_mpdcch_StartSF_UESS_r13_36[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct EPDCCH_SetConfig_r11__mpdcch_config_r13__setup__mpdcch_StartSF_UESS_r13, choice.fdd_r13),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_fdd_r13_37,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"fdd-r13"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct EPDCCH_SetConfig_r11__mpdcch_config_r13__setup__mpdcch_StartSF_UESS_r13, choice.tdd_r13),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_tdd_r13_46,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"tdd-r13"
		},
};
static const asn_TYPE_tag2member_t asn_MAP_mpdcch_StartSF_UESS_r13_tag2el_36[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* fdd-r13 */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 } /* tdd-r13 */
};
static asn_CHOICE_specifics_t asn_SPC_mpdcch_StartSF_UESS_r13_specs_36 = {
	sizeof(struct EPDCCH_SetConfig_r11__mpdcch_config_r13__setup__mpdcch_StartSF_UESS_r13),
	offsetof(struct EPDCCH_SetConfig_r11__mpdcch_config_r13__setup__mpdcch_StartSF_UESS_r13, _asn_ctx),
	offsetof(struct EPDCCH_SetConfig_r11__mpdcch_config_r13__setup__mpdcch_StartSF_UESS_r13, present),
	sizeof(((struct EPDCCH_SetConfig_r11__mpdcch_config_r13__setup__mpdcch_StartSF_UESS_r13 *)0)->present),
	asn_MAP_mpdcch_StartSF_UESS_r13_tag2el_36,
	2,	/* Count of tags in the map */
	0,
	-1	/* Extensions start */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_mpdcch_StartSF_UESS_r13_36 = {
	"mpdcch-StartSF-UESS-r13",
	"mpdcch-StartSF-UESS-r13",
	CHOICE_free,
	CHOICE_print,
	CHOICE_constraint,
	CHOICE_decode_ber,
	CHOICE_encode_der,
	CHOICE_decode_xer,
	CHOICE_encode_xer,
	CHOICE_decode_uper,
	CHOICE_encode_uper,
	CHOICE_decode_aper,
	CHOICE_encode_aper,
	CHOICE_outmost_tag,
	0,	/* No effective tags (pointer) */
	0,	/* No effective tags (count) */
	0,	/* No tags (pointer) */
	0,	/* No tags (count) */
	&asn_PER_type_mpdcch_StartSF_UESS_r13_constr_36,
	asn_MBR_mpdcch_StartSF_UESS_r13_36,
	2,	/* Elements count */
	&asn_SPC_mpdcch_StartSF_UESS_r13_specs_36	/* Additional specs */
};

static const asn_INTEGER_enum_map_t asn_MAP_mpdcch_NumRepetition_r13_value2enum_55[] = {
	{ 0,	2,	"r1" },
	{ 1,	2,	"r2" },
	{ 2,	2,	"r4" },
	{ 3,	2,	"r8" },
	{ 4,	3,	"r16" },
	{ 5,	3,	"r32" },
	{ 6,	3,	"r64" },
	{ 7,	4,	"r128" },
	{ 8,	4,	"r256" }
};
static const unsigned int asn_MAP_mpdcch_NumRepetition_r13_enum2value_55[] = {
	0,	/* r1(0) */
	7,	/* r128(7) */
	4,	/* r16(4) */
	1,	/* r2(1) */
	8,	/* r256(8) */
	5,	/* r32(5) */
	2,	/* r4(2) */
	6,	/* r64(6) */
	3	/* r8(3) */
};
static const asn_INTEGER_specifics_t asn_SPC_mpdcch_NumRepetition_r13_specs_55 = {
	asn_MAP_mpdcch_NumRepetition_r13_value2enum_55,	/* "tag" => N; sorted by tag */
	asn_MAP_mpdcch_NumRepetition_r13_enum2value_55,	/* N => "tag"; sorted by N */
	9,	/* Number of elements in the maps */
	0,	/* Enumeration is not extensible */
	1,	/* Strict enumeration */
	0,	/* Native long size */
	0
};
static const ber_tlv_tag_t asn_DEF_mpdcch_NumRepetition_r13_tags_55[] = {
	(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (10 << 2))
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_mpdcch_NumRepetition_r13_55 = {
	"mpdcch-NumRepetition-r13",
	"mpdcch-NumRepetition-r13",
	mpdcch_NumRepetition_r13_55_free,
	mpdcch_NumRepetition_r13_55_print,
	mpdcch_NumRepetition_r13_55_constraint,
	mpdcch_NumRepetition_r13_55_decode_ber,
	mpdcch_NumRepetition_r13_55_encode_der,
	mpdcch_NumRepetition_r13_55_decode_xer,
	mpdcch_NumRepetition_r13_55_encode_xer,
	mpdcch_NumRepetition_r13_55_decode_uper,
	mpdcch_NumRepetition_r13_55_encode_uper,
	mpdcch_NumRepetition_r13_55_decode_aper,
	mpdcch_NumRepetition_r13_55_encode_aper,
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_mpdcch_NumRepetition_r13_tags_55,
	sizeof(asn_DEF_mpdcch_NumRepetition_r13_tags_55)
		/sizeof(asn_DEF_mpdcch_NumRepetition_r13_tags_55[0]) - 1, /* 1 */
	asn_DEF_mpdcch_NumRepetition_r13_tags_55,	/* Same as above */
	sizeof(asn_DEF_mpdcch_NumRepetition_r13_tags_55)
		/sizeof(asn_DEF_mpdcch_NumRepetition_r13_tags_55[0]), /* 2 */
	&asn_PER_type_mpdcch_NumRepetition_r13_constr_55,
	0, 0,	/* Defined elsewhere */
	&asn_SPC_mpdcch_NumRepetition_r13_specs_55	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_setup_25[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct EPDCCH_SetConfig_r11__mpdcch_config_r13__setup, csi_NumRepetitionCE_r13),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_csi_NumRepetitionCE_r13_26,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"csi-NumRepetitionCE-r13"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct EPDCCH_SetConfig_r11__mpdcch_config_r13__setup, mpdcch_pdsch_HoppingConfig_r13),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_mpdcch_pdsch_HoppingConfig_r13_33,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"mpdcch-pdsch-HoppingConfig-r13"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct EPDCCH_SetConfig_r11__mpdcch_config_r13__setup, mpdcch_StartSF_UESS_r13),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_mpdcch_StartSF_UESS_r13_36,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"mpdcch-StartSF-UESS-r13"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct EPDCCH_SetConfig_r11__mpdcch_config_r13__setup, mpdcch_NumRepetition_r13),
		(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_mpdcch_NumRepetition_r13_55,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"mpdcch-NumRepetition-r13"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct EPDCCH_SetConfig_r11__mpdcch_config_r13__setup, mpdcch_Narrowband_r13),
		(ASN_TAG_CLASS_CONTEXT | (4 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NativeInteger,
		memb_mpdcch_Narrowband_r13_constraint_25,
		&asn_PER_memb_mpdcch_Narrowband_r13_constr_65,
		0,
		"mpdcch-Narrowband-r13"
		},
};
static const ber_tlv_tag_t asn_DEF_setup_tags_25[] = {
	(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_setup_tag2el_25[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* csi-NumRepetitionCE-r13 */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* mpdcch-pdsch-HoppingConfig-r13 */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 }, /* mpdcch-StartSF-UESS-r13 */
    { (ASN_TAG_CLASS_CONTEXT | (3 << 2)), 3, 0, 0 }, /* mpdcch-NumRepetition-r13 */
    { (ASN_TAG_CLASS_CONTEXT | (4 << 2)), 4, 0, 0 } /* mpdcch-Narrowband-r13 */
};
static asn_SEQUENCE_specifics_t asn_SPC_setup_specs_25 = {
	sizeof(struct EPDCCH_SetConfig_r11__mpdcch_config_r13__setup),
	offsetof(struct EPDCCH_SetConfig_r11__mpdcch_config_r13__setup, _asn_ctx),
	asn_MAP_setup_tag2el_25,
	5,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* Start extensions */
	-1	/* Stop extensions */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_setup_25 = {
	"setup",
	"setup",
	SEQUENCE_free,
	SEQUENCE_print,
	SEQUENCE_constraint,
	SEQUENCE_decode_ber,
	SEQUENCE_encode_der,
	SEQUENCE_decode_xer,
	SEQUENCE_encode_xer,
	SEQUENCE_decode_uper,
	SEQUENCE_encode_uper,
	SEQUENCE_decode_aper,
	SEQUENCE_encode_aper,
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_setup_tags_25,
	sizeof(asn_DEF_setup_tags_25)
		/sizeof(asn_DEF_setup_tags_25[0]) - 1, /* 1 */
	asn_DEF_setup_tags_25,	/* Same as above */
	sizeof(asn_DEF_setup_tags_25)
		/sizeof(asn_DEF_setup_tags_25[0]), /* 2 */
	0,	/* No PER visible constraints */
	asn_MBR_setup_25,
	5,	/* Elements count */
	&asn_SPC_setup_specs_25	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_mpdcch_config_r13_23[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct EPDCCH_SetConfig_r11__mpdcch_config_r13, choice.release),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NULL,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"release"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct EPDCCH_SetConfig_r11__mpdcch_config_r13, choice.setup),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		0,
		&asn_DEF_setup_25,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"setup"
		},
};
static const asn_TYPE_tag2member_t asn_MAP_mpdcch_config_r13_tag2el_23[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* release */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 } /* setup */
};
static asn_CHOICE_specifics_t asn_SPC_mpdcch_config_r13_specs_23 = {
	sizeof(struct EPDCCH_SetConfig_r11__mpdcch_config_r13),
	offsetof(struct EPDCCH_SetConfig_r11__mpdcch_config_r13, _asn_ctx),
	offsetof(struct EPDCCH_SetConfig_r11__mpdcch_config_r13, present),
	sizeof(((struct EPDCCH_SetConfig_r11__mpdcch_config_r13 *)0)->present),
	asn_MAP_mpdcch_config_r13_tag2el_23,
	2,	/* Count of tags in the map */
	0,
	-1	/* Extensions start */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_mpdcch_config_r13_23 = {
	"mpdcch-config-r13",
	"mpdcch-config-r13",
	CHOICE_free,
	CHOICE_print,
	CHOICE_constraint,
	CHOICE_decode_ber,
	CHOICE_encode_der,
	CHOICE_decode_xer,
	CHOICE_encode_xer,
	CHOICE_decode_uper,
	CHOICE_encode_uper,
	CHOICE_decode_aper,
	CHOICE_encode_aper,
	CHOICE_outmost_tag,
	0,	/* No effective tags (pointer) */
	0,	/* No effective tags (count) */
	0,	/* No tags (pointer) */
	0,	/* No tags (count) */
	&asn_PER_type_mpdcch_config_r13_constr_23,
	asn_MBR_mpdcch_config_r13_23,
	2,	/* Elements count */
	&asn_SPC_mpdcch_config_r13_specs_23	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_EPDCCH_SetConfig_r11_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct EPDCCH_SetConfig_r11, setConfigId_r11),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_EPDCCH_SetConfigId_r11,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"setConfigId-r11"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct EPDCCH_SetConfig_r11, transmissionType_r11),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_transmissionType_r11_3,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"transmissionType-r11"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct EPDCCH_SetConfig_r11, resourceBlockAssignment_r11),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		0,
		&asn_DEF_resourceBlockAssignment_r11_6,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"resourceBlockAssignment-r11"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct EPDCCH_SetConfig_r11, dmrs_ScramblingSequenceInt_r11),
		(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NativeInteger,
		memb_dmrs_ScramblingSequenceInt_r11_constraint_1,
		&asn_PER_memb_dmrs_ScramblingSequenceInt_r11_constr_12,
		0,
		"dmrs-ScramblingSequenceInt-r11"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct EPDCCH_SetConfig_r11, pucch_ResourceStartOffset_r11),
		(ASN_TAG_CLASS_CONTEXT | (4 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NativeInteger,
		memb_pucch_ResourceStartOffset_r11_constraint_1,
		&asn_PER_memb_pucch_ResourceStartOffset_r11_constr_13,
		0,
		"pucch-ResourceStartOffset-r11"
		},
	{ ATF_POINTER, 4, offsetof(struct EPDCCH_SetConfig_r11, re_MappingQCL_ConfigId_r11),
		(ASN_TAG_CLASS_CONTEXT | (5 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_PDSCH_RE_MappingQCL_ConfigId_r11,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"re-MappingQCL-ConfigId-r11"
		},
	{ ATF_POINTER, 3, offsetof(struct EPDCCH_SetConfig_r11, csi_RS_ConfigZPId2_r12),
		(ASN_TAG_CLASS_CONTEXT | (6 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_csi_RS_ConfigZPId2_r12_16,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"csi-RS-ConfigZPId2-r12"
		},
	{ ATF_POINTER, 2, offsetof(struct EPDCCH_SetConfig_r11, numberPRB_Pairs_v1310),
		(ASN_TAG_CLASS_CONTEXT | (7 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_numberPRB_Pairs_v1310_19,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"numberPRB-Pairs-v1310"
		},
	{ ATF_POINTER, 1, offsetof(struct EPDCCH_SetConfig_r11, mpdcch_config_r13),
		(ASN_TAG_CLASS_CONTEXT | (8 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_mpdcch_config_r13_23,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"mpdcch-config-r13"
		},
};
static const int asn_MAP_EPDCCH_SetConfig_r11_oms_1[] = { 5, 6, 7, 8 };
static const ber_tlv_tag_t asn_DEF_EPDCCH_SetConfig_r11_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_EPDCCH_SetConfig_r11_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* setConfigId-r11 */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* transmissionType-r11 */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 }, /* resourceBlockAssignment-r11 */
    { (ASN_TAG_CLASS_CONTEXT | (3 << 2)), 3, 0, 0 }, /* dmrs-ScramblingSequenceInt-r11 */
    { (ASN_TAG_CLASS_CONTEXT | (4 << 2)), 4, 0, 0 }, /* pucch-ResourceStartOffset-r11 */
    { (ASN_TAG_CLASS_CONTEXT | (5 << 2)), 5, 0, 0 }, /* re-MappingQCL-ConfigId-r11 */
    { (ASN_TAG_CLASS_CONTEXT | (6 << 2)), 6, 0, 0 }, /* csi-RS-ConfigZPId2-r12 */
    { (ASN_TAG_CLASS_CONTEXT | (7 << 2)), 7, 0, 0 }, /* numberPRB-Pairs-v1310 */
    { (ASN_TAG_CLASS_CONTEXT | (8 << 2)), 8, 0, 0 } /* mpdcch-config-r13 */
};
static asn_SEQUENCE_specifics_t asn_SPC_EPDCCH_SetConfig_r11_specs_1 = {
	sizeof(struct EPDCCH_SetConfig_r11),
	offsetof(struct EPDCCH_SetConfig_r11, _asn_ctx),
	asn_MAP_EPDCCH_SetConfig_r11_tag2el_1,
	9,	/* Count of tags in the map */
	asn_MAP_EPDCCH_SetConfig_r11_oms_1,	/* Optional members */
	1, 3,	/* Root/Additions */
	5,	/* Start extensions */
	10	/* Stop extensions */
};
asn_TYPE_descriptor_t asn_DEF_EPDCCH_SetConfig_r11 = {
	"EPDCCH-SetConfig-r11",
	"EPDCCH-SetConfig-r11",
	SEQUENCE_free,
	SEQUENCE_print,
	SEQUENCE_constraint,
	SEQUENCE_decode_ber,
	SEQUENCE_encode_der,
	SEQUENCE_decode_xer,
	SEQUENCE_encode_xer,
	SEQUENCE_decode_uper,
	SEQUENCE_encode_uper,
	SEQUENCE_decode_aper,
	SEQUENCE_encode_aper,
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_EPDCCH_SetConfig_r11_tags_1,
	sizeof(asn_DEF_EPDCCH_SetConfig_r11_tags_1)
		/sizeof(asn_DEF_EPDCCH_SetConfig_r11_tags_1[0]), /* 1 */
	asn_DEF_EPDCCH_SetConfig_r11_tags_1,	/* Same as above */
	sizeof(asn_DEF_EPDCCH_SetConfig_r11_tags_1)
		/sizeof(asn_DEF_EPDCCH_SetConfig_r11_tags_1[0]), /* 1 */
	0,	/* No PER visible constraints */
	asn_MBR_EPDCCH_SetConfig_r11_1,
	9,	/* Elements count */
	&asn_SPC_EPDCCH_SetConfig_r11_specs_1	/* Additional specs */
};

