/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "EUTRA-RRC-Definitions"
 * 	found in "../asn1_defs/EUTRA-RRC-Definitions.asn"
 * 	`asn1c -gen-PER -fcompound-names -fnative-types`
 */

#include "MAC-MainConfig.h"

static int
maxHARQ_Tx_3_constraint(asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	/* Replace with underlying type checker */
	td->check_constraints = asn_DEF_NativeEnumerated.check_constraints;
	return td->check_constraints(td, sptr, ctfailcb, app_key);
}

/*
 * This type is implemented using NativeEnumerated,
 * so here we adjust the DEF accordingly.
 */
static void
maxHARQ_Tx_3_inherit_TYPE_descriptor(asn_TYPE_descriptor_t *td) {
	td->free_struct    = asn_DEF_NativeEnumerated.free_struct;
	td->print_struct   = asn_DEF_NativeEnumerated.print_struct;
	td->check_constraints = asn_DEF_NativeEnumerated.check_constraints;
	td->ber_decoder    = asn_DEF_NativeEnumerated.ber_decoder;
	td->der_encoder    = asn_DEF_NativeEnumerated.der_encoder;
	td->xer_decoder    = asn_DEF_NativeEnumerated.xer_decoder;
	td->xer_encoder    = asn_DEF_NativeEnumerated.xer_encoder;
	td->uper_decoder   = asn_DEF_NativeEnumerated.uper_decoder;
	td->uper_encoder   = asn_DEF_NativeEnumerated.uper_encoder;
	td->aper_decoder   = asn_DEF_NativeEnumerated.aper_decoder;
	td->aper_encoder   = asn_DEF_NativeEnumerated.aper_encoder;
	if(!td->per_constraints)
		td->per_constraints = asn_DEF_NativeEnumerated.per_constraints;
	td->elements       = asn_DEF_NativeEnumerated.elements;
	td->elements_count = asn_DEF_NativeEnumerated.elements_count;
     /* td->specifics      = asn_DEF_NativeEnumerated.specifics;	// Defined explicitly */
}

static void
maxHARQ_Tx_3_free(asn_TYPE_descriptor_t *td,
		void *struct_ptr, int contents_only) {
	maxHARQ_Tx_3_inherit_TYPE_descriptor(td);
	td->free_struct(td, struct_ptr, contents_only);
}

static int
maxHARQ_Tx_3_print(asn_TYPE_descriptor_t *td, const void *struct_ptr,
		int ilevel, asn_app_consume_bytes_f *cb, void *app_key) {
	maxHARQ_Tx_3_inherit_TYPE_descriptor(td);
	return td->print_struct(td, struct_ptr, ilevel, cb, app_key);
}

static asn_dec_rval_t
maxHARQ_Tx_3_decode_ber(asn_codec_ctx_t *opt_codec_ctx, asn_TYPE_descriptor_t *td,
		void **structure, const void *bufptr, size_t size, int tag_mode) {
	maxHARQ_Tx_3_inherit_TYPE_descriptor(td);
	return td->ber_decoder(opt_codec_ctx, td, structure, bufptr, size, tag_mode);
}

static asn_enc_rval_t
maxHARQ_Tx_3_encode_der(asn_TYPE_descriptor_t *td,
		void *structure, int tag_mode, ber_tlv_tag_t tag,
		asn_app_consume_bytes_f *cb, void *app_key) {
	maxHARQ_Tx_3_inherit_TYPE_descriptor(td);
	return td->der_encoder(td, structure, tag_mode, tag, cb, app_key);
}

static asn_dec_rval_t
maxHARQ_Tx_3_decode_xer(asn_codec_ctx_t *opt_codec_ctx, asn_TYPE_descriptor_t *td,
		void **structure, const char *opt_mname, const void *bufptr, size_t size) {
	maxHARQ_Tx_3_inherit_TYPE_descriptor(td);
	return td->xer_decoder(opt_codec_ctx, td, structure, opt_mname, bufptr, size);
}

static asn_enc_rval_t
maxHARQ_Tx_3_encode_xer(asn_TYPE_descriptor_t *td, void *structure,
		int ilevel, enum xer_encoder_flags_e flags,
		asn_app_consume_bytes_f *cb, void *app_key) {
	maxHARQ_Tx_3_inherit_TYPE_descriptor(td);
	return td->xer_encoder(td, structure, ilevel, flags, cb, app_key);
}

static asn_dec_rval_t
maxHARQ_Tx_3_decode_uper(asn_codec_ctx_t *opt_codec_ctx, asn_TYPE_descriptor_t *td,
		asn_per_constraints_t *constraints, void **structure, asn_per_data_t *per_data) {
	maxHARQ_Tx_3_inherit_TYPE_descriptor(td);
	return td->uper_decoder(opt_codec_ctx, td, constraints, structure, per_data);
}

static asn_enc_rval_t
maxHARQ_Tx_3_encode_uper(asn_TYPE_descriptor_t *td,
		asn_per_constraints_t *constraints,
		void *structure, asn_per_outp_t *per_out) {
	maxHARQ_Tx_3_inherit_TYPE_descriptor(td);
	return td->uper_encoder(td, constraints, structure, per_out);
}

static asn_dec_rval_t
maxHARQ_Tx_3_decode_aper(asn_codec_ctx_t *opt_codec_ctx, asn_TYPE_descriptor_t *td,
		asn_per_constraints_t *constraints, void **structure, asn_per_data_t *per_data) {
	maxHARQ_Tx_3_inherit_TYPE_descriptor(td);
	return td->aper_decoder(opt_codec_ctx, td, constraints, structure, per_data);
}

static asn_enc_rval_t
maxHARQ_Tx_3_encode_aper(asn_TYPE_descriptor_t *td,
		asn_per_constraints_t *constraints,
		void *structure, asn_per_outp_t *per_out) {
	maxHARQ_Tx_3_inherit_TYPE_descriptor(td);
	return td->aper_encoder(td, constraints, structure, per_out);
}

static int
periodicPHR_Timer_28_constraint(asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	/* Replace with underlying type checker */
	td->check_constraints = asn_DEF_NativeEnumerated.check_constraints;
	return td->check_constraints(td, sptr, ctfailcb, app_key);
}

/*
 * This type is implemented using NativeEnumerated,
 * so here we adjust the DEF accordingly.
 */
static void
periodicPHR_Timer_28_inherit_TYPE_descriptor(asn_TYPE_descriptor_t *td) {
	td->free_struct    = asn_DEF_NativeEnumerated.free_struct;
	td->print_struct   = asn_DEF_NativeEnumerated.print_struct;
	td->check_constraints = asn_DEF_NativeEnumerated.check_constraints;
	td->ber_decoder    = asn_DEF_NativeEnumerated.ber_decoder;
	td->der_encoder    = asn_DEF_NativeEnumerated.der_encoder;
	td->xer_decoder    = asn_DEF_NativeEnumerated.xer_decoder;
	td->xer_encoder    = asn_DEF_NativeEnumerated.xer_encoder;
	td->uper_decoder   = asn_DEF_NativeEnumerated.uper_decoder;
	td->uper_encoder   = asn_DEF_NativeEnumerated.uper_encoder;
	td->aper_decoder   = asn_DEF_NativeEnumerated.aper_decoder;
	td->aper_encoder   = asn_DEF_NativeEnumerated.aper_encoder;
	if(!td->per_constraints)
		td->per_constraints = asn_DEF_NativeEnumerated.per_constraints;
	td->elements       = asn_DEF_NativeEnumerated.elements;
	td->elements_count = asn_DEF_NativeEnumerated.elements_count;
     /* td->specifics      = asn_DEF_NativeEnumerated.specifics;	// Defined explicitly */
}

static void
periodicPHR_Timer_28_free(asn_TYPE_descriptor_t *td,
		void *struct_ptr, int contents_only) {
	periodicPHR_Timer_28_inherit_TYPE_descriptor(td);
	td->free_struct(td, struct_ptr, contents_only);
}

static int
periodicPHR_Timer_28_print(asn_TYPE_descriptor_t *td, const void *struct_ptr,
		int ilevel, asn_app_consume_bytes_f *cb, void *app_key) {
	periodicPHR_Timer_28_inherit_TYPE_descriptor(td);
	return td->print_struct(td, struct_ptr, ilevel, cb, app_key);
}

static asn_dec_rval_t
periodicPHR_Timer_28_decode_ber(asn_codec_ctx_t *opt_codec_ctx, asn_TYPE_descriptor_t *td,
		void **structure, const void *bufptr, size_t size, int tag_mode) {
	periodicPHR_Timer_28_inherit_TYPE_descriptor(td);
	return td->ber_decoder(opt_codec_ctx, td, structure, bufptr, size, tag_mode);
}

static asn_enc_rval_t
periodicPHR_Timer_28_encode_der(asn_TYPE_descriptor_t *td,
		void *structure, int tag_mode, ber_tlv_tag_t tag,
		asn_app_consume_bytes_f *cb, void *app_key) {
	periodicPHR_Timer_28_inherit_TYPE_descriptor(td);
	return td->der_encoder(td, structure, tag_mode, tag, cb, app_key);
}

static asn_dec_rval_t
periodicPHR_Timer_28_decode_xer(asn_codec_ctx_t *opt_codec_ctx, asn_TYPE_descriptor_t *td,
		void **structure, const char *opt_mname, const void *bufptr, size_t size) {
	periodicPHR_Timer_28_inherit_TYPE_descriptor(td);
	return td->xer_decoder(opt_codec_ctx, td, structure, opt_mname, bufptr, size);
}

static asn_enc_rval_t
periodicPHR_Timer_28_encode_xer(asn_TYPE_descriptor_t *td, void *structure,
		int ilevel, enum xer_encoder_flags_e flags,
		asn_app_consume_bytes_f *cb, void *app_key) {
	periodicPHR_Timer_28_inherit_TYPE_descriptor(td);
	return td->xer_encoder(td, structure, ilevel, flags, cb, app_key);
}

static asn_dec_rval_t
periodicPHR_Timer_28_decode_uper(asn_codec_ctx_t *opt_codec_ctx, asn_TYPE_descriptor_t *td,
		asn_per_constraints_t *constraints, void **structure, asn_per_data_t *per_data) {
	periodicPHR_Timer_28_inherit_TYPE_descriptor(td);
	return td->uper_decoder(opt_codec_ctx, td, constraints, structure, per_data);
}

static asn_enc_rval_t
periodicPHR_Timer_28_encode_uper(asn_TYPE_descriptor_t *td,
		asn_per_constraints_t *constraints,
		void *structure, asn_per_outp_t *per_out) {
	periodicPHR_Timer_28_inherit_TYPE_descriptor(td);
	return td->uper_encoder(td, constraints, structure, per_out);
}

static asn_dec_rval_t
periodicPHR_Timer_28_decode_aper(asn_codec_ctx_t *opt_codec_ctx, asn_TYPE_descriptor_t *td,
		asn_per_constraints_t *constraints, void **structure, asn_per_data_t *per_data) {
	periodicPHR_Timer_28_inherit_TYPE_descriptor(td);
	return td->aper_decoder(opt_codec_ctx, td, constraints, structure, per_data);
}

static asn_enc_rval_t
periodicPHR_Timer_28_encode_aper(asn_TYPE_descriptor_t *td,
		asn_per_constraints_t *constraints,
		void *structure, asn_per_outp_t *per_out) {
	periodicPHR_Timer_28_inherit_TYPE_descriptor(td);
	return td->aper_encoder(td, constraints, structure, per_out);
}

static int
prohibitPHR_Timer_37_constraint(asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	/* Replace with underlying type checker */
	td->check_constraints = asn_DEF_NativeEnumerated.check_constraints;
	return td->check_constraints(td, sptr, ctfailcb, app_key);
}

/*
 * This type is implemented using NativeEnumerated,
 * so here we adjust the DEF accordingly.
 */
static void
prohibitPHR_Timer_37_inherit_TYPE_descriptor(asn_TYPE_descriptor_t *td) {
	td->free_struct    = asn_DEF_NativeEnumerated.free_struct;
	td->print_struct   = asn_DEF_NativeEnumerated.print_struct;
	td->check_constraints = asn_DEF_NativeEnumerated.check_constraints;
	td->ber_decoder    = asn_DEF_NativeEnumerated.ber_decoder;
	td->der_encoder    = asn_DEF_NativeEnumerated.der_encoder;
	td->xer_decoder    = asn_DEF_NativeEnumerated.xer_decoder;
	td->xer_encoder    = asn_DEF_NativeEnumerated.xer_encoder;
	td->uper_decoder   = asn_DEF_NativeEnumerated.uper_decoder;
	td->uper_encoder   = asn_DEF_NativeEnumerated.uper_encoder;
	td->aper_decoder   = asn_DEF_NativeEnumerated.aper_decoder;
	td->aper_encoder   = asn_DEF_NativeEnumerated.aper_encoder;
	if(!td->per_constraints)
		td->per_constraints = asn_DEF_NativeEnumerated.per_constraints;
	td->elements       = asn_DEF_NativeEnumerated.elements;
	td->elements_count = asn_DEF_NativeEnumerated.elements_count;
     /* td->specifics      = asn_DEF_NativeEnumerated.specifics;	// Defined explicitly */
}

static void
prohibitPHR_Timer_37_free(asn_TYPE_descriptor_t *td,
		void *struct_ptr, int contents_only) {
	prohibitPHR_Timer_37_inherit_TYPE_descriptor(td);
	td->free_struct(td, struct_ptr, contents_only);
}

static int
prohibitPHR_Timer_37_print(asn_TYPE_descriptor_t *td, const void *struct_ptr,
		int ilevel, asn_app_consume_bytes_f *cb, void *app_key) {
	prohibitPHR_Timer_37_inherit_TYPE_descriptor(td);
	return td->print_struct(td, struct_ptr, ilevel, cb, app_key);
}

static asn_dec_rval_t
prohibitPHR_Timer_37_decode_ber(asn_codec_ctx_t *opt_codec_ctx, asn_TYPE_descriptor_t *td,
		void **structure, const void *bufptr, size_t size, int tag_mode) {
	prohibitPHR_Timer_37_inherit_TYPE_descriptor(td);
	return td->ber_decoder(opt_codec_ctx, td, structure, bufptr, size, tag_mode);
}

static asn_enc_rval_t
prohibitPHR_Timer_37_encode_der(asn_TYPE_descriptor_t *td,
		void *structure, int tag_mode, ber_tlv_tag_t tag,
		asn_app_consume_bytes_f *cb, void *app_key) {
	prohibitPHR_Timer_37_inherit_TYPE_descriptor(td);
	return td->der_encoder(td, structure, tag_mode, tag, cb, app_key);
}

static asn_dec_rval_t
prohibitPHR_Timer_37_decode_xer(asn_codec_ctx_t *opt_codec_ctx, asn_TYPE_descriptor_t *td,
		void **structure, const char *opt_mname, const void *bufptr, size_t size) {
	prohibitPHR_Timer_37_inherit_TYPE_descriptor(td);
	return td->xer_decoder(opt_codec_ctx, td, structure, opt_mname, bufptr, size);
}

static asn_enc_rval_t
prohibitPHR_Timer_37_encode_xer(asn_TYPE_descriptor_t *td, void *structure,
		int ilevel, enum xer_encoder_flags_e flags,
		asn_app_consume_bytes_f *cb, void *app_key) {
	prohibitPHR_Timer_37_inherit_TYPE_descriptor(td);
	return td->xer_encoder(td, structure, ilevel, flags, cb, app_key);
}

static asn_dec_rval_t
prohibitPHR_Timer_37_decode_uper(asn_codec_ctx_t *opt_codec_ctx, asn_TYPE_descriptor_t *td,
		asn_per_constraints_t *constraints, void **structure, asn_per_data_t *per_data) {
	prohibitPHR_Timer_37_inherit_TYPE_descriptor(td);
	return td->uper_decoder(opt_codec_ctx, td, constraints, structure, per_data);
}

static asn_enc_rval_t
prohibitPHR_Timer_37_encode_uper(asn_TYPE_descriptor_t *td,
		asn_per_constraints_t *constraints,
		void *structure, asn_per_outp_t *per_out) {
	prohibitPHR_Timer_37_inherit_TYPE_descriptor(td);
	return td->uper_encoder(td, constraints, structure, per_out);
}

static asn_dec_rval_t
prohibitPHR_Timer_37_decode_aper(asn_codec_ctx_t *opt_codec_ctx, asn_TYPE_descriptor_t *td,
		asn_per_constraints_t *constraints, void **structure, asn_per_data_t *per_data) {
	prohibitPHR_Timer_37_inherit_TYPE_descriptor(td);
	return td->aper_decoder(opt_codec_ctx, td, constraints, structure, per_data);
}

static asn_enc_rval_t
prohibitPHR_Timer_37_encode_aper(asn_TYPE_descriptor_t *td,
		asn_per_constraints_t *constraints,
		void *structure, asn_per_outp_t *per_out) {
	prohibitPHR_Timer_37_inherit_TYPE_descriptor(td);
	return td->aper_encoder(td, constraints, structure, per_out);
}

static int
dl_PathlossChange_46_constraint(asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	/* Replace with underlying type checker */
	td->check_constraints = asn_DEF_NativeEnumerated.check_constraints;
	return td->check_constraints(td, sptr, ctfailcb, app_key);
}

/*
 * This type is implemented using NativeEnumerated,
 * so here we adjust the DEF accordingly.
 */
static void
dl_PathlossChange_46_inherit_TYPE_descriptor(asn_TYPE_descriptor_t *td) {
	td->free_struct    = asn_DEF_NativeEnumerated.free_struct;
	td->print_struct   = asn_DEF_NativeEnumerated.print_struct;
	td->check_constraints = asn_DEF_NativeEnumerated.check_constraints;
	td->ber_decoder    = asn_DEF_NativeEnumerated.ber_decoder;
	td->der_encoder    = asn_DEF_NativeEnumerated.der_encoder;
	td->xer_decoder    = asn_DEF_NativeEnumerated.xer_decoder;
	td->xer_encoder    = asn_DEF_NativeEnumerated.xer_encoder;
	td->uper_decoder   = asn_DEF_NativeEnumerated.uper_decoder;
	td->uper_encoder   = asn_DEF_NativeEnumerated.uper_encoder;
	td->aper_decoder   = asn_DEF_NativeEnumerated.aper_decoder;
	td->aper_encoder   = asn_DEF_NativeEnumerated.aper_encoder;
	if(!td->per_constraints)
		td->per_constraints = asn_DEF_NativeEnumerated.per_constraints;
	td->elements       = asn_DEF_NativeEnumerated.elements;
	td->elements_count = asn_DEF_NativeEnumerated.elements_count;
     /* td->specifics      = asn_DEF_NativeEnumerated.specifics;	// Defined explicitly */
}

static void
dl_PathlossChange_46_free(asn_TYPE_descriptor_t *td,
		void *struct_ptr, int contents_only) {
	dl_PathlossChange_46_inherit_TYPE_descriptor(td);
	td->free_struct(td, struct_ptr, contents_only);
}

static int
dl_PathlossChange_46_print(asn_TYPE_descriptor_t *td, const void *struct_ptr,
		int ilevel, asn_app_consume_bytes_f *cb, void *app_key) {
	dl_PathlossChange_46_inherit_TYPE_descriptor(td);
	return td->print_struct(td, struct_ptr, ilevel, cb, app_key);
}

static asn_dec_rval_t
dl_PathlossChange_46_decode_ber(asn_codec_ctx_t *opt_codec_ctx, asn_TYPE_descriptor_t *td,
		void **structure, const void *bufptr, size_t size, int tag_mode) {
	dl_PathlossChange_46_inherit_TYPE_descriptor(td);
	return td->ber_decoder(opt_codec_ctx, td, structure, bufptr, size, tag_mode);
}

static asn_enc_rval_t
dl_PathlossChange_46_encode_der(asn_TYPE_descriptor_t *td,
		void *structure, int tag_mode, ber_tlv_tag_t tag,
		asn_app_consume_bytes_f *cb, void *app_key) {
	dl_PathlossChange_46_inherit_TYPE_descriptor(td);
	return td->der_encoder(td, structure, tag_mode, tag, cb, app_key);
}

static asn_dec_rval_t
dl_PathlossChange_46_decode_xer(asn_codec_ctx_t *opt_codec_ctx, asn_TYPE_descriptor_t *td,
		void **structure, const char *opt_mname, const void *bufptr, size_t size) {
	dl_PathlossChange_46_inherit_TYPE_descriptor(td);
	return td->xer_decoder(opt_codec_ctx, td, structure, opt_mname, bufptr, size);
}

static asn_enc_rval_t
dl_PathlossChange_46_encode_xer(asn_TYPE_descriptor_t *td, void *structure,
		int ilevel, enum xer_encoder_flags_e flags,
		asn_app_consume_bytes_f *cb, void *app_key) {
	dl_PathlossChange_46_inherit_TYPE_descriptor(td);
	return td->xer_encoder(td, structure, ilevel, flags, cb, app_key);
}

static asn_dec_rval_t
dl_PathlossChange_46_decode_uper(asn_codec_ctx_t *opt_codec_ctx, asn_TYPE_descriptor_t *td,
		asn_per_constraints_t *constraints, void **structure, asn_per_data_t *per_data) {
	dl_PathlossChange_46_inherit_TYPE_descriptor(td);
	return td->uper_decoder(opt_codec_ctx, td, constraints, structure, per_data);
}

static asn_enc_rval_t
dl_PathlossChange_46_encode_uper(asn_TYPE_descriptor_t *td,
		asn_per_constraints_t *constraints,
		void *structure, asn_per_outp_t *per_out) {
	dl_PathlossChange_46_inherit_TYPE_descriptor(td);
	return td->uper_encoder(td, constraints, structure, per_out);
}

static asn_dec_rval_t
dl_PathlossChange_46_decode_aper(asn_codec_ctx_t *opt_codec_ctx, asn_TYPE_descriptor_t *td,
		asn_per_constraints_t *constraints, void **structure, asn_per_data_t *per_data) {
	dl_PathlossChange_46_inherit_TYPE_descriptor(td);
	return td->aper_decoder(opt_codec_ctx, td, constraints, structure, per_data);
}

static asn_enc_rval_t
dl_PathlossChange_46_encode_aper(asn_TYPE_descriptor_t *td,
		asn_per_constraints_t *constraints,
		void *structure, asn_per_outp_t *per_out) {
	dl_PathlossChange_46_inherit_TYPE_descriptor(td);
	return td->aper_encoder(td, constraints, structure, per_out);
}

static int
sCellDeactivationTimer_r10_54_constraint(asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	/* Replace with underlying type checker */
	td->check_constraints = asn_DEF_NativeEnumerated.check_constraints;
	return td->check_constraints(td, sptr, ctfailcb, app_key);
}

/*
 * This type is implemented using NativeEnumerated,
 * so here we adjust the DEF accordingly.
 */
static void
sCellDeactivationTimer_r10_54_inherit_TYPE_descriptor(asn_TYPE_descriptor_t *td) {
	td->free_struct    = asn_DEF_NativeEnumerated.free_struct;
	td->print_struct   = asn_DEF_NativeEnumerated.print_struct;
	td->check_constraints = asn_DEF_NativeEnumerated.check_constraints;
	td->ber_decoder    = asn_DEF_NativeEnumerated.ber_decoder;
	td->der_encoder    = asn_DEF_NativeEnumerated.der_encoder;
	td->xer_decoder    = asn_DEF_NativeEnumerated.xer_decoder;
	td->xer_encoder    = asn_DEF_NativeEnumerated.xer_encoder;
	td->uper_decoder   = asn_DEF_NativeEnumerated.uper_decoder;
	td->uper_encoder   = asn_DEF_NativeEnumerated.uper_encoder;
	td->aper_decoder   = asn_DEF_NativeEnumerated.aper_decoder;
	td->aper_encoder   = asn_DEF_NativeEnumerated.aper_encoder;
	if(!td->per_constraints)
		td->per_constraints = asn_DEF_NativeEnumerated.per_constraints;
	td->elements       = asn_DEF_NativeEnumerated.elements;
	td->elements_count = asn_DEF_NativeEnumerated.elements_count;
     /* td->specifics      = asn_DEF_NativeEnumerated.specifics;	// Defined explicitly */
}

static void
sCellDeactivationTimer_r10_54_free(asn_TYPE_descriptor_t *td,
		void *struct_ptr, int contents_only) {
	sCellDeactivationTimer_r10_54_inherit_TYPE_descriptor(td);
	td->free_struct(td, struct_ptr, contents_only);
}

static int
sCellDeactivationTimer_r10_54_print(asn_TYPE_descriptor_t *td, const void *struct_ptr,
		int ilevel, asn_app_consume_bytes_f *cb, void *app_key) {
	sCellDeactivationTimer_r10_54_inherit_TYPE_descriptor(td);
	return td->print_struct(td, struct_ptr, ilevel, cb, app_key);
}

static asn_dec_rval_t
sCellDeactivationTimer_r10_54_decode_ber(asn_codec_ctx_t *opt_codec_ctx, asn_TYPE_descriptor_t *td,
		void **structure, const void *bufptr, size_t size, int tag_mode) {
	sCellDeactivationTimer_r10_54_inherit_TYPE_descriptor(td);
	return td->ber_decoder(opt_codec_ctx, td, structure, bufptr, size, tag_mode);
}

static asn_enc_rval_t
sCellDeactivationTimer_r10_54_encode_der(asn_TYPE_descriptor_t *td,
		void *structure, int tag_mode, ber_tlv_tag_t tag,
		asn_app_consume_bytes_f *cb, void *app_key) {
	sCellDeactivationTimer_r10_54_inherit_TYPE_descriptor(td);
	return td->der_encoder(td, structure, tag_mode, tag, cb, app_key);
}

static asn_dec_rval_t
sCellDeactivationTimer_r10_54_decode_xer(asn_codec_ctx_t *opt_codec_ctx, asn_TYPE_descriptor_t *td,
		void **structure, const char *opt_mname, const void *bufptr, size_t size) {
	sCellDeactivationTimer_r10_54_inherit_TYPE_descriptor(td);
	return td->xer_decoder(opt_codec_ctx, td, structure, opt_mname, bufptr, size);
}

static asn_enc_rval_t
sCellDeactivationTimer_r10_54_encode_xer(asn_TYPE_descriptor_t *td, void *structure,
		int ilevel, enum xer_encoder_flags_e flags,
		asn_app_consume_bytes_f *cb, void *app_key) {
	sCellDeactivationTimer_r10_54_inherit_TYPE_descriptor(td);
	return td->xer_encoder(td, structure, ilevel, flags, cb, app_key);
}

static asn_dec_rval_t
sCellDeactivationTimer_r10_54_decode_uper(asn_codec_ctx_t *opt_codec_ctx, asn_TYPE_descriptor_t *td,
		asn_per_constraints_t *constraints, void **structure, asn_per_data_t *per_data) {
	sCellDeactivationTimer_r10_54_inherit_TYPE_descriptor(td);
	return td->uper_decoder(opt_codec_ctx, td, constraints, structure, per_data);
}

static asn_enc_rval_t
sCellDeactivationTimer_r10_54_encode_uper(asn_TYPE_descriptor_t *td,
		asn_per_constraints_t *constraints,
		void *structure, asn_per_outp_t *per_out) {
	sCellDeactivationTimer_r10_54_inherit_TYPE_descriptor(td);
	return td->uper_encoder(td, constraints, structure, per_out);
}

static asn_dec_rval_t
sCellDeactivationTimer_r10_54_decode_aper(asn_codec_ctx_t *opt_codec_ctx, asn_TYPE_descriptor_t *td,
		asn_per_constraints_t *constraints, void **structure, asn_per_data_t *per_data) {
	sCellDeactivationTimer_r10_54_inherit_TYPE_descriptor(td);
	return td->aper_decoder(opt_codec_ctx, td, constraints, structure, per_data);
}

static asn_enc_rval_t
sCellDeactivationTimer_r10_54_encode_aper(asn_TYPE_descriptor_t *td,
		asn_per_constraints_t *constraints,
		void *structure, asn_per_outp_t *per_out) {
	sCellDeactivationTimer_r10_54_inherit_TYPE_descriptor(td);
	return td->aper_encoder(td, constraints, structure, per_out);
}

static int
extendedBSR_Sizes_r10_63_constraint(asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	/* Replace with underlying type checker */
	td->check_constraints = asn_DEF_NativeEnumerated.check_constraints;
	return td->check_constraints(td, sptr, ctfailcb, app_key);
}

/*
 * This type is implemented using NativeEnumerated,
 * so here we adjust the DEF accordingly.
 */
static void
extendedBSR_Sizes_r10_63_inherit_TYPE_descriptor(asn_TYPE_descriptor_t *td) {
	td->free_struct    = asn_DEF_NativeEnumerated.free_struct;
	td->print_struct   = asn_DEF_NativeEnumerated.print_struct;
	td->check_constraints = asn_DEF_NativeEnumerated.check_constraints;
	td->ber_decoder    = asn_DEF_NativeEnumerated.ber_decoder;
	td->der_encoder    = asn_DEF_NativeEnumerated.der_encoder;
	td->xer_decoder    = asn_DEF_NativeEnumerated.xer_decoder;
	td->xer_encoder    = asn_DEF_NativeEnumerated.xer_encoder;
	td->uper_decoder   = asn_DEF_NativeEnumerated.uper_decoder;
	td->uper_encoder   = asn_DEF_NativeEnumerated.uper_encoder;
	td->aper_decoder   = asn_DEF_NativeEnumerated.aper_decoder;
	td->aper_encoder   = asn_DEF_NativeEnumerated.aper_encoder;
	if(!td->per_constraints)
		td->per_constraints = asn_DEF_NativeEnumerated.per_constraints;
	td->elements       = asn_DEF_NativeEnumerated.elements;
	td->elements_count = asn_DEF_NativeEnumerated.elements_count;
     /* td->specifics      = asn_DEF_NativeEnumerated.specifics;	// Defined explicitly */
}

static void
extendedBSR_Sizes_r10_63_free(asn_TYPE_descriptor_t *td,
		void *struct_ptr, int contents_only) {
	extendedBSR_Sizes_r10_63_inherit_TYPE_descriptor(td);
	td->free_struct(td, struct_ptr, contents_only);
}

static int
extendedBSR_Sizes_r10_63_print(asn_TYPE_descriptor_t *td, const void *struct_ptr,
		int ilevel, asn_app_consume_bytes_f *cb, void *app_key) {
	extendedBSR_Sizes_r10_63_inherit_TYPE_descriptor(td);
	return td->print_struct(td, struct_ptr, ilevel, cb, app_key);
}

static asn_dec_rval_t
extendedBSR_Sizes_r10_63_decode_ber(asn_codec_ctx_t *opt_codec_ctx, asn_TYPE_descriptor_t *td,
		void **structure, const void *bufptr, size_t size, int tag_mode) {
	extendedBSR_Sizes_r10_63_inherit_TYPE_descriptor(td);
	return td->ber_decoder(opt_codec_ctx, td, structure, bufptr, size, tag_mode);
}

static asn_enc_rval_t
extendedBSR_Sizes_r10_63_encode_der(asn_TYPE_descriptor_t *td,
		void *structure, int tag_mode, ber_tlv_tag_t tag,
		asn_app_consume_bytes_f *cb, void *app_key) {
	extendedBSR_Sizes_r10_63_inherit_TYPE_descriptor(td);
	return td->der_encoder(td, structure, tag_mode, tag, cb, app_key);
}

static asn_dec_rval_t
extendedBSR_Sizes_r10_63_decode_xer(asn_codec_ctx_t *opt_codec_ctx, asn_TYPE_descriptor_t *td,
		void **structure, const char *opt_mname, const void *bufptr, size_t size) {
	extendedBSR_Sizes_r10_63_inherit_TYPE_descriptor(td);
	return td->xer_decoder(opt_codec_ctx, td, structure, opt_mname, bufptr, size);
}

static asn_enc_rval_t
extendedBSR_Sizes_r10_63_encode_xer(asn_TYPE_descriptor_t *td, void *structure,
		int ilevel, enum xer_encoder_flags_e flags,
		asn_app_consume_bytes_f *cb, void *app_key) {
	extendedBSR_Sizes_r10_63_inherit_TYPE_descriptor(td);
	return td->xer_encoder(td, structure, ilevel, flags, cb, app_key);
}

static asn_dec_rval_t
extendedBSR_Sizes_r10_63_decode_uper(asn_codec_ctx_t *opt_codec_ctx, asn_TYPE_descriptor_t *td,
		asn_per_constraints_t *constraints, void **structure, asn_per_data_t *per_data) {
	extendedBSR_Sizes_r10_63_inherit_TYPE_descriptor(td);
	return td->uper_decoder(opt_codec_ctx, td, constraints, structure, per_data);
}

static asn_enc_rval_t
extendedBSR_Sizes_r10_63_encode_uper(asn_TYPE_descriptor_t *td,
		asn_per_constraints_t *constraints,
		void *structure, asn_per_outp_t *per_out) {
	extendedBSR_Sizes_r10_63_inherit_TYPE_descriptor(td);
	return td->uper_encoder(td, constraints, structure, per_out);
}

static asn_dec_rval_t
extendedBSR_Sizes_r10_63_decode_aper(asn_codec_ctx_t *opt_codec_ctx, asn_TYPE_descriptor_t *td,
		asn_per_constraints_t *constraints, void **structure, asn_per_data_t *per_data) {
	extendedBSR_Sizes_r10_63_inherit_TYPE_descriptor(td);
	return td->aper_decoder(opt_codec_ctx, td, constraints, structure, per_data);
}

static asn_enc_rval_t
extendedBSR_Sizes_r10_63_encode_aper(asn_TYPE_descriptor_t *td,
		asn_per_constraints_t *constraints,
		void *structure, asn_per_outp_t *per_out) {
	extendedBSR_Sizes_r10_63_inherit_TYPE_descriptor(td);
	return td->aper_encoder(td, constraints, structure, per_out);
}

static int
extendedPHR_r10_65_constraint(asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	/* Replace with underlying type checker */
	td->check_constraints = asn_DEF_NativeEnumerated.check_constraints;
	return td->check_constraints(td, sptr, ctfailcb, app_key);
}

/*
 * This type is implemented using NativeEnumerated,
 * so here we adjust the DEF accordingly.
 */
static void
extendedPHR_r10_65_inherit_TYPE_descriptor(asn_TYPE_descriptor_t *td) {
	td->free_struct    = asn_DEF_NativeEnumerated.free_struct;
	td->print_struct   = asn_DEF_NativeEnumerated.print_struct;
	td->check_constraints = asn_DEF_NativeEnumerated.check_constraints;
	td->ber_decoder    = asn_DEF_NativeEnumerated.ber_decoder;
	td->der_encoder    = asn_DEF_NativeEnumerated.der_encoder;
	td->xer_decoder    = asn_DEF_NativeEnumerated.xer_decoder;
	td->xer_encoder    = asn_DEF_NativeEnumerated.xer_encoder;
	td->uper_decoder   = asn_DEF_NativeEnumerated.uper_decoder;
	td->uper_encoder   = asn_DEF_NativeEnumerated.uper_encoder;
	td->aper_decoder   = asn_DEF_NativeEnumerated.aper_decoder;
	td->aper_encoder   = asn_DEF_NativeEnumerated.aper_encoder;
	if(!td->per_constraints)
		td->per_constraints = asn_DEF_NativeEnumerated.per_constraints;
	td->elements       = asn_DEF_NativeEnumerated.elements;
	td->elements_count = asn_DEF_NativeEnumerated.elements_count;
     /* td->specifics      = asn_DEF_NativeEnumerated.specifics;	// Defined explicitly */
}

static void
extendedPHR_r10_65_free(asn_TYPE_descriptor_t *td,
		void *struct_ptr, int contents_only) {
	extendedPHR_r10_65_inherit_TYPE_descriptor(td);
	td->free_struct(td, struct_ptr, contents_only);
}

static int
extendedPHR_r10_65_print(asn_TYPE_descriptor_t *td, const void *struct_ptr,
		int ilevel, asn_app_consume_bytes_f *cb, void *app_key) {
	extendedPHR_r10_65_inherit_TYPE_descriptor(td);
	return td->print_struct(td, struct_ptr, ilevel, cb, app_key);
}

static asn_dec_rval_t
extendedPHR_r10_65_decode_ber(asn_codec_ctx_t *opt_codec_ctx, asn_TYPE_descriptor_t *td,
		void **structure, const void *bufptr, size_t size, int tag_mode) {
	extendedPHR_r10_65_inherit_TYPE_descriptor(td);
	return td->ber_decoder(opt_codec_ctx, td, structure, bufptr, size, tag_mode);
}

static asn_enc_rval_t
extendedPHR_r10_65_encode_der(asn_TYPE_descriptor_t *td,
		void *structure, int tag_mode, ber_tlv_tag_t tag,
		asn_app_consume_bytes_f *cb, void *app_key) {
	extendedPHR_r10_65_inherit_TYPE_descriptor(td);
	return td->der_encoder(td, structure, tag_mode, tag, cb, app_key);
}

static asn_dec_rval_t
extendedPHR_r10_65_decode_xer(asn_codec_ctx_t *opt_codec_ctx, asn_TYPE_descriptor_t *td,
		void **structure, const char *opt_mname, const void *bufptr, size_t size) {
	extendedPHR_r10_65_inherit_TYPE_descriptor(td);
	return td->xer_decoder(opt_codec_ctx, td, structure, opt_mname, bufptr, size);
}

static asn_enc_rval_t
extendedPHR_r10_65_encode_xer(asn_TYPE_descriptor_t *td, void *structure,
		int ilevel, enum xer_encoder_flags_e flags,
		asn_app_consume_bytes_f *cb, void *app_key) {
	extendedPHR_r10_65_inherit_TYPE_descriptor(td);
	return td->xer_encoder(td, structure, ilevel, flags, cb, app_key);
}

static asn_dec_rval_t
extendedPHR_r10_65_decode_uper(asn_codec_ctx_t *opt_codec_ctx, asn_TYPE_descriptor_t *td,
		asn_per_constraints_t *constraints, void **structure, asn_per_data_t *per_data) {
	extendedPHR_r10_65_inherit_TYPE_descriptor(td);
	return td->uper_decoder(opt_codec_ctx, td, constraints, structure, per_data);
}

static asn_enc_rval_t
extendedPHR_r10_65_encode_uper(asn_TYPE_descriptor_t *td,
		asn_per_constraints_t *constraints,
		void *structure, asn_per_outp_t *per_out) {
	extendedPHR_r10_65_inherit_TYPE_descriptor(td);
	return td->uper_encoder(td, constraints, structure, per_out);
}

static asn_dec_rval_t
extendedPHR_r10_65_decode_aper(asn_codec_ctx_t *opt_codec_ctx, asn_TYPE_descriptor_t *td,
		asn_per_constraints_t *constraints, void **structure, asn_per_data_t *per_data) {
	extendedPHR_r10_65_inherit_TYPE_descriptor(td);
	return td->aper_decoder(opt_codec_ctx, td, constraints, structure, per_data);
}

static asn_enc_rval_t
extendedPHR_r10_65_encode_aper(asn_TYPE_descriptor_t *td,
		asn_per_constraints_t *constraints,
		void *structure, asn_per_outp_t *per_out) {
	extendedPHR_r10_65_inherit_TYPE_descriptor(td);
	return td->aper_encoder(td, constraints, structure, per_out);
}

static int
phr_ModeOtherCG_r12_74_constraint(asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	/* Replace with underlying type checker */
	td->check_constraints = asn_DEF_NativeEnumerated.check_constraints;
	return td->check_constraints(td, sptr, ctfailcb, app_key);
}

/*
 * This type is implemented using NativeEnumerated,
 * so here we adjust the DEF accordingly.
 */
static void
phr_ModeOtherCG_r12_74_inherit_TYPE_descriptor(asn_TYPE_descriptor_t *td) {
	td->free_struct    = asn_DEF_NativeEnumerated.free_struct;
	td->print_struct   = asn_DEF_NativeEnumerated.print_struct;
	td->check_constraints = asn_DEF_NativeEnumerated.check_constraints;
	td->ber_decoder    = asn_DEF_NativeEnumerated.ber_decoder;
	td->der_encoder    = asn_DEF_NativeEnumerated.der_encoder;
	td->xer_decoder    = asn_DEF_NativeEnumerated.xer_decoder;
	td->xer_encoder    = asn_DEF_NativeEnumerated.xer_encoder;
	td->uper_decoder   = asn_DEF_NativeEnumerated.uper_decoder;
	td->uper_encoder   = asn_DEF_NativeEnumerated.uper_encoder;
	td->aper_decoder   = asn_DEF_NativeEnumerated.aper_decoder;
	td->aper_encoder   = asn_DEF_NativeEnumerated.aper_encoder;
	if(!td->per_constraints)
		td->per_constraints = asn_DEF_NativeEnumerated.per_constraints;
	td->elements       = asn_DEF_NativeEnumerated.elements;
	td->elements_count = asn_DEF_NativeEnumerated.elements_count;
     /* td->specifics      = asn_DEF_NativeEnumerated.specifics;	// Defined explicitly */
}

static void
phr_ModeOtherCG_r12_74_free(asn_TYPE_descriptor_t *td,
		void *struct_ptr, int contents_only) {
	phr_ModeOtherCG_r12_74_inherit_TYPE_descriptor(td);
	td->free_struct(td, struct_ptr, contents_only);
}

static int
phr_ModeOtherCG_r12_74_print(asn_TYPE_descriptor_t *td, const void *struct_ptr,
		int ilevel, asn_app_consume_bytes_f *cb, void *app_key) {
	phr_ModeOtherCG_r12_74_inherit_TYPE_descriptor(td);
	return td->print_struct(td, struct_ptr, ilevel, cb, app_key);
}

static asn_dec_rval_t
phr_ModeOtherCG_r12_74_decode_ber(asn_codec_ctx_t *opt_codec_ctx, asn_TYPE_descriptor_t *td,
		void **structure, const void *bufptr, size_t size, int tag_mode) {
	phr_ModeOtherCG_r12_74_inherit_TYPE_descriptor(td);
	return td->ber_decoder(opt_codec_ctx, td, structure, bufptr, size, tag_mode);
}

static asn_enc_rval_t
phr_ModeOtherCG_r12_74_encode_der(asn_TYPE_descriptor_t *td,
		void *structure, int tag_mode, ber_tlv_tag_t tag,
		asn_app_consume_bytes_f *cb, void *app_key) {
	phr_ModeOtherCG_r12_74_inherit_TYPE_descriptor(td);
	return td->der_encoder(td, structure, tag_mode, tag, cb, app_key);
}

static asn_dec_rval_t
phr_ModeOtherCG_r12_74_decode_xer(asn_codec_ctx_t *opt_codec_ctx, asn_TYPE_descriptor_t *td,
		void **structure, const char *opt_mname, const void *bufptr, size_t size) {
	phr_ModeOtherCG_r12_74_inherit_TYPE_descriptor(td);
	return td->xer_decoder(opt_codec_ctx, td, structure, opt_mname, bufptr, size);
}

static asn_enc_rval_t
phr_ModeOtherCG_r12_74_encode_xer(asn_TYPE_descriptor_t *td, void *structure,
		int ilevel, enum xer_encoder_flags_e flags,
		asn_app_consume_bytes_f *cb, void *app_key) {
	phr_ModeOtherCG_r12_74_inherit_TYPE_descriptor(td);
	return td->xer_encoder(td, structure, ilevel, flags, cb, app_key);
}

static asn_dec_rval_t
phr_ModeOtherCG_r12_74_decode_uper(asn_codec_ctx_t *opt_codec_ctx, asn_TYPE_descriptor_t *td,
		asn_per_constraints_t *constraints, void **structure, asn_per_data_t *per_data) {
	phr_ModeOtherCG_r12_74_inherit_TYPE_descriptor(td);
	return td->uper_decoder(opt_codec_ctx, td, constraints, structure, per_data);
}

static asn_enc_rval_t
phr_ModeOtherCG_r12_74_encode_uper(asn_TYPE_descriptor_t *td,
		asn_per_constraints_t *constraints,
		void *structure, asn_per_outp_t *per_out) {
	phr_ModeOtherCG_r12_74_inherit_TYPE_descriptor(td);
	return td->uper_encoder(td, constraints, structure, per_out);
}

static asn_dec_rval_t
phr_ModeOtherCG_r12_74_decode_aper(asn_codec_ctx_t *opt_codec_ctx, asn_TYPE_descriptor_t *td,
		asn_per_constraints_t *constraints, void **structure, asn_per_data_t *per_data) {
	phr_ModeOtherCG_r12_74_inherit_TYPE_descriptor(td);
	return td->aper_decoder(opt_codec_ctx, td, constraints, structure, per_data);
}

static asn_enc_rval_t
phr_ModeOtherCG_r12_74_encode_aper(asn_TYPE_descriptor_t *td,
		asn_per_constraints_t *constraints,
		void *structure, asn_per_outp_t *per_out) {
	phr_ModeOtherCG_r12_74_inherit_TYPE_descriptor(td);
	return td->aper_encoder(td, constraints, structure, per_out);
}

static int
logicalChannelSR_ProhibitTimer_r12_80_constraint(asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	/* Replace with underlying type checker */
	td->check_constraints = asn_DEF_NativeEnumerated.check_constraints;
	return td->check_constraints(td, sptr, ctfailcb, app_key);
}

/*
 * This type is implemented using NativeEnumerated,
 * so here we adjust the DEF accordingly.
 */
static void
logicalChannelSR_ProhibitTimer_r12_80_inherit_TYPE_descriptor(asn_TYPE_descriptor_t *td) {
	td->free_struct    = asn_DEF_NativeEnumerated.free_struct;
	td->print_struct   = asn_DEF_NativeEnumerated.print_struct;
	td->check_constraints = asn_DEF_NativeEnumerated.check_constraints;
	td->ber_decoder    = asn_DEF_NativeEnumerated.ber_decoder;
	td->der_encoder    = asn_DEF_NativeEnumerated.der_encoder;
	td->xer_decoder    = asn_DEF_NativeEnumerated.xer_decoder;
	td->xer_encoder    = asn_DEF_NativeEnumerated.xer_encoder;
	td->uper_decoder   = asn_DEF_NativeEnumerated.uper_decoder;
	td->uper_encoder   = asn_DEF_NativeEnumerated.uper_encoder;
	td->aper_decoder   = asn_DEF_NativeEnumerated.aper_decoder;
	td->aper_encoder   = asn_DEF_NativeEnumerated.aper_encoder;
	if(!td->per_constraints)
		td->per_constraints = asn_DEF_NativeEnumerated.per_constraints;
	td->elements       = asn_DEF_NativeEnumerated.elements;
	td->elements_count = asn_DEF_NativeEnumerated.elements_count;
     /* td->specifics      = asn_DEF_NativeEnumerated.specifics;	// Defined explicitly */
}

static void
logicalChannelSR_ProhibitTimer_r12_80_free(asn_TYPE_descriptor_t *td,
		void *struct_ptr, int contents_only) {
	logicalChannelSR_ProhibitTimer_r12_80_inherit_TYPE_descriptor(td);
	td->free_struct(td, struct_ptr, contents_only);
}

static int
logicalChannelSR_ProhibitTimer_r12_80_print(asn_TYPE_descriptor_t *td, const void *struct_ptr,
		int ilevel, asn_app_consume_bytes_f *cb, void *app_key) {
	logicalChannelSR_ProhibitTimer_r12_80_inherit_TYPE_descriptor(td);
	return td->print_struct(td, struct_ptr, ilevel, cb, app_key);
}

static asn_dec_rval_t
logicalChannelSR_ProhibitTimer_r12_80_decode_ber(asn_codec_ctx_t *opt_codec_ctx, asn_TYPE_descriptor_t *td,
		void **structure, const void *bufptr, size_t size, int tag_mode) {
	logicalChannelSR_ProhibitTimer_r12_80_inherit_TYPE_descriptor(td);
	return td->ber_decoder(opt_codec_ctx, td, structure, bufptr, size, tag_mode);
}

static asn_enc_rval_t
logicalChannelSR_ProhibitTimer_r12_80_encode_der(asn_TYPE_descriptor_t *td,
		void *structure, int tag_mode, ber_tlv_tag_t tag,
		asn_app_consume_bytes_f *cb, void *app_key) {
	logicalChannelSR_ProhibitTimer_r12_80_inherit_TYPE_descriptor(td);
	return td->der_encoder(td, structure, tag_mode, tag, cb, app_key);
}

static asn_dec_rval_t
logicalChannelSR_ProhibitTimer_r12_80_decode_xer(asn_codec_ctx_t *opt_codec_ctx, asn_TYPE_descriptor_t *td,
		void **structure, const char *opt_mname, const void *bufptr, size_t size) {
	logicalChannelSR_ProhibitTimer_r12_80_inherit_TYPE_descriptor(td);
	return td->xer_decoder(opt_codec_ctx, td, structure, opt_mname, bufptr, size);
}

static asn_enc_rval_t
logicalChannelSR_ProhibitTimer_r12_80_encode_xer(asn_TYPE_descriptor_t *td, void *structure,
		int ilevel, enum xer_encoder_flags_e flags,
		asn_app_consume_bytes_f *cb, void *app_key) {
	logicalChannelSR_ProhibitTimer_r12_80_inherit_TYPE_descriptor(td);
	return td->xer_encoder(td, structure, ilevel, flags, cb, app_key);
}

static asn_dec_rval_t
logicalChannelSR_ProhibitTimer_r12_80_decode_uper(asn_codec_ctx_t *opt_codec_ctx, asn_TYPE_descriptor_t *td,
		asn_per_constraints_t *constraints, void **structure, asn_per_data_t *per_data) {
	logicalChannelSR_ProhibitTimer_r12_80_inherit_TYPE_descriptor(td);
	return td->uper_decoder(opt_codec_ctx, td, constraints, structure, per_data);
}

static asn_enc_rval_t
logicalChannelSR_ProhibitTimer_r12_80_encode_uper(asn_TYPE_descriptor_t *td,
		asn_per_constraints_t *constraints,
		void *structure, asn_per_outp_t *per_out) {
	logicalChannelSR_ProhibitTimer_r12_80_inherit_TYPE_descriptor(td);
	return td->uper_encoder(td, constraints, structure, per_out);
}

static asn_dec_rval_t
logicalChannelSR_ProhibitTimer_r12_80_decode_aper(asn_codec_ctx_t *opt_codec_ctx, asn_TYPE_descriptor_t *td,
		asn_per_constraints_t *constraints, void **structure, asn_per_data_t *per_data) {
	logicalChannelSR_ProhibitTimer_r12_80_inherit_TYPE_descriptor(td);
	return td->aper_decoder(opt_codec_ctx, td, constraints, structure, per_data);
}

static asn_enc_rval_t
logicalChannelSR_ProhibitTimer_r12_80_encode_aper(asn_TYPE_descriptor_t *td,
		asn_per_constraints_t *constraints,
		void *structure, asn_per_outp_t *per_out) {
	logicalChannelSR_ProhibitTimer_r12_80_inherit_TYPE_descriptor(td);
	return td->aper_encoder(td, constraints, structure, per_out);
}

static int
memb_sf5120_constraint_93(asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	long long value;
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	value = *(const long long *)sptr;
	
	if((value >= 0LL && value <= 1LL)) {
		/* Constraint check succeeded */
		return 0;
	} else {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

static int
memb_sf10240_constraint_93(asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	long long value;
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	value = *(const long long *)sptr;
	
	if((value >= 0LL && value <= 3LL)) {
		/* Constraint check succeeded */
		return 0;
	} else {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

static int
memb_sr_ProhibitTimer_r9_constraint_1(asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	long long value;
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	value = *(const long long *)sptr;
	
	if((value >= 0LL && value <= 7LL)) {
		/* Constraint check succeeded */
		return 0;
	} else {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

static asn_per_constraints_t asn_PER_type_maxHARQ_Tx_constr_3 GCC_NOTUSED = {
	{ APC_CONSTRAINED,	 4,  4,  0,  15 }	/* (0..15) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_per_constraints_t asn_PER_type_periodicPHR_Timer_constr_28 GCC_NOTUSED = {
	{ APC_CONSTRAINED,	 3,  3,  0,  7 }	/* (0..7) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_per_constraints_t asn_PER_type_prohibitPHR_Timer_constr_37 GCC_NOTUSED = {
	{ APC_CONSTRAINED,	 3,  3,  0,  7 }	/* (0..7) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_per_constraints_t asn_PER_type_dl_PathlossChange_constr_46 GCC_NOTUSED = {
	{ APC_CONSTRAINED,	 2,  2,  0,  3 }	/* (0..3) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_per_constraints_t asn_PER_type_phr_Config_constr_25 GCC_NOTUSED = {
	{ APC_CONSTRAINED,	 1,  1,  0,  1 }	/* (0..1) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_per_constraints_t asn_PER_type_sCellDeactivationTimer_r10_constr_54 GCC_NOTUSED = {
	{ APC_CONSTRAINED,	 3,  3,  0,  7 }	/* (0..7) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_per_constraints_t asn_PER_type_extendedBSR_Sizes_r10_constr_63 GCC_NOTUSED = {
	{ APC_CONSTRAINED,	 0,  0,  0,  0 }	/* (0..0) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_per_constraints_t asn_PER_type_extendedPHR_r10_constr_65 GCC_NOTUSED = {
	{ APC_CONSTRAINED,	 0,  0,  0,  0 }	/* (0..0) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_per_constraints_t asn_PER_type_phr_ModeOtherCG_r12_constr_74 GCC_NOTUSED = {
	{ APC_CONSTRAINED,	 1,  1,  0,  1 }	/* (0..1) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_per_constraints_t asn_PER_type_dualConnectivityPHR_constr_71 GCC_NOTUSED = {
	{ APC_CONSTRAINED,	 1,  1,  0,  1 }	/* (0..1) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_per_constraints_t asn_PER_type_logicalChannelSR_ProhibitTimer_r12_constr_80 GCC_NOTUSED = {
	{ APC_CONSTRAINED,	 3,  3,  0,  7 }	/* (0..7) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_per_constraints_t asn_PER_type_logicalChannelSR_Config_r12_constr_77 GCC_NOTUSED = {
	{ APC_CONSTRAINED,	 1,  1,  0,  1 }	/* (0..1) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_per_constraints_t asn_PER_memb_sf5120_constr_94 GCC_NOTUSED = {
	{ APC_CONSTRAINED,	 1,  1,  0,  1 }	/* (0..1) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_per_constraints_t asn_PER_memb_sf10240_constr_95 GCC_NOTUSED = {
	{ APC_CONSTRAINED,	 2,  2,  0,  3 }	/* (0..3) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_per_constraints_t asn_PER_type_setup_constr_93 GCC_NOTUSED = {
	{ APC_CONSTRAINED,	 1,  1,  0,  1 }	/* (0..1) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_per_constraints_t asn_PER_type_eDRX_Config_CycleStartOffset_r13_constr_91 GCC_NOTUSED = {
	{ APC_CONSTRAINED,	 1,  1,  0,  1 }	/* (0..1) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_per_constraints_t asn_PER_type_drx_Config_r13_constr_96 GCC_NOTUSED = {
	{ APC_CONSTRAINED,	 1,  1,  0,  1 }	/* (0..1) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_per_constraints_t asn_PER_memb_sr_ProhibitTimer_r9_constr_52 GCC_NOTUSED = {
	{ APC_CONSTRAINED,	 3,  3,  0,  7 }	/* (0..7) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static const asn_INTEGER_enum_map_t asn_MAP_maxHARQ_Tx_value2enum_3[] = {
	{ 0,	2,	"n1" },
	{ 1,	2,	"n2" },
	{ 2,	2,	"n3" },
	{ 3,	2,	"n4" },
	{ 4,	2,	"n5" },
	{ 5,	2,	"n6" },
	{ 6,	2,	"n7" },
	{ 7,	2,	"n8" },
	{ 8,	3,	"n10" },
	{ 9,	3,	"n12" },
	{ 10,	3,	"n16" },
	{ 11,	3,	"n20" },
	{ 12,	3,	"n24" },
	{ 13,	3,	"n28" },
	{ 14,	6,	"spare2" },
	{ 15,	6,	"spare1" }
};
static const unsigned int asn_MAP_maxHARQ_Tx_enum2value_3[] = {
	0,	/* n1(0) */
	8,	/* n10(8) */
	9,	/* n12(9) */
	10,	/* n16(10) */
	1,	/* n2(1) */
	11,	/* n20(11) */
	12,	/* n24(12) */
	13,	/* n28(13) */
	2,	/* n3(2) */
	3,	/* n4(3) */
	4,	/* n5(4) */
	5,	/* n6(5) */
	6,	/* n7(6) */
	7,	/* n8(7) */
	15,	/* spare1(15) */
	14	/* spare2(14) */
};
static const asn_INTEGER_specifics_t asn_SPC_maxHARQ_Tx_specs_3 = {
	asn_MAP_maxHARQ_Tx_value2enum_3,	/* "tag" => N; sorted by tag */
	asn_MAP_maxHARQ_Tx_enum2value_3,	/* N => "tag"; sorted by N */
	16,	/* Number of elements in the maps */
	0,	/* Enumeration is not extensible */
	1,	/* Strict enumeration */
	0,	/* Native long size */
	0
};
static const ber_tlv_tag_t asn_DEF_maxHARQ_Tx_tags_3[] = {
	(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (10 << 2))
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_maxHARQ_Tx_3 = {
	"maxHARQ-Tx",
	"maxHARQ-Tx",
	maxHARQ_Tx_3_free,
	maxHARQ_Tx_3_print,
	maxHARQ_Tx_3_constraint,
	maxHARQ_Tx_3_decode_ber,
	maxHARQ_Tx_3_encode_der,
	maxHARQ_Tx_3_decode_xer,
	maxHARQ_Tx_3_encode_xer,
	maxHARQ_Tx_3_decode_uper,
	maxHARQ_Tx_3_encode_uper,
	maxHARQ_Tx_3_decode_aper,
	maxHARQ_Tx_3_encode_aper,
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_maxHARQ_Tx_tags_3,
	sizeof(asn_DEF_maxHARQ_Tx_tags_3)
		/sizeof(asn_DEF_maxHARQ_Tx_tags_3[0]) - 1, /* 1 */
	asn_DEF_maxHARQ_Tx_tags_3,	/* Same as above */
	sizeof(asn_DEF_maxHARQ_Tx_tags_3)
		/sizeof(asn_DEF_maxHARQ_Tx_tags_3[0]), /* 2 */
	&asn_PER_type_maxHARQ_Tx_constr_3,
	0, 0,	/* Defined elsewhere */
	&asn_SPC_maxHARQ_Tx_specs_3	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_ul_SCH_Config_2[] = {
	{ ATF_POINTER, 2, offsetof(struct MAC_MainConfig__ul_SCH_Config, maxHARQ_Tx),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_maxHARQ_Tx_3,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"maxHARQ-Tx"
		},
	{ ATF_POINTER, 1, offsetof(struct MAC_MainConfig__ul_SCH_Config, periodicBSR_Timer),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_PeriodicBSR_Timer_r12,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"periodicBSR-Timer"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct MAC_MainConfig__ul_SCH_Config, retxBSR_Timer),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_RetxBSR_Timer_r12,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"retxBSR-Timer"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct MAC_MainConfig__ul_SCH_Config, ttiBundling),
		(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_BOOLEAN,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"ttiBundling"
		},
};
static const int asn_MAP_ul_SCH_Config_oms_2[] = { 0, 1 };
static const ber_tlv_tag_t asn_DEF_ul_SCH_Config_tags_2[] = {
	(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_ul_SCH_Config_tag2el_2[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* maxHARQ-Tx */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* periodicBSR-Timer */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 }, /* retxBSR-Timer */
    { (ASN_TAG_CLASS_CONTEXT | (3 << 2)), 3, 0, 0 } /* ttiBundling */
};
static asn_SEQUENCE_specifics_t asn_SPC_ul_SCH_Config_specs_2 = {
	sizeof(struct MAC_MainConfig__ul_SCH_Config),
	offsetof(struct MAC_MainConfig__ul_SCH_Config, _asn_ctx),
	asn_MAP_ul_SCH_Config_tag2el_2,
	4,	/* Count of tags in the map */
	asn_MAP_ul_SCH_Config_oms_2,	/* Optional members */
	2, 0,	/* Root/Additions */
	-1,	/* Start extensions */
	-1	/* Stop extensions */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_ul_SCH_Config_2 = {
	"ul-SCH-Config",
	"ul-SCH-Config",
	SEQUENCE_free,
	SEQUENCE_print,
	SEQUENCE_constraint,
	SEQUENCE_decode_ber,
	SEQUENCE_encode_der,
	SEQUENCE_decode_xer,
	SEQUENCE_encode_xer,
	SEQUENCE_decode_uper,
	SEQUENCE_encode_uper,
	SEQUENCE_decode_aper,
	SEQUENCE_encode_aper,
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_ul_SCH_Config_tags_2,
	sizeof(asn_DEF_ul_SCH_Config_tags_2)
		/sizeof(asn_DEF_ul_SCH_Config_tags_2[0]) - 1, /* 1 */
	asn_DEF_ul_SCH_Config_tags_2,	/* Same as above */
	sizeof(asn_DEF_ul_SCH_Config_tags_2)
		/sizeof(asn_DEF_ul_SCH_Config_tags_2[0]), /* 2 */
	0,	/* No PER visible constraints */
	asn_MBR_ul_SCH_Config_2,
	4,	/* Elements count */
	&asn_SPC_ul_SCH_Config_specs_2	/* Additional specs */
};

static const asn_INTEGER_enum_map_t asn_MAP_periodicPHR_Timer_value2enum_28[] = {
	{ 0,	4,	"sf10" },
	{ 1,	4,	"sf20" },
	{ 2,	4,	"sf50" },
	{ 3,	5,	"sf100" },
	{ 4,	5,	"sf200" },
	{ 5,	5,	"sf500" },
	{ 6,	6,	"sf1000" },
	{ 7,	8,	"infinity" }
};
static const unsigned int asn_MAP_periodicPHR_Timer_enum2value_28[] = {
	7,	/* infinity(7) */
	0,	/* sf10(0) */
	3,	/* sf100(3) */
	6,	/* sf1000(6) */
	1,	/* sf20(1) */
	4,	/* sf200(4) */
	2,	/* sf50(2) */
	5	/* sf500(5) */
};
static const asn_INTEGER_specifics_t asn_SPC_periodicPHR_Timer_specs_28 = {
	asn_MAP_periodicPHR_Timer_value2enum_28,	/* "tag" => N; sorted by tag */
	asn_MAP_periodicPHR_Timer_enum2value_28,	/* N => "tag"; sorted by N */
	8,	/* Number of elements in the maps */
	0,	/* Enumeration is not extensible */
	1,	/* Strict enumeration */
	0,	/* Native long size */
	0
};
static const ber_tlv_tag_t asn_DEF_periodicPHR_Timer_tags_28[] = {
	(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (10 << 2))
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_periodicPHR_Timer_28 = {
	"periodicPHR-Timer",
	"periodicPHR-Timer",
	periodicPHR_Timer_28_free,
	periodicPHR_Timer_28_print,
	periodicPHR_Timer_28_constraint,
	periodicPHR_Timer_28_decode_ber,
	periodicPHR_Timer_28_encode_der,
	periodicPHR_Timer_28_decode_xer,
	periodicPHR_Timer_28_encode_xer,
	periodicPHR_Timer_28_decode_uper,
	periodicPHR_Timer_28_encode_uper,
	periodicPHR_Timer_28_decode_aper,
	periodicPHR_Timer_28_encode_aper,
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_periodicPHR_Timer_tags_28,
	sizeof(asn_DEF_periodicPHR_Timer_tags_28)
		/sizeof(asn_DEF_periodicPHR_Timer_tags_28[0]) - 1, /* 1 */
	asn_DEF_periodicPHR_Timer_tags_28,	/* Same as above */
	sizeof(asn_DEF_periodicPHR_Timer_tags_28)
		/sizeof(asn_DEF_periodicPHR_Timer_tags_28[0]), /* 2 */
	&asn_PER_type_periodicPHR_Timer_constr_28,
	0, 0,	/* Defined elsewhere */
	&asn_SPC_periodicPHR_Timer_specs_28	/* Additional specs */
};

static const asn_INTEGER_enum_map_t asn_MAP_prohibitPHR_Timer_value2enum_37[] = {
	{ 0,	3,	"sf0" },
	{ 1,	4,	"sf10" },
	{ 2,	4,	"sf20" },
	{ 3,	4,	"sf50" },
	{ 4,	5,	"sf100" },
	{ 5,	5,	"sf200" },
	{ 6,	5,	"sf500" },
	{ 7,	6,	"sf1000" }
};
static const unsigned int asn_MAP_prohibitPHR_Timer_enum2value_37[] = {
	0,	/* sf0(0) */
	1,	/* sf10(1) */
	4,	/* sf100(4) */
	7,	/* sf1000(7) */
	2,	/* sf20(2) */
	5,	/* sf200(5) */
	3,	/* sf50(3) */
	6	/* sf500(6) */
};
static const asn_INTEGER_specifics_t asn_SPC_prohibitPHR_Timer_specs_37 = {
	asn_MAP_prohibitPHR_Timer_value2enum_37,	/* "tag" => N; sorted by tag */
	asn_MAP_prohibitPHR_Timer_enum2value_37,	/* N => "tag"; sorted by N */
	8,	/* Number of elements in the maps */
	0,	/* Enumeration is not extensible */
	1,	/* Strict enumeration */
	0,	/* Native long size */
	0
};
static const ber_tlv_tag_t asn_DEF_prohibitPHR_Timer_tags_37[] = {
	(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (10 << 2))
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_prohibitPHR_Timer_37 = {
	"prohibitPHR-Timer",
	"prohibitPHR-Timer",
	prohibitPHR_Timer_37_free,
	prohibitPHR_Timer_37_print,
	prohibitPHR_Timer_37_constraint,
	prohibitPHR_Timer_37_decode_ber,
	prohibitPHR_Timer_37_encode_der,
	prohibitPHR_Timer_37_decode_xer,
	prohibitPHR_Timer_37_encode_xer,
	prohibitPHR_Timer_37_decode_uper,
	prohibitPHR_Timer_37_encode_uper,
	prohibitPHR_Timer_37_decode_aper,
	prohibitPHR_Timer_37_encode_aper,
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_prohibitPHR_Timer_tags_37,
	sizeof(asn_DEF_prohibitPHR_Timer_tags_37)
		/sizeof(asn_DEF_prohibitPHR_Timer_tags_37[0]) - 1, /* 1 */
	asn_DEF_prohibitPHR_Timer_tags_37,	/* Same as above */
	sizeof(asn_DEF_prohibitPHR_Timer_tags_37)
		/sizeof(asn_DEF_prohibitPHR_Timer_tags_37[0]), /* 2 */
	&asn_PER_type_prohibitPHR_Timer_constr_37,
	0, 0,	/* Defined elsewhere */
	&asn_SPC_prohibitPHR_Timer_specs_37	/* Additional specs */
};

static const asn_INTEGER_enum_map_t asn_MAP_dl_PathlossChange_value2enum_46[] = {
	{ 0,	3,	"dB1" },
	{ 1,	3,	"dB3" },
	{ 2,	3,	"dB6" },
	{ 3,	8,	"infinity" }
};
static const unsigned int asn_MAP_dl_PathlossChange_enum2value_46[] = {
	0,	/* dB1(0) */
	1,	/* dB3(1) */
	2,	/* dB6(2) */
	3	/* infinity(3) */
};
static const asn_INTEGER_specifics_t asn_SPC_dl_PathlossChange_specs_46 = {
	asn_MAP_dl_PathlossChange_value2enum_46,	/* "tag" => N; sorted by tag */
	asn_MAP_dl_PathlossChange_enum2value_46,	/* N => "tag"; sorted by N */
	4,	/* Number of elements in the maps */
	0,	/* Enumeration is not extensible */
	1,	/* Strict enumeration */
	0,	/* Native long size */
	0
};
static const ber_tlv_tag_t asn_DEF_dl_PathlossChange_tags_46[] = {
	(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (10 << 2))
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_dl_PathlossChange_46 = {
	"dl-PathlossChange",
	"dl-PathlossChange",
	dl_PathlossChange_46_free,
	dl_PathlossChange_46_print,
	dl_PathlossChange_46_constraint,
	dl_PathlossChange_46_decode_ber,
	dl_PathlossChange_46_encode_der,
	dl_PathlossChange_46_decode_xer,
	dl_PathlossChange_46_encode_xer,
	dl_PathlossChange_46_decode_uper,
	dl_PathlossChange_46_encode_uper,
	dl_PathlossChange_46_decode_aper,
	dl_PathlossChange_46_encode_aper,
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_dl_PathlossChange_tags_46,
	sizeof(asn_DEF_dl_PathlossChange_tags_46)
		/sizeof(asn_DEF_dl_PathlossChange_tags_46[0]) - 1, /* 1 */
	asn_DEF_dl_PathlossChange_tags_46,	/* Same as above */
	sizeof(asn_DEF_dl_PathlossChange_tags_46)
		/sizeof(asn_DEF_dl_PathlossChange_tags_46[0]), /* 2 */
	&asn_PER_type_dl_PathlossChange_constr_46,
	0, 0,	/* Defined elsewhere */
	&asn_SPC_dl_PathlossChange_specs_46	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_setup_27[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct MAC_MainConfig__phr_Config__setup, periodicPHR_Timer),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_periodicPHR_Timer_28,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"periodicPHR-Timer"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct MAC_MainConfig__phr_Config__setup, prohibitPHR_Timer),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_prohibitPHR_Timer_37,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"prohibitPHR-Timer"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct MAC_MainConfig__phr_Config__setup, dl_PathlossChange),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_dl_PathlossChange_46,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"dl-PathlossChange"
		},
};
static const ber_tlv_tag_t asn_DEF_setup_tags_27[] = {
	(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_setup_tag2el_27[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* periodicPHR-Timer */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* prohibitPHR-Timer */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 } /* dl-PathlossChange */
};
static asn_SEQUENCE_specifics_t asn_SPC_setup_specs_27 = {
	sizeof(struct MAC_MainConfig__phr_Config__setup),
	offsetof(struct MAC_MainConfig__phr_Config__setup, _asn_ctx),
	asn_MAP_setup_tag2el_27,
	3,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* Start extensions */
	-1	/* Stop extensions */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_setup_27 = {
	"setup",
	"setup",
	SEQUENCE_free,
	SEQUENCE_print,
	SEQUENCE_constraint,
	SEQUENCE_decode_ber,
	SEQUENCE_encode_der,
	SEQUENCE_decode_xer,
	SEQUENCE_encode_xer,
	SEQUENCE_decode_uper,
	SEQUENCE_encode_uper,
	SEQUENCE_decode_aper,
	SEQUENCE_encode_aper,
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_setup_tags_27,
	sizeof(asn_DEF_setup_tags_27)
		/sizeof(asn_DEF_setup_tags_27[0]) - 1, /* 1 */
	asn_DEF_setup_tags_27,	/* Same as above */
	sizeof(asn_DEF_setup_tags_27)
		/sizeof(asn_DEF_setup_tags_27[0]), /* 2 */
	0,	/* No PER visible constraints */
	asn_MBR_setup_27,
	3,	/* Elements count */
	&asn_SPC_setup_specs_27	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_phr_Config_25[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct MAC_MainConfig__phr_Config, choice.release),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NULL,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"release"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct MAC_MainConfig__phr_Config, choice.setup),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		0,
		&asn_DEF_setup_27,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"setup"
		},
};
static const asn_TYPE_tag2member_t asn_MAP_phr_Config_tag2el_25[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* release */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 } /* setup */
};
static asn_CHOICE_specifics_t asn_SPC_phr_Config_specs_25 = {
	sizeof(struct MAC_MainConfig__phr_Config),
	offsetof(struct MAC_MainConfig__phr_Config, _asn_ctx),
	offsetof(struct MAC_MainConfig__phr_Config, present),
	sizeof(((struct MAC_MainConfig__phr_Config *)0)->present),
	asn_MAP_phr_Config_tag2el_25,
	2,	/* Count of tags in the map */
	0,
	-1	/* Extensions start */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_phr_Config_25 = {
	"phr-Config",
	"phr-Config",
	CHOICE_free,
	CHOICE_print,
	CHOICE_constraint,
	CHOICE_decode_ber,
	CHOICE_encode_der,
	CHOICE_decode_xer,
	CHOICE_encode_xer,
	CHOICE_decode_uper,
	CHOICE_encode_uper,
	CHOICE_decode_aper,
	CHOICE_encode_aper,
	CHOICE_outmost_tag,
	0,	/* No effective tags (pointer) */
	0,	/* No effective tags (count) */
	0,	/* No tags (pointer) */
	0,	/* No tags (count) */
	&asn_PER_type_phr_Config_constr_25,
	asn_MBR_phr_Config_25,
	2,	/* Elements count */
	&asn_SPC_phr_Config_specs_25	/* Additional specs */
};

static const asn_INTEGER_enum_map_t asn_MAP_sCellDeactivationTimer_r10_value2enum_54[] = {
	{ 0,	3,	"rf2" },
	{ 1,	3,	"rf4" },
	{ 2,	3,	"rf8" },
	{ 3,	4,	"rf16" },
	{ 4,	4,	"rf32" },
	{ 5,	4,	"rf64" },
	{ 6,	5,	"rf128" },
	{ 7,	5,	"spare" }
};
static const unsigned int asn_MAP_sCellDeactivationTimer_r10_enum2value_54[] = {
	6,	/* rf128(6) */
	3,	/* rf16(3) */
	0,	/* rf2(0) */
	4,	/* rf32(4) */
	1,	/* rf4(1) */
	5,	/* rf64(5) */
	2,	/* rf8(2) */
	7	/* spare(7) */
};
static const asn_INTEGER_specifics_t asn_SPC_sCellDeactivationTimer_r10_specs_54 = {
	asn_MAP_sCellDeactivationTimer_r10_value2enum_54,	/* "tag" => N; sorted by tag */
	asn_MAP_sCellDeactivationTimer_r10_enum2value_54,	/* N => "tag"; sorted by N */
	8,	/* Number of elements in the maps */
	0,	/* Enumeration is not extensible */
	1,	/* Strict enumeration */
	0,	/* Native long size */
	0
};
static const ber_tlv_tag_t asn_DEF_sCellDeactivationTimer_r10_tags_54[] = {
	(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (10 << 2))
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_sCellDeactivationTimer_r10_54 = {
	"sCellDeactivationTimer-r10",
	"sCellDeactivationTimer-r10",
	sCellDeactivationTimer_r10_54_free,
	sCellDeactivationTimer_r10_54_print,
	sCellDeactivationTimer_r10_54_constraint,
	sCellDeactivationTimer_r10_54_decode_ber,
	sCellDeactivationTimer_r10_54_encode_der,
	sCellDeactivationTimer_r10_54_decode_xer,
	sCellDeactivationTimer_r10_54_encode_xer,
	sCellDeactivationTimer_r10_54_decode_uper,
	sCellDeactivationTimer_r10_54_encode_uper,
	sCellDeactivationTimer_r10_54_decode_aper,
	sCellDeactivationTimer_r10_54_encode_aper,
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_sCellDeactivationTimer_r10_tags_54,
	sizeof(asn_DEF_sCellDeactivationTimer_r10_tags_54)
		/sizeof(asn_DEF_sCellDeactivationTimer_r10_tags_54[0]) - 1, /* 1 */
	asn_DEF_sCellDeactivationTimer_r10_tags_54,	/* Same as above */
	sizeof(asn_DEF_sCellDeactivationTimer_r10_tags_54)
		/sizeof(asn_DEF_sCellDeactivationTimer_r10_tags_54[0]), /* 2 */
	&asn_PER_type_sCellDeactivationTimer_r10_constr_54,
	0, 0,	/* Defined elsewhere */
	&asn_SPC_sCellDeactivationTimer_r10_specs_54	/* Additional specs */
};

static const asn_INTEGER_enum_map_t asn_MAP_extendedBSR_Sizes_r10_value2enum_63[] = {
	{ 0,	5,	"setup" }
};
static const unsigned int asn_MAP_extendedBSR_Sizes_r10_enum2value_63[] = {
	0	/* setup(0) */
};
static const asn_INTEGER_specifics_t asn_SPC_extendedBSR_Sizes_r10_specs_63 = {
	asn_MAP_extendedBSR_Sizes_r10_value2enum_63,	/* "tag" => N; sorted by tag */
	asn_MAP_extendedBSR_Sizes_r10_enum2value_63,	/* N => "tag"; sorted by N */
	1,	/* Number of elements in the maps */
	0,	/* Enumeration is not extensible */
	1,	/* Strict enumeration */
	0,	/* Native long size */
	0
};
static const ber_tlv_tag_t asn_DEF_extendedBSR_Sizes_r10_tags_63[] = {
	(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (10 << 2))
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_extendedBSR_Sizes_r10_63 = {
	"extendedBSR-Sizes-r10",
	"extendedBSR-Sizes-r10",
	extendedBSR_Sizes_r10_63_free,
	extendedBSR_Sizes_r10_63_print,
	extendedBSR_Sizes_r10_63_constraint,
	extendedBSR_Sizes_r10_63_decode_ber,
	extendedBSR_Sizes_r10_63_encode_der,
	extendedBSR_Sizes_r10_63_decode_xer,
	extendedBSR_Sizes_r10_63_encode_xer,
	extendedBSR_Sizes_r10_63_decode_uper,
	extendedBSR_Sizes_r10_63_encode_uper,
	extendedBSR_Sizes_r10_63_decode_aper,
	extendedBSR_Sizes_r10_63_encode_aper,
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_extendedBSR_Sizes_r10_tags_63,
	sizeof(asn_DEF_extendedBSR_Sizes_r10_tags_63)
		/sizeof(asn_DEF_extendedBSR_Sizes_r10_tags_63[0]) - 1, /* 1 */
	asn_DEF_extendedBSR_Sizes_r10_tags_63,	/* Same as above */
	sizeof(asn_DEF_extendedBSR_Sizes_r10_tags_63)
		/sizeof(asn_DEF_extendedBSR_Sizes_r10_tags_63[0]), /* 2 */
	&asn_PER_type_extendedBSR_Sizes_r10_constr_63,
	0, 0,	/* Defined elsewhere */
	&asn_SPC_extendedBSR_Sizes_r10_specs_63	/* Additional specs */
};

static const asn_INTEGER_enum_map_t asn_MAP_extendedPHR_r10_value2enum_65[] = {
	{ 0,	5,	"setup" }
};
static const unsigned int asn_MAP_extendedPHR_r10_enum2value_65[] = {
	0	/* setup(0) */
};
static const asn_INTEGER_specifics_t asn_SPC_extendedPHR_r10_specs_65 = {
	asn_MAP_extendedPHR_r10_value2enum_65,	/* "tag" => N; sorted by tag */
	asn_MAP_extendedPHR_r10_enum2value_65,	/* N => "tag"; sorted by N */
	1,	/* Number of elements in the maps */
	0,	/* Enumeration is not extensible */
	1,	/* Strict enumeration */
	0,	/* Native long size */
	0
};
static const ber_tlv_tag_t asn_DEF_extendedPHR_r10_tags_65[] = {
	(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (10 << 2))
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_extendedPHR_r10_65 = {
	"extendedPHR-r10",
	"extendedPHR-r10",
	extendedPHR_r10_65_free,
	extendedPHR_r10_65_print,
	extendedPHR_r10_65_constraint,
	extendedPHR_r10_65_decode_ber,
	extendedPHR_r10_65_encode_der,
	extendedPHR_r10_65_decode_xer,
	extendedPHR_r10_65_encode_xer,
	extendedPHR_r10_65_decode_uper,
	extendedPHR_r10_65_encode_uper,
	extendedPHR_r10_65_decode_aper,
	extendedPHR_r10_65_encode_aper,
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_extendedPHR_r10_tags_65,
	sizeof(asn_DEF_extendedPHR_r10_tags_65)
		/sizeof(asn_DEF_extendedPHR_r10_tags_65[0]) - 1, /* 1 */
	asn_DEF_extendedPHR_r10_tags_65,	/* Same as above */
	sizeof(asn_DEF_extendedPHR_r10_tags_65)
		/sizeof(asn_DEF_extendedPHR_r10_tags_65[0]), /* 2 */
	&asn_PER_type_extendedPHR_r10_constr_65,
	0, 0,	/* Defined elsewhere */
	&asn_SPC_extendedPHR_r10_specs_65	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_mac_MainConfig_v1020_53[] = {
	{ ATF_POINTER, 3, offsetof(struct MAC_MainConfig__mac_MainConfig_v1020, sCellDeactivationTimer_r10),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_sCellDeactivationTimer_r10_54,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"sCellDeactivationTimer-r10"
		},
	{ ATF_POINTER, 2, offsetof(struct MAC_MainConfig__mac_MainConfig_v1020, extendedBSR_Sizes_r10),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_extendedBSR_Sizes_r10_63,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"extendedBSR-Sizes-r10"
		},
	{ ATF_POINTER, 1, offsetof(struct MAC_MainConfig__mac_MainConfig_v1020, extendedPHR_r10),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_extendedPHR_r10_65,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"extendedPHR-r10"
		},
};
static const int asn_MAP_mac_MainConfig_v1020_oms_53[] = { 0, 1, 2 };
static const ber_tlv_tag_t asn_DEF_mac_MainConfig_v1020_tags_53[] = {
	(ASN_TAG_CLASS_CONTEXT | (5 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_mac_MainConfig_v1020_tag2el_53[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* sCellDeactivationTimer-r10 */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* extendedBSR-Sizes-r10 */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 } /* extendedPHR-r10 */
};
static asn_SEQUENCE_specifics_t asn_SPC_mac_MainConfig_v1020_specs_53 = {
	sizeof(struct MAC_MainConfig__mac_MainConfig_v1020),
	offsetof(struct MAC_MainConfig__mac_MainConfig_v1020, _asn_ctx),
	asn_MAP_mac_MainConfig_v1020_tag2el_53,
	3,	/* Count of tags in the map */
	asn_MAP_mac_MainConfig_v1020_oms_53,	/* Optional members */
	3, 0,	/* Root/Additions */
	-1,	/* Start extensions */
	-1	/* Stop extensions */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_mac_MainConfig_v1020_53 = {
	"mac-MainConfig-v1020",
	"mac-MainConfig-v1020",
	SEQUENCE_free,
	SEQUENCE_print,
	SEQUENCE_constraint,
	SEQUENCE_decode_ber,
	SEQUENCE_encode_der,
	SEQUENCE_decode_xer,
	SEQUENCE_encode_xer,
	SEQUENCE_decode_uper,
	SEQUENCE_encode_uper,
	SEQUENCE_decode_aper,
	SEQUENCE_encode_aper,
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_mac_MainConfig_v1020_tags_53,
	sizeof(asn_DEF_mac_MainConfig_v1020_tags_53)
		/sizeof(asn_DEF_mac_MainConfig_v1020_tags_53[0]) - 1, /* 1 */
	asn_DEF_mac_MainConfig_v1020_tags_53,	/* Same as above */
	sizeof(asn_DEF_mac_MainConfig_v1020_tags_53)
		/sizeof(asn_DEF_mac_MainConfig_v1020_tags_53[0]), /* 2 */
	0,	/* No PER visible constraints */
	asn_MBR_mac_MainConfig_v1020_53,
	3,	/* Elements count */
	&asn_SPC_mac_MainConfig_v1020_specs_53	/* Additional specs */
};

static const asn_INTEGER_enum_map_t asn_MAP_phr_ModeOtherCG_r12_value2enum_74[] = {
	{ 0,	4,	"real" },
	{ 1,	7,	"virtual" }
};
static const unsigned int asn_MAP_phr_ModeOtherCG_r12_enum2value_74[] = {
	0,	/* real(0) */
	1	/* virtual(1) */
};
static const asn_INTEGER_specifics_t asn_SPC_phr_ModeOtherCG_r12_specs_74 = {
	asn_MAP_phr_ModeOtherCG_r12_value2enum_74,	/* "tag" => N; sorted by tag */
	asn_MAP_phr_ModeOtherCG_r12_enum2value_74,	/* N => "tag"; sorted by N */
	2,	/* Number of elements in the maps */
	0,	/* Enumeration is not extensible */
	1,	/* Strict enumeration */
	0,	/* Native long size */
	0
};
static const ber_tlv_tag_t asn_DEF_phr_ModeOtherCG_r12_tags_74[] = {
	(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (10 << 2))
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_phr_ModeOtherCG_r12_74 = {
	"phr-ModeOtherCG-r12",
	"phr-ModeOtherCG-r12",
	phr_ModeOtherCG_r12_74_free,
	phr_ModeOtherCG_r12_74_print,
	phr_ModeOtherCG_r12_74_constraint,
	phr_ModeOtherCG_r12_74_decode_ber,
	phr_ModeOtherCG_r12_74_encode_der,
	phr_ModeOtherCG_r12_74_decode_xer,
	phr_ModeOtherCG_r12_74_encode_xer,
	phr_ModeOtherCG_r12_74_decode_uper,
	phr_ModeOtherCG_r12_74_encode_uper,
	phr_ModeOtherCG_r12_74_decode_aper,
	phr_ModeOtherCG_r12_74_encode_aper,
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_phr_ModeOtherCG_r12_tags_74,
	sizeof(asn_DEF_phr_ModeOtherCG_r12_tags_74)
		/sizeof(asn_DEF_phr_ModeOtherCG_r12_tags_74[0]) - 1, /* 1 */
	asn_DEF_phr_ModeOtherCG_r12_tags_74,	/* Same as above */
	sizeof(asn_DEF_phr_ModeOtherCG_r12_tags_74)
		/sizeof(asn_DEF_phr_ModeOtherCG_r12_tags_74[0]), /* 2 */
	&asn_PER_type_phr_ModeOtherCG_r12_constr_74,
	0, 0,	/* Defined elsewhere */
	&asn_SPC_phr_ModeOtherCG_r12_specs_74	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_setup_73[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct MAC_MainConfig__dualConnectivityPHR__setup, phr_ModeOtherCG_r12),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_phr_ModeOtherCG_r12_74,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"phr-ModeOtherCG-r12"
		},
};
static const ber_tlv_tag_t asn_DEF_setup_tags_73[] = {
	(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_setup_tag2el_73[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 } /* phr-ModeOtherCG-r12 */
};
static asn_SEQUENCE_specifics_t asn_SPC_setup_specs_73 = {
	sizeof(struct MAC_MainConfig__dualConnectivityPHR__setup),
	offsetof(struct MAC_MainConfig__dualConnectivityPHR__setup, _asn_ctx),
	asn_MAP_setup_tag2el_73,
	1,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* Start extensions */
	-1	/* Stop extensions */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_setup_73 = {
	"setup",
	"setup",
	SEQUENCE_free,
	SEQUENCE_print,
	SEQUENCE_constraint,
	SEQUENCE_decode_ber,
	SEQUENCE_encode_der,
	SEQUENCE_decode_xer,
	SEQUENCE_encode_xer,
	SEQUENCE_decode_uper,
	SEQUENCE_encode_uper,
	SEQUENCE_decode_aper,
	SEQUENCE_encode_aper,
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_setup_tags_73,
	sizeof(asn_DEF_setup_tags_73)
		/sizeof(asn_DEF_setup_tags_73[0]) - 1, /* 1 */
	asn_DEF_setup_tags_73,	/* Same as above */
	sizeof(asn_DEF_setup_tags_73)
		/sizeof(asn_DEF_setup_tags_73[0]), /* 2 */
	0,	/* No PER visible constraints */
	asn_MBR_setup_73,
	1,	/* Elements count */
	&asn_SPC_setup_specs_73	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_dualConnectivityPHR_71[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct MAC_MainConfig__dualConnectivityPHR, choice.release),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NULL,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"release"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct MAC_MainConfig__dualConnectivityPHR, choice.setup),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		0,
		&asn_DEF_setup_73,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"setup"
		},
};
static const asn_TYPE_tag2member_t asn_MAP_dualConnectivityPHR_tag2el_71[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* release */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 } /* setup */
};
static asn_CHOICE_specifics_t asn_SPC_dualConnectivityPHR_specs_71 = {
	sizeof(struct MAC_MainConfig__dualConnectivityPHR),
	offsetof(struct MAC_MainConfig__dualConnectivityPHR, _asn_ctx),
	offsetof(struct MAC_MainConfig__dualConnectivityPHR, present),
	sizeof(((struct MAC_MainConfig__dualConnectivityPHR *)0)->present),
	asn_MAP_dualConnectivityPHR_tag2el_71,
	2,	/* Count of tags in the map */
	0,
	-1	/* Extensions start */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_dualConnectivityPHR_71 = {
	"dualConnectivityPHR",
	"dualConnectivityPHR",
	CHOICE_free,
	CHOICE_print,
	CHOICE_constraint,
	CHOICE_decode_ber,
	CHOICE_encode_der,
	CHOICE_decode_xer,
	CHOICE_encode_xer,
	CHOICE_decode_uper,
	CHOICE_encode_uper,
	CHOICE_decode_aper,
	CHOICE_encode_aper,
	CHOICE_outmost_tag,
	0,	/* No effective tags (pointer) */
	0,	/* No effective tags (count) */
	0,	/* No tags (pointer) */
	0,	/* No tags (count) */
	&asn_PER_type_dualConnectivityPHR_constr_71,
	asn_MBR_dualConnectivityPHR_71,
	2,	/* Elements count */
	&asn_SPC_dualConnectivityPHR_specs_71	/* Additional specs */
};

static const asn_INTEGER_enum_map_t asn_MAP_logicalChannelSR_ProhibitTimer_r12_value2enum_80[] = {
	{ 0,	4,	"sf20" },
	{ 1,	4,	"sf40" },
	{ 2,	4,	"sf64" },
	{ 3,	5,	"sf128" },
	{ 4,	5,	"sf512" },
	{ 5,	6,	"sf1024" },
	{ 6,	6,	"sf2560" },
	{ 7,	6,	"spare1" }
};
static const unsigned int asn_MAP_logicalChannelSR_ProhibitTimer_r12_enum2value_80[] = {
	5,	/* sf1024(5) */
	3,	/* sf128(3) */
	0,	/* sf20(0) */
	6,	/* sf2560(6) */
	1,	/* sf40(1) */
	4,	/* sf512(4) */
	2,	/* sf64(2) */
	7	/* spare1(7) */
};
static const asn_INTEGER_specifics_t asn_SPC_logicalChannelSR_ProhibitTimer_r12_specs_80 = {
	asn_MAP_logicalChannelSR_ProhibitTimer_r12_value2enum_80,	/* "tag" => N; sorted by tag */
	asn_MAP_logicalChannelSR_ProhibitTimer_r12_enum2value_80,	/* N => "tag"; sorted by N */
	8,	/* Number of elements in the maps */
	0,	/* Enumeration is not extensible */
	1,	/* Strict enumeration */
	0,	/* Native long size */
	0
};
static const ber_tlv_tag_t asn_DEF_logicalChannelSR_ProhibitTimer_r12_tags_80[] = {
	(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (10 << 2))
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_logicalChannelSR_ProhibitTimer_r12_80 = {
	"logicalChannelSR-ProhibitTimer-r12",
	"logicalChannelSR-ProhibitTimer-r12",
	logicalChannelSR_ProhibitTimer_r12_80_free,
	logicalChannelSR_ProhibitTimer_r12_80_print,
	logicalChannelSR_ProhibitTimer_r12_80_constraint,
	logicalChannelSR_ProhibitTimer_r12_80_decode_ber,
	logicalChannelSR_ProhibitTimer_r12_80_encode_der,
	logicalChannelSR_ProhibitTimer_r12_80_decode_xer,
	logicalChannelSR_ProhibitTimer_r12_80_encode_xer,
	logicalChannelSR_ProhibitTimer_r12_80_decode_uper,
	logicalChannelSR_ProhibitTimer_r12_80_encode_uper,
	logicalChannelSR_ProhibitTimer_r12_80_decode_aper,
	logicalChannelSR_ProhibitTimer_r12_80_encode_aper,
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_logicalChannelSR_ProhibitTimer_r12_tags_80,
	sizeof(asn_DEF_logicalChannelSR_ProhibitTimer_r12_tags_80)
		/sizeof(asn_DEF_logicalChannelSR_ProhibitTimer_r12_tags_80[0]) - 1, /* 1 */
	asn_DEF_logicalChannelSR_ProhibitTimer_r12_tags_80,	/* Same as above */
	sizeof(asn_DEF_logicalChannelSR_ProhibitTimer_r12_tags_80)
		/sizeof(asn_DEF_logicalChannelSR_ProhibitTimer_r12_tags_80[0]), /* 2 */
	&asn_PER_type_logicalChannelSR_ProhibitTimer_r12_constr_80,
	0, 0,	/* Defined elsewhere */
	&asn_SPC_logicalChannelSR_ProhibitTimer_r12_specs_80	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_setup_79[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct MAC_MainConfig__logicalChannelSR_Config_r12__setup, logicalChannelSR_ProhibitTimer_r12),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_logicalChannelSR_ProhibitTimer_r12_80,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"logicalChannelSR-ProhibitTimer-r12"
		},
};
static const ber_tlv_tag_t asn_DEF_setup_tags_79[] = {
	(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_setup_tag2el_79[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 } /* logicalChannelSR-ProhibitTimer-r12 */
};
static asn_SEQUENCE_specifics_t asn_SPC_setup_specs_79 = {
	sizeof(struct MAC_MainConfig__logicalChannelSR_Config_r12__setup),
	offsetof(struct MAC_MainConfig__logicalChannelSR_Config_r12__setup, _asn_ctx),
	asn_MAP_setup_tag2el_79,
	1,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* Start extensions */
	-1	/* Stop extensions */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_setup_79 = {
	"setup",
	"setup",
	SEQUENCE_free,
	SEQUENCE_print,
	SEQUENCE_constraint,
	SEQUENCE_decode_ber,
	SEQUENCE_encode_der,
	SEQUENCE_decode_xer,
	SEQUENCE_encode_xer,
	SEQUENCE_decode_uper,
	SEQUENCE_encode_uper,
	SEQUENCE_decode_aper,
	SEQUENCE_encode_aper,
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_setup_tags_79,
	sizeof(asn_DEF_setup_tags_79)
		/sizeof(asn_DEF_setup_tags_79[0]) - 1, /* 1 */
	asn_DEF_setup_tags_79,	/* Same as above */
	sizeof(asn_DEF_setup_tags_79)
		/sizeof(asn_DEF_setup_tags_79[0]), /* 2 */
	0,	/* No PER visible constraints */
	asn_MBR_setup_79,
	1,	/* Elements count */
	&asn_SPC_setup_specs_79	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_logicalChannelSR_Config_r12_77[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct MAC_MainConfig__logicalChannelSR_Config_r12, choice.release),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NULL,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"release"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct MAC_MainConfig__logicalChannelSR_Config_r12, choice.setup),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		0,
		&asn_DEF_setup_79,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"setup"
		},
};
static const asn_TYPE_tag2member_t asn_MAP_logicalChannelSR_Config_r12_tag2el_77[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* release */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 } /* setup */
};
static asn_CHOICE_specifics_t asn_SPC_logicalChannelSR_Config_r12_specs_77 = {
	sizeof(struct MAC_MainConfig__logicalChannelSR_Config_r12),
	offsetof(struct MAC_MainConfig__logicalChannelSR_Config_r12, _asn_ctx),
	offsetof(struct MAC_MainConfig__logicalChannelSR_Config_r12, present),
	sizeof(((struct MAC_MainConfig__logicalChannelSR_Config_r12 *)0)->present),
	asn_MAP_logicalChannelSR_Config_r12_tag2el_77,
	2,	/* Count of tags in the map */
	0,
	-1	/* Extensions start */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_logicalChannelSR_Config_r12_77 = {
	"logicalChannelSR-Config-r12",
	"logicalChannelSR-Config-r12",
	CHOICE_free,
	CHOICE_print,
	CHOICE_constraint,
	CHOICE_decode_ber,
	CHOICE_encode_der,
	CHOICE_decode_xer,
	CHOICE_encode_xer,
	CHOICE_decode_uper,
	CHOICE_encode_uper,
	CHOICE_decode_aper,
	CHOICE_encode_aper,
	CHOICE_outmost_tag,
	0,	/* No effective tags (pointer) */
	0,	/* No effective tags (count) */
	0,	/* No tags (pointer) */
	0,	/* No tags (count) */
	&asn_PER_type_logicalChannelSR_Config_r12_constr_77,
	asn_MBR_logicalChannelSR_Config_r12_77,
	2,	/* Elements count */
	&asn_SPC_logicalChannelSR_Config_r12_specs_77	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_setup_93[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct MAC_MainConfig__eDRX_Config_CycleStartOffset_r13__setup, choice.sf5120),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NativeInteger,
		memb_sf5120_constraint_93,
		&asn_PER_memb_sf5120_constr_94,
		0,
		"sf5120"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct MAC_MainConfig__eDRX_Config_CycleStartOffset_r13__setup, choice.sf10240),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NativeInteger,
		memb_sf10240_constraint_93,
		&asn_PER_memb_sf10240_constr_95,
		0,
		"sf10240"
		},
};
static const asn_TYPE_tag2member_t asn_MAP_setup_tag2el_93[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* sf5120 */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 } /* sf10240 */
};
static asn_CHOICE_specifics_t asn_SPC_setup_specs_93 = {
	sizeof(struct MAC_MainConfig__eDRX_Config_CycleStartOffset_r13__setup),
	offsetof(struct MAC_MainConfig__eDRX_Config_CycleStartOffset_r13__setup, _asn_ctx),
	offsetof(struct MAC_MainConfig__eDRX_Config_CycleStartOffset_r13__setup, present),
	sizeof(((struct MAC_MainConfig__eDRX_Config_CycleStartOffset_r13__setup *)0)->present),
	asn_MAP_setup_tag2el_93,
	2,	/* Count of tags in the map */
	0,
	-1	/* Extensions start */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_setup_93 = {
	"setup",
	"setup",
	CHOICE_free,
	CHOICE_print,
	CHOICE_constraint,
	CHOICE_decode_ber,
	CHOICE_encode_der,
	CHOICE_decode_xer,
	CHOICE_encode_xer,
	CHOICE_decode_uper,
	CHOICE_encode_uper,
	CHOICE_decode_aper,
	CHOICE_encode_aper,
	CHOICE_outmost_tag,
	0,	/* No effective tags (pointer) */
	0,	/* No effective tags (count) */
	0,	/* No tags (pointer) */
	0,	/* No tags (count) */
	&asn_PER_type_setup_constr_93,
	asn_MBR_setup_93,
	2,	/* Elements count */
	&asn_SPC_setup_specs_93	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_eDRX_Config_CycleStartOffset_r13_91[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct MAC_MainConfig__eDRX_Config_CycleStartOffset_r13, choice.release),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NULL,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"release"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct MAC_MainConfig__eDRX_Config_CycleStartOffset_r13, choice.setup),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_setup_93,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"setup"
		},
};
static const asn_TYPE_tag2member_t asn_MAP_eDRX_Config_CycleStartOffset_r13_tag2el_91[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* release */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 } /* setup */
};
static asn_CHOICE_specifics_t asn_SPC_eDRX_Config_CycleStartOffset_r13_specs_91 = {
	sizeof(struct MAC_MainConfig__eDRX_Config_CycleStartOffset_r13),
	offsetof(struct MAC_MainConfig__eDRX_Config_CycleStartOffset_r13, _asn_ctx),
	offsetof(struct MAC_MainConfig__eDRX_Config_CycleStartOffset_r13, present),
	sizeof(((struct MAC_MainConfig__eDRX_Config_CycleStartOffset_r13 *)0)->present),
	asn_MAP_eDRX_Config_CycleStartOffset_r13_tag2el_91,
	2,	/* Count of tags in the map */
	0,
	-1	/* Extensions start */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_eDRX_Config_CycleStartOffset_r13_91 = {
	"eDRX-Config-CycleStartOffset-r13",
	"eDRX-Config-CycleStartOffset-r13",
	CHOICE_free,
	CHOICE_print,
	CHOICE_constraint,
	CHOICE_decode_ber,
	CHOICE_encode_der,
	CHOICE_decode_xer,
	CHOICE_encode_xer,
	CHOICE_decode_uper,
	CHOICE_encode_uper,
	CHOICE_decode_aper,
	CHOICE_encode_aper,
	CHOICE_outmost_tag,
	0,	/* No effective tags (pointer) */
	0,	/* No effective tags (count) */
	0,	/* No tags (pointer) */
	0,	/* No tags (count) */
	&asn_PER_type_eDRX_Config_CycleStartOffset_r13_constr_91,
	asn_MBR_eDRX_Config_CycleStartOffset_r13_91,
	2,	/* Elements count */
	&asn_SPC_eDRX_Config_CycleStartOffset_r13_specs_91	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_drx_Config_r13_96[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct MAC_MainConfig__drx_Config_r13, choice.release),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NULL,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"release"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct MAC_MainConfig__drx_Config_r13, choice.setup),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_DRX_Config_r13,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"setup"
		},
};
static const asn_TYPE_tag2member_t asn_MAP_drx_Config_r13_tag2el_96[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* release */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 } /* setup */
};
static asn_CHOICE_specifics_t asn_SPC_drx_Config_r13_specs_96 = {
	sizeof(struct MAC_MainConfig__drx_Config_r13),
	offsetof(struct MAC_MainConfig__drx_Config_r13, _asn_ctx),
	offsetof(struct MAC_MainConfig__drx_Config_r13, present),
	sizeof(((struct MAC_MainConfig__drx_Config_r13 *)0)->present),
	asn_MAP_drx_Config_r13_tag2el_96,
	2,	/* Count of tags in the map */
	0,
	-1	/* Extensions start */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_drx_Config_r13_96 = {
	"drx-Config-r13",
	"drx-Config-r13",
	CHOICE_free,
	CHOICE_print,
	CHOICE_constraint,
	CHOICE_decode_ber,
	CHOICE_encode_der,
	CHOICE_decode_xer,
	CHOICE_encode_xer,
	CHOICE_decode_uper,
	CHOICE_encode_uper,
	CHOICE_decode_aper,
	CHOICE_encode_aper,
	CHOICE_outmost_tag,
	0,	/* No effective tags (pointer) */
	0,	/* No effective tags (count) */
	0,	/* No tags (pointer) */
	0,	/* No tags (count) */
	&asn_PER_type_drx_Config_r13_constr_96,
	asn_MBR_drx_Config_r13_96,
	2,	/* Elements count */
	&asn_SPC_drx_Config_r13_specs_96	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_MAC_MainConfig_1[] = {
	{ ATF_POINTER, 2, offsetof(struct MAC_MainConfig, ul_SCH_Config),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		0,
		&asn_DEF_ul_SCH_Config_2,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"ul-SCH-Config"
		},
	{ ATF_POINTER, 1, offsetof(struct MAC_MainConfig, drx_Config),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_DRX_Config,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"drx-Config"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct MAC_MainConfig, timeAlignmentTimerDedicated),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_TimeAlignmentTimer,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"timeAlignmentTimerDedicated"
		},
	{ ATF_POINTER, 13, offsetof(struct MAC_MainConfig, phr_Config),
		(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_phr_Config_25,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"phr-Config"
		},
	{ ATF_POINTER, 12, offsetof(struct MAC_MainConfig, sr_ProhibitTimer_r9),
		(ASN_TAG_CLASS_CONTEXT | (4 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NativeInteger,
		memb_sr_ProhibitTimer_r9_constraint_1,
		&asn_PER_memb_sr_ProhibitTimer_r9_constr_52,
		0,
		"sr-ProhibitTimer-r9"
		},
	{ ATF_POINTER, 11, offsetof(struct MAC_MainConfig, mac_MainConfig_v1020),
		(ASN_TAG_CLASS_CONTEXT | (5 << 2)),
		0,
		&asn_DEF_mac_MainConfig_v1020_53,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"mac-MainConfig-v1020"
		},
	{ ATF_POINTER, 10, offsetof(struct MAC_MainConfig, stag_ToReleaseList_r11),
		(ASN_TAG_CLASS_CONTEXT | (6 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_STAG_ToReleaseList_r11,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"stag-ToReleaseList-r11"
		},
	{ ATF_POINTER, 9, offsetof(struct MAC_MainConfig, stag_ToAddModList_r11),
		(ASN_TAG_CLASS_CONTEXT | (7 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_STAG_ToAddModList_r11,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"stag-ToAddModList-r11"
		},
	{ ATF_POINTER, 8, offsetof(struct MAC_MainConfig, drx_Config_v1130),
		(ASN_TAG_CLASS_CONTEXT | (8 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_DRX_Config_v1130,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"drx-Config-v1130"
		},
	{ ATF_POINTER, 7, offsetof(struct MAC_MainConfig, e_HARQ_Pattern_r12),
		(ASN_TAG_CLASS_CONTEXT | (9 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_BOOLEAN,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"e-HARQ-Pattern-r12"
		},
	{ ATF_POINTER, 6, offsetof(struct MAC_MainConfig, dualConnectivityPHR),
		(ASN_TAG_CLASS_CONTEXT | (10 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_dualConnectivityPHR_71,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"dualConnectivityPHR"
		},
	{ ATF_POINTER, 5, offsetof(struct MAC_MainConfig, logicalChannelSR_Config_r12),
		(ASN_TAG_CLASS_CONTEXT | (11 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_logicalChannelSR_Config_r12_77,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"logicalChannelSR-Config-r12"
		},
	{ ATF_POINTER, 4, offsetof(struct MAC_MainConfig, drx_Config_v1310),
		(ASN_TAG_CLASS_CONTEXT | (12 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_DRX_Config_v1310,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"drx-Config-v1310"
		},
	{ ATF_POINTER, 3, offsetof(struct MAC_MainConfig, extendedPHR2_r13),
		(ASN_TAG_CLASS_CONTEXT | (13 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_BOOLEAN,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"extendedPHR2-r13"
		},
	{ ATF_POINTER, 2, offsetof(struct MAC_MainConfig, eDRX_Config_CycleStartOffset_r13),
		(ASN_TAG_CLASS_CONTEXT | (14 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_eDRX_Config_CycleStartOffset_r13_91,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"eDRX-Config-CycleStartOffset-r13"
		},
	{ ATF_POINTER, 1, offsetof(struct MAC_MainConfig, drx_Config_r13),
		(ASN_TAG_CLASS_CONTEXT | (15 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_drx_Config_r13_96,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"drx-Config-r13"
		},
};
static const int asn_MAP_MAC_MainConfig_oms_1[] = { 0, 1, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15 };
static const ber_tlv_tag_t asn_DEF_MAC_MainConfig_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_MAC_MainConfig_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* ul-SCH-Config */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* drx-Config */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 }, /* timeAlignmentTimerDedicated */
    { (ASN_TAG_CLASS_CONTEXT | (3 << 2)), 3, 0, 0 }, /* phr-Config */
    { (ASN_TAG_CLASS_CONTEXT | (4 << 2)), 4, 0, 0 }, /* sr-ProhibitTimer-r9 */
    { (ASN_TAG_CLASS_CONTEXT | (5 << 2)), 5, 0, 0 }, /* mac-MainConfig-v1020 */
    { (ASN_TAG_CLASS_CONTEXT | (6 << 2)), 6, 0, 0 }, /* stag-ToReleaseList-r11 */
    { (ASN_TAG_CLASS_CONTEXT | (7 << 2)), 7, 0, 0 }, /* stag-ToAddModList-r11 */
    { (ASN_TAG_CLASS_CONTEXT | (8 << 2)), 8, 0, 0 }, /* drx-Config-v1130 */
    { (ASN_TAG_CLASS_CONTEXT | (9 << 2)), 9, 0, 0 }, /* e-HARQ-Pattern-r12 */
    { (ASN_TAG_CLASS_CONTEXT | (10 << 2)), 10, 0, 0 }, /* dualConnectivityPHR */
    { (ASN_TAG_CLASS_CONTEXT | (11 << 2)), 11, 0, 0 }, /* logicalChannelSR-Config-r12 */
    { (ASN_TAG_CLASS_CONTEXT | (12 << 2)), 12, 0, 0 }, /* drx-Config-v1310 */
    { (ASN_TAG_CLASS_CONTEXT | (13 << 2)), 13, 0, 0 }, /* extendedPHR2-r13 */
    { (ASN_TAG_CLASS_CONTEXT | (14 << 2)), 14, 0, 0 }, /* eDRX-Config-CycleStartOffset-r13 */
    { (ASN_TAG_CLASS_CONTEXT | (15 << 2)), 15, 0, 0 } /* drx-Config-r13 */
};
static asn_SEQUENCE_specifics_t asn_SPC_MAC_MainConfig_specs_1 = {
	sizeof(struct MAC_MainConfig),
	offsetof(struct MAC_MainConfig, _asn_ctx),
	asn_MAP_MAC_MainConfig_tag2el_1,
	16,	/* Count of tags in the map */
	asn_MAP_MAC_MainConfig_oms_1,	/* Optional members */
	3, 12,	/* Root/Additions */
	3,	/* Start extensions */
	17	/* Stop extensions */
};
asn_TYPE_descriptor_t asn_DEF_MAC_MainConfig = {
	"MAC-MainConfig",
	"MAC-MainConfig",
	SEQUENCE_free,
	SEQUENCE_print,
	SEQUENCE_constraint,
	SEQUENCE_decode_ber,
	SEQUENCE_encode_der,
	SEQUENCE_decode_xer,
	SEQUENCE_encode_xer,
	SEQUENCE_decode_uper,
	SEQUENCE_encode_uper,
	SEQUENCE_decode_aper,
	SEQUENCE_encode_aper,
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_MAC_MainConfig_tags_1,
	sizeof(asn_DEF_MAC_MainConfig_tags_1)
		/sizeof(asn_DEF_MAC_MainConfig_tags_1[0]), /* 1 */
	asn_DEF_MAC_MainConfig_tags_1,	/* Same as above */
	sizeof(asn_DEF_MAC_MainConfig_tags_1)
		/sizeof(asn_DEF_MAC_MainConfig_tags_1[0]), /* 1 */
	0,	/* No PER visible constraints */
	asn_MBR_MAC_MainConfig_1,
	16,	/* Elements count */
	&asn_SPC_MAC_MainConfig_specs_1	/* Additional specs */
};

