/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "EUTRA-RRC-Definitions"
 * 	found in "../asn1_defs/EUTRA-RRC-Definitions.asn"
 * 	`asn1c -gen-PER -fcompound-names -fnative-types`
 */

#ifndef	_MeasConfig_H_
#define	_MeasConfig_H_


#include <asn_application.h>

/* Including external dependencies */
#include "RSRP-Range.h"
#include <BOOLEAN.h>
#include <NULL.h>
#include "MobilityStateParameters.h"
#include "SpeedStateScaleFactors.h"
#include <constr_SEQUENCE.h>
#include <constr_CHOICE.h>
#include "MeasScaleFactor-r12.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum MeasConfig__speedStatePars_PR {
	MeasConfig__speedStatePars_PR_NOTHING,	/* No components present */
	MeasConfig__speedStatePars_PR_release,
	MeasConfig__speedStatePars_PR_setup
} MeasConfig__speedStatePars_PR;
typedef enum MeasConfig__measScaleFactor_r12_PR {
	MeasConfig__measScaleFactor_r12_PR_NOTHING,	/* No components present */
	MeasConfig__measScaleFactor_r12_PR_release,
	MeasConfig__measScaleFactor_r12_PR_setup
} MeasConfig__measScaleFactor_r12_PR;

/* Forward declarations */
struct MeasObjectToRemoveList;
struct MeasObjectToAddModList;
struct ReportConfigToRemoveList;
struct ReportConfigToAddModList;
struct MeasIdToRemoveList;
struct MeasIdToAddModList;
struct QuantityConfig;
struct MeasGapConfig;
struct PreRegistrationInfoHRPD;
struct MeasObjectToAddModList_v9e0;
struct MeasIdToRemoveListExt_r12;
struct MeasIdToAddModListExt_r12;
struct MeasObjectToRemoveListExt_r13;
struct MeasObjectToAddModListExt_r13;
struct MeasIdToAddModList_v1310;
struct MeasIdToAddModListExt_v1310;

/* MeasConfig */
typedef struct MeasConfig {
	struct MeasObjectToRemoveList	*measObjectToRemoveList	/* OPTIONAL */;
	struct MeasObjectToAddModList	*measObjectToAddModList	/* OPTIONAL */;
	struct ReportConfigToRemoveList	*reportConfigToRemoveList	/* OPTIONAL */;
	struct ReportConfigToAddModList	*reportConfigToAddModList	/* OPTIONAL */;
	struct MeasIdToRemoveList	*measIdToRemoveList	/* OPTIONAL */;
	struct MeasIdToAddModList	*measIdToAddModList	/* OPTIONAL */;
	struct QuantityConfig	*quantityConfig	/* OPTIONAL */;
	struct MeasGapConfig	*measGapConfig	/* OPTIONAL */;
	RSRP_Range_t	*s_Measure	/* OPTIONAL */;
	struct PreRegistrationInfoHRPD	*preRegistrationInfoHRPD	/* OPTIONAL */;
	struct MeasConfig__speedStatePars {
		MeasConfig__speedStatePars_PR present;
		union MeasConfig__speedStatePars_u {
			NULL_t	 release;
			struct MeasConfig__speedStatePars__setup {
				MobilityStateParameters_t	 mobilityStateParameters;
				SpeedStateScaleFactors_t	 timeToTrigger_SF;
				
				/* Context for parsing across buffer boundaries */
				asn_struct_ctx_t _asn_ctx;
			} setup;
		} choice;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *speedStatePars;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	struct MeasObjectToAddModList_v9e0	*measObjectToAddModList_v9e0	/* OPTIONAL */;
	BOOLEAN_t	*allowInterruptions_r11	/* OPTIONAL */;
	struct MeasConfig__measScaleFactor_r12 {
		MeasConfig__measScaleFactor_r12_PR present;
		union MeasConfig__measScaleFactor_r12_u {
			NULL_t	 release;
			MeasScaleFactor_r12_t	 setup;
		} choice;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *measScaleFactor_r12;
	struct MeasIdToRemoveListExt_r12	*measIdToRemoveListExt_r12	/* OPTIONAL */;
	struct MeasIdToAddModListExt_r12	*measIdToAddModListExt_r12	/* OPTIONAL */;
	BOOLEAN_t	*measRSRQ_OnAllSymbols_r12	/* OPTIONAL */;
	struct MeasObjectToRemoveListExt_r13	*measObjectToRemoveListExt_r13	/* OPTIONAL */;
	struct MeasObjectToAddModListExt_r13	*measObjectToAddModListExt_r13	/* OPTIONAL */;
	struct MeasIdToAddModList_v1310	*measIdToAddModList_v1310	/* OPTIONAL */;
	struct MeasIdToAddModListExt_v1310	*measIdToAddModListExt_v1310	/* OPTIONAL */;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} MeasConfig_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_MeasConfig;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "MeasObjectToRemoveList.h"
#include "MeasObjectToAddModList.h"
#include "ReportConfigToRemoveList.h"
#include "ReportConfigToAddModList.h"
#include "MeasIdToRemoveList.h"
#include "MeasIdToAddModList.h"
#include "QuantityConfig.h"
#include "MeasGapConfig.h"
#include "PreRegistrationInfoHRPD.h"
#include "MeasObjectToAddModList-v9e0.h"
#include "MeasIdToRemoveListExt-r12.h"
#include "MeasIdToAddModListExt-r12.h"
#include "MeasObjectToRemoveListExt-r13.h"
#include "MeasObjectToAddModListExt-r13.h"
#include "MeasIdToAddModList-v1310.h"
#include "MeasIdToAddModListExt-v1310.h"

#endif	/* _MeasConfig_H_ */
#include <asn_internal.h>
