/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "EUTRA-RRC-Definitions"
 * 	found in "../asn1_defs/EUTRA-RRC-Definitions.asn"
 * 	`asn1c -gen-PER -fcompound-names -fnative-types`
 */

#ifndef	_RedistributionInterFreqInfo_r13_H_
#define	_RedistributionInterFreqInfo_r13_H_


#include <asn_application.h>

/* Including external dependencies */
#include "RedistributionFactor-r13.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct RedistributionNeighCellList_r13;

/* RedistributionInterFreqInfo-r13 */
typedef struct RedistributionInterFreqInfo_r13 {
	RedistributionFactor_r13_t	*redistributionFactorFreq_r13	/* OPTIONAL */;
	struct RedistributionNeighCellList_r13	*redistributionNeighCellList_r13	/* OPTIONAL */;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} RedistributionInterFreqInfo_r13_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_RedistributionInterFreqInfo_r13;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "RedistributionNeighCellList-r13.h"

#endif	/* _RedistributionInterFreqInfo_r13_H_ */
#include <asn_internal.h>
