/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "EUTRA-RRC-Definitions"
 * 	found in "../asn1_defs/EUTRA-RRC-Definitions.asn"
 * 	`asn1c -gen-PER -fcompound-names -fnative-types`
 */

#include "SC-MTCH-Info-r13.h"

static int
memb_g_RNTI_r13_constraint_1(asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	const BIT_STRING_t *st = (const BIT_STRING_t *)sptr;
	size_t size;
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	if(st->size > 0) {
		/* Size in bits */
		size = 8 * st->size - (st->bits_unused & 0x07);
	} else {
		size = 0;
	}
	
	if((size == 16LL)) {
		/* Constraint check succeeded */
		return 0;
	} else {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

static int
memb_sc_mtch_neighbourCell_r13_constraint_1(asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	const BIT_STRING_t *st = (const BIT_STRING_t *)sptr;
	size_t size;
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	if(st->size > 0) {
		/* Size in bits */
		size = 8 * st->size - (st->bits_unused & 0x07);
	} else {
		size = 0;
	}
	
	if((size == 8LL)) {
		/* Constraint check succeeded */
		return 0;
	} else {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

static asn_per_constraints_t asn_PER_memb_g_RNTI_r13_constr_3 GCC_NOTUSED = {
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	{ APC_CONSTRAINED,	 0,  0,  16,  16 }	/* (SIZE(16..16)) */,
	0, 0	/* No PER value map */
};
static asn_per_constraints_t asn_PER_memb_sc_mtch_neighbourCell_r13_constr_5 GCC_NOTUSED = {
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	{ APC_CONSTRAINED,	 0,  0,  8,  8 }	/* (SIZE(8..8)) */,
	0, 0	/* No PER value map */
};
static asn_TYPE_member_t asn_MBR_SC_MTCH_Info_r13_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct SC_MTCH_Info_r13, mbmsSessionInfo_r13),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_MBMSSessionInfo_r13,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"mbmsSessionInfo-r13"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct SC_MTCH_Info_r13, g_RNTI_r13),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_BIT_STRING,
		memb_g_RNTI_r13_constraint_1,
		&asn_PER_memb_g_RNTI_r13_constr_3,
		0,
		"g-RNTI-r13"
		},
	{ ATF_POINTER, 2, offsetof(struct SC_MTCH_Info_r13, sc_mtch_schedulingInfo_r13),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_SC_MTCH_SchedulingInfo_r13,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"sc-mtch-schedulingInfo-r13"
		},
	{ ATF_POINTER, 1, offsetof(struct SC_MTCH_Info_r13, sc_mtch_neighbourCell_r13),
		(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_BIT_STRING,
		memb_sc_mtch_neighbourCell_r13_constraint_1,
		&asn_PER_memb_sc_mtch_neighbourCell_r13_constr_5,
		0,
		"sc-mtch-neighbourCell-r13"
		},
};
static const int asn_MAP_SC_MTCH_Info_r13_oms_1[] = { 2, 3 };
static const ber_tlv_tag_t asn_DEF_SC_MTCH_Info_r13_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_SC_MTCH_Info_r13_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* mbmsSessionInfo-r13 */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* g-RNTI-r13 */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 }, /* sc-mtch-schedulingInfo-r13 */
    { (ASN_TAG_CLASS_CONTEXT | (3 << 2)), 3, 0, 0 } /* sc-mtch-neighbourCell-r13 */
};
static asn_SEQUENCE_specifics_t asn_SPC_SC_MTCH_Info_r13_specs_1 = {
	sizeof(struct SC_MTCH_Info_r13),
	offsetof(struct SC_MTCH_Info_r13, _asn_ctx),
	asn_MAP_SC_MTCH_Info_r13_tag2el_1,
	4,	/* Count of tags in the map */
	asn_MAP_SC_MTCH_Info_r13_oms_1,	/* Optional members */
	2, 0,	/* Root/Additions */
	3,	/* Start extensions */
	5	/* Stop extensions */
};
asn_TYPE_descriptor_t asn_DEF_SC_MTCH_Info_r13 = {
	"SC-MTCH-Info-r13",
	"SC-MTCH-Info-r13",
	SEQUENCE_free,
	SEQUENCE_print,
	SEQUENCE_constraint,
	SEQUENCE_decode_ber,
	SEQUENCE_encode_der,
	SEQUENCE_decode_xer,
	SEQUENCE_encode_xer,
	SEQUENCE_decode_uper,
	SEQUENCE_encode_uper,
	SEQUENCE_decode_aper,
	SEQUENCE_encode_aper,
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_SC_MTCH_Info_r13_tags_1,
	sizeof(asn_DEF_SC_MTCH_Info_r13_tags_1)
		/sizeof(asn_DEF_SC_MTCH_Info_r13_tags_1[0]), /* 1 */
	asn_DEF_SC_MTCH_Info_r13_tags_1,	/* Same as above */
	sizeof(asn_DEF_SC_MTCH_Info_r13_tags_1)
		/sizeof(asn_DEF_SC_MTCH_Info_r13_tags_1[0]), /* 1 */
	0,	/* No PER visible constraints */
	asn_MBR_SC_MTCH_Info_r13_1,
	4,	/* Elements count */
	&asn_SPC_SC_MTCH_Info_r13_specs_1	/* Additional specs */
};

