/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "EUTRA-RRC-Definitions"
 * 	found in "../asn1_defs/EUTRA-RRC-Definitions.asn"
 * 	`asn1c -gen-PER -fcompound-names -fnative-types`
 */

#ifndef	_SC_MTCH_Info_r13_H_
#define	_SC_MTCH_Info_r13_H_


#include <asn_application.h>

/* Including external dependencies */
#include "MBMSSessionInfo-r13.h"
#include <BIT_STRING.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct SC_MTCH_SchedulingInfo_r13;

/* SC-MTCH-Info-r13 */
typedef struct SC_MTCH_Info_r13 {
	MBMSSessionInfo_r13_t	 mbmsSessionInfo_r13;
	BIT_STRING_t	 g_RNTI_r13;
	struct SC_MTCH_SchedulingInfo_r13	*sc_mtch_schedulingInfo_r13	/* OPTIONAL */;
	BIT_STRING_t	*sc_mtch_neighbourCell_r13	/* OPTIONAL */;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} SC_MTCH_Info_r13_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_SC_MTCH_Info_r13;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "SC-MTCH-SchedulingInfo-r13.h"

#endif	/* _SC_MTCH_Info_r13_H_ */
#include <asn_internal.h>
