/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "EUTRA-RRC-Definitions"
 * 	found in "../asn1_defs/EUTRA-RRC-Definitions.asn"
 * 	`asn1c -gen-PER -fcompound-names -fnative-types`
 */

#ifndef	_UE_BasedNetwPerfMeasParameters_v1250_H_
#define	_UE_BasedNetwPerfMeasParameters_v1250_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeEnumerated.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum UE_BasedNetwPerfMeasParameters_v1250__loggedMBSFNMeasurements_r12 {
	UE_BasedNetwPerfMeasParameters_v1250__loggedMBSFNMeasurements_r12_supported	= 0
} e_UE_BasedNetwPerfMeasParameters_v1250__loggedMBSFNMeasurements_r12;

/* UE-BasedNetwPerfMeasParameters-v1250 */
typedef struct UE_BasedNetwPerfMeasParameters_v1250 {
	long	 loggedMBSFNMeasurements_r12;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} UE_BasedNetwPerfMeasParameters_v1250_t;

/* Implementation */
/* extern asn_TYPE_descriptor_t asn_DEF_loggedMBSFNMeasurements_r12_2;	// (Use -fall-defs-global to expose) */
extern asn_TYPE_descriptor_t asn_DEF_UE_BasedNetwPerfMeasParameters_v1250;

#ifdef __cplusplus
}
#endif

#endif	/* _UE_BasedNetwPerfMeasParameters_v1250_H_ */
#include <asn_internal.h>
