/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "EUTRA-RRC-Definitions"
 * 	found in "../asn1_defs/EUTRA-RRC-Definitions.asn"
 * 	`asn1c -gen-PER -fcompound-names -fnative-types`
 */

#ifndef	_UE_EUTRA_Capability_v1330_IEs_H_
#define	_UE_EUTRA_Capability_v1330_IEs_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>
#include <NativeEnumerated.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum UE_EUTRA_Capability_v1330_IEs__ue_CE_NeedULGaps_r13 {
	UE_EUTRA_Capability_v1330_IEs__ue_CE_NeedULGaps_r13_true	= 0
} e_UE_EUTRA_Capability_v1330_IEs__ue_CE_NeedULGaps_r13;

/* Forward declarations */
struct PhyLayerParameters_v1330;

/* UE-EUTRA-Capability-v1330-IEs */
typedef struct UE_EUTRA_Capability_v1330_IEs {
	long	*ue_CategoryDL_v13xy	/* OPTIONAL */;
	struct PhyLayerParameters_v1330	*phyLayerParameters_v1330	/* OPTIONAL */;
	long	*ue_CE_NeedULGaps_r13	/* OPTIONAL */;
	struct UE_EUTRA_Capability_v1330_IEs__nonCriticalExtension {
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *nonCriticalExtension;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} UE_EUTRA_Capability_v1330_IEs_t;

/* Implementation */
/* extern asn_TYPE_descriptor_t asn_DEF_ue_CE_NeedULGaps_r13_4;	// (Use -fall-defs-global to expose) */
extern asn_TYPE_descriptor_t asn_DEF_UE_EUTRA_Capability_v1330_IEs;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "PhyLayerParameters-v1330.h"

#endif	/* _UE_EUTRA_Capability_v1330_IEs_H_ */
#include <asn_internal.h>
