/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "EUTRA-RRC-Definitions"
 * 	found in "../asn1_defs/EUTRA-RRC-Definitions.asn"
 * 	`asn1c -gen-PER -fcompound-names -fnative-types`
 */

#ifndef	_UE_RadioPagingInfo_r12_H_
#define	_UE_RadioPagingInfo_r12_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>
#include <NativeEnumerated.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum UE_RadioPagingInfo_r12__ue_CategoryDL_v1310 {
	UE_RadioPagingInfo_r12__ue_CategoryDL_v1310_m1	= 0
} e_UE_RadioPagingInfo_r12__ue_CategoryDL_v1310;
typedef enum UE_RadioPagingInfo_r12__ce_ModeA_r13 {
	UE_RadioPagingInfo_r12__ce_ModeA_r13_true	= 0
} e_UE_RadioPagingInfo_r12__ce_ModeA_r13;
typedef enum UE_RadioPagingInfo_r12__ce_ModeB_r13 {
	UE_RadioPagingInfo_r12__ce_ModeB_r13_true	= 0
} e_UE_RadioPagingInfo_r12__ce_ModeB_r13;

/* UE-RadioPagingInfo-r12 */
typedef struct UE_RadioPagingInfo_r12 {
	long	*ue_Category_v1250	/* OPTIONAL */;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	long	*ue_CategoryDL_v1310	/* OPTIONAL */;
	long	*ce_ModeA_r13	/* OPTIONAL */;
	long	*ce_ModeB_r13	/* OPTIONAL */;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} UE_RadioPagingInfo_r12_t;

/* Implementation */
/* extern asn_TYPE_descriptor_t asn_DEF_ue_CategoryDL_v1310_4;	// (Use -fall-defs-global to expose) */
/* extern asn_TYPE_descriptor_t asn_DEF_ce_ModeA_r13_6;	// (Use -fall-defs-global to expose) */
/* extern asn_TYPE_descriptor_t asn_DEF_ce_ModeB_r13_8;	// (Use -fall-defs-global to expose) */
extern asn_TYPE_descriptor_t asn_DEF_UE_RadioPagingInfo_r12;

#ifdef __cplusplus
}
#endif

#endif	/* _UE_RadioPagingInfo_r12_H_ */
#include <asn_internal.h>
